------------------------------------------------BASE DE DATOS DEL PROYECTO
CREATE DATABASE IF NOT EXISTS PROYECTO;

-------------------------------------------------------------CAPA LANDING 
--CREAR ESQUEMASPROYECTO.CLEANSED_MEDICARE
CREATE SCHEMA IF NOT EXISTS PROYECTO.LANDING_MEDICARE;
CREATE SCHEMA IF NOT EXISTS PROYECTO.LANDING_NEXTBIO;
CREATE SCHEMA IF NOT EXISTS PROYECTO.LANDING_PRODUCTOS;

-----------------------------------------------------------------CAPA RAW
--CREAR ESQUEMAS
CREATE SCHEMA IF NOT EXISTS PROYECTO.RAW_NEXTBIO;
CREATE SCHEMA IF NOT EXISTS PROYECTO.RAW_PRODUCTOS;
CREATE SCHEMA IF NOT EXISTS PROYECTO.RAW_MEDICARE; 

-------------------------------------------------------------CAPA CLEANSED
--CREAR ESQUEMAS
CREATE SCHEMA IF NOT EXISTS PROYECTO.CLEANSED_MEDICARE;
CREATE SCHEMA IF NOT EXISTS PROYECTO.CLEANSED_NEXTBIO;
CREATE SCHEMA IF NOT EXISTS PROYECTO.CLEANSED_PRODUCTOS;

---------------------------------------------------------------STREAMS Y TASKS---------------
--CREAR ESQUEMA
CREATE SCHEMA IF NOT EXISTS PROYECTO.STREAMS;
CREATE SCHEMA IF NOT EXISTS PROYECTO.TASKS;


