-- sp_deploy_optimized.sql
-- Capa OPTIMIZED: crea el esquema y el procedimiento de despliegue.
--
-- Las definiciones completas y documentadas de cada vista estan en:
--   view_mantenimiento_equipos.sql
--   view_monitorizacion_pacientes.sql
--   view_ensayos_clinicos.sql
--
-- FASE 0: ejecuta este fichero  -> crea el esquema OPTIMIZED y define el SP
-- FASE 5: llama al SP           -> crea/actualiza las 3 vistas

CREATE SCHEMA IF NOT EXISTS OPTIMIZED;

CREATE OR REPLACE PROCEDURE OPTIMIZED.SP_DEPLOY_OPTIMIZED()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

    -- -------------------------------------------------------
    -- Vista 1: Mantenimiento de equipos
    -- -------------------------------------------------------
    CREATE OR REPLACE VIEW OPTIMIZED.MANTENIMIENTO_EQUIPOS AS
    SELECT
        f.ID_ORDEN,
        fe.FECHA, fe.ANIO, fe.SEMESTRE, fe.TRIMESTRE, fe.MES, fe.NOMBRE_MES,
        fe.SEMANA_ANIO, fe.DIA, fe.NOMBRE_DIA, fe.ES_FIN_SEMANA,
        eq.NOMBRE_EQUIPO, eq.NUMERO_SERIE, eq.MODELO, eq.CLASE_RIESGO,
        eq.ESTADO_EQUIPO, eq.DEPARTAMENTO_ACTUAL AS DEPARTAMENTO_EQUIPO,
        eq.UBICACION_ACTUAL AS UBICACION_EQUIPO, eq.FECHA_ADQUISICION, eq.FECHA_FIN_GARANTIA,
        tc.NOMBRE AS NOMBRE_TECNICO, tc.APELLIDOS AS APELLIDOS_TECNICO,
        tc.ESPECIALIDAD AS ESPECIALIDAD_TECNICO, tc.NIVEL_CERTIFICACION, tc.ANIOS_EXPERIENCIA,
        dp.NOMBRE_DEPARTAMENTO, dp.NIVEL_JERARQUIA AS NIVEL_JERARQUIA_DEPARTAMENTO,
        ub.EDIFICIO, ub.PLANTA, ub.ALA, ub.SALA, ub.TIPO_SALA,
        fa.NOMBRE_FABRICANTE, fa.PAIS_ORIGEN, fa.CERTIFICACION_ISO,
        pm.TIPO_MANTENIMIENTO, pm.PRIORIDAD, pm.GRAVEDAD,
        pm.ES_GARANTIA, pm.REQUIERE_PARADA_EQUIPO,
        f.HORAS_TRABAJADAS, f.TARIFA_HORA, f.COSTO_REPUESTOS,
        f.COSTO_MANO_OBRA, f.COSTO_TOTAL, f.DURACION_HORAS,
        f.NUMERO_PIEZAS_REEMPLAZADAS, f.INDICADOR_REINCIDENCIA
    FROM CONFORMED.FACT_MANTENIMIENTO_EQUIPOS f
    JOIN CONFORMED.DIM_FECHA                fe ON fe.SK_FECHA                = f.SK_FECHA
    JOIN CONFORMED.DIM_EQUIPO               eq ON eq.SK_EQUIPO               = f.SK_EQUIPO               AND eq.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_TECNICO              tc ON tc.SK_TECNICO              = f.SK_TECNICO              AND tc.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_DEPARTAMENTO         dp ON dp.SK_DEPARTAMENTO         = f.SK_DEPARTAMENTO
    JOIN CONFORMED.DIM_UBICACION            ub ON ub.SK_UBICACION            = f.SK_UBICACION
    JOIN CONFORMED.DIM_FABRICANTE           fa ON fa.SK_FABRICANTE           = f.SK_FABRICANTE
    JOIN CONFORMED.DIM_PERFIL_MANTENIMIENTO pm ON pm.SK_PERFIL_MANTENIMIENTO = f.SK_PERFIL_MANTENIMIENTO;

    -- -------------------------------------------------------
    -- Vista 2: Monitorizacion de pacientes
    -- -------------------------------------------------------
    CREATE OR REPLACE VIEW OPTIMIZED.MONITORIZACION_PACIENTES AS
    SELECT
        f.ID_SESION,
        fe.FECHA, fe.ANIO, fe.TRIMESTRE, fe.MES, fe.NOMBRE_MES, fe.NOMBRE_DIA, fe.ES_FIN_SEMANA,
        pa.NOMBRE AS NOMBRE_PACIENTE, pa.APELLIDOS AS APELLIDOS_PACIENTE,
        pa.FECHA_NACIMIENTO, pa.GENERO, pa.GRUPO_SANGUINEO,
        pa.CIUDAD AS CIUDAD_PACIENTE, pa.SEGURO_MEDICO, pa.TIPO_SEGURO,
        me.NOMBRE AS NOMBRE_MEDICO, me.APELLIDOS AS APELLIDOS_MEDICO,
        me.ESPECIALIDAD AS ESPECIALIDAD_MEDICO, me.NUMERO_COLEGIADO,
        eq.NOMBRE_EQUIPO, eq.CLASE_RIESGO, eq.ESTADO_EQUIPO,
        dp.NOMBRE_DEPARTAMENTO,
        ub.EDIFICIO, ub.SALA, ub.TIPO_SALA,
        di.CODIGO_CIE10, di.DESCRIPCION_DIAGNOSTICO,
        di.CATEGORIA AS CATEGORIA_DIAGNOSTICO,
        di.SUBCATEGORIA AS SUBCATEGORIA_DIAGNOSTICO, di.ES_CRONICO,
        f.DURACION_MONITORIZACION_MIN,
        f.FRECUENCIA_CARDIACA, f.PRESION_SISTOLICA, f.PRESION_DIASTOLICA,
        f.TEMPERATURA, f.SATURACION_OXIGENO, f.NIVEL_GLUCOSA, f.ALERTA_GENERADA
    FROM CONFORMED.FACT_MONITORIZACION_PACIENTES f
    JOIN CONFORMED.DIM_FECHA        fe ON fe.SK_FECHA        = f.SK_FECHA
    JOIN CONFORMED.DIM_PACIENTE     pa ON pa.SK_PACIENTE     = f.SK_PACIENTE     AND pa.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_MEDICO       me ON me.SK_MEDICO       = f.SK_MEDICO       AND me.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_EQUIPO       eq ON eq.SK_EQUIPO       = f.SK_EQUIPO       AND eq.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_DEPARTAMENTO dp ON dp.SK_DEPARTAMENTO = f.SK_DEPARTAMENTO
    JOIN CONFORMED.DIM_UBICACION    ub ON ub.SK_UBICACION    = f.SK_UBICACION
    JOIN CONFORMED.DIM_DIAGNOSTICO  di ON di.SK_DIAGNOSTICO  = f.SK_DIAGNOSTICO;

    -- -------------------------------------------------------
    -- Vista 3: Ensayos clinicos
    -- -------------------------------------------------------
    CREATE OR REPLACE VIEW OPTIMIZED.ENSAYOS_CLINICOS AS
    SELECT
        f.ID_VISITA,
        fv.FECHA AS FECHA_VISITA, fv.ANIO AS ANIO_VISITA,
        fv.TRIMESTRE AS TRIMESTRE_VISITA, fv.MES AS MES_VISITA, fv.NOMBRE_MES AS NOMBRE_MES_VISITA,
        fi.FECHA AS FECHA_INICIO_PARTICIPACION,
        ff.FECHA AS FECHA_FIN_PARTICIPACION,
        en.CODIGO_ENSAYO, en.NOMBRE_ENSAYO, en.PATROCINADOR, en.ESTADO_ENSAYO,
        en.MOLECULA_FARMACO, en.OBJETIVO_PRINCIPAL, en.FECHA_INICIO_ENSAYO, en.FECHA_FIN_PREVISTA,
        pa.NOMBRE AS NOMBRE_PACIENTE, pa.APELLIDOS AS APELLIDOS_PACIENTE,
        pa.GENERO, pa.FECHA_NACIMIENTO, pa.GRUPO_SANGUINEO,
        me.NOMBRE AS NOMBRE_MEDICO, me.APELLIDOS AS APELLIDOS_MEDICO,
        me.ESPECIALIDAD AS ESPECIALIDAD_MEDICO,
        di.CODIGO_CIE10, di.DESCRIPCION_DIAGNOSTICO,
        di.CATEGORIA AS CATEGORIA_DIAGNOSTICO, di.ES_CRONICO,
        dp.NOMBRE_DEPARTAMENTO,
        pe.FASE_ENSAYO, pe.TIPO_CIEGO, pe.TIPO_ALEATORIZACION,
        pe.GRUPO_TRATAMIENTO, pe.VIA_ADMINISTRACION,
        f.DOSIS_ADMINISTRADA, f.UNIDAD_DOSIS, f.NUMERO_EFECTOS_ADVERSOS,
        f.RESULTADO_MEDICION_PRINCIPAL, f.RESULTADO_MEDICION_SECUNDARIA, f.NIVEL_EFICACIA
    FROM CONFORMED.FACT_ENSAYOS_CLINICOS f
    JOIN      CONFORMED.DIM_FECHA         fv ON fv.SK_FECHA         = f.SK_FECHA
    JOIN      CONFORMED.DIM_FECHA         fi ON fi.SK_FECHA         = f.SK_FECHA_INICIO
    LEFT JOIN CONFORMED.DIM_FECHA         ff ON ff.SK_FECHA         = f.SK_FECHA_FIN
    JOIN      CONFORMED.DIM_ENSAYO        en ON en.SK_ENSAYO        = f.SK_ENSAYO
    JOIN      CONFORMED.DIM_PACIENTE      pa ON pa.SK_PACIENTE      = f.SK_PACIENTE      AND pa.ES_ACTUAL = TRUE
    JOIN      CONFORMED.DIM_MEDICO        me ON me.SK_MEDICO        = f.SK_MEDICO        AND me.ES_ACTUAL = TRUE
    JOIN      CONFORMED.DIM_DIAGNOSTICO   di ON di.SK_DIAGNOSTICO   = f.SK_DIAGNOSTICO
    JOIN      CONFORMED.DIM_DEPARTAMENTO  dp ON dp.SK_DEPARTAMENTO  = f.SK_DEPARTAMENTO
    JOIN      CONFORMED.DIM_PERFIL_ENSAYO pe ON pe.SK_PERFIL_ENSAYO = f.SK_PERFIL_ENSAYO;

    RETURN 'SP_DEPLOY_OPTIMIZED OK: 3 vistas creadas/actualizadas.';
END;
$$;
