-- sp_deploy_conformed.sql
-- Crea el esquema, todas las tablas de la capa CONFORMED y el SP de carga inicial.
-- Las tablas se crean vacias; los datos se cargan mediante SP_DEPLOY_CONFORMED().
--
-- Prerequisitos (orden en _FICHEROS_SETUP):
--   1. sp_merge_utils.sql    → SP_MERGE_SCD1 y SP_MERGE_SCD1_SCD2
--   2. sp_deploy_conformed.sql (este fichero) → DDL + SP_DEPLOY_CONFORMED
--   3. sp_load_conformed.sql  → SP_LOAD_* para incrementales via Task DAG
--
-- Carga inicial:
--   CALL CONFORMED.SP_DEPLOY_CONFORMED()

CREATE SCHEMA IF NOT EXISTS CONFORMED;


-- ============================================================
-- DIMENSIONES
-- ============================================================

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_FECHA (
    SK_FECHA      NUMBER      NOT NULL PRIMARY KEY,
    FECHA         DATE        NOT NULL,
    ANIO          NUMBER      NOT NULL,
    SEMESTRE      NUMBER      NOT NULL,
    TRIMESTRE     NUMBER      NOT NULL,
    MES           NUMBER      NOT NULL,
    NOMBRE_MES    VARCHAR(20) NOT NULL,
    SEMANA_ANIO   NUMBER      NOT NULL,
    DIA           NUMBER      NOT NULL,
    DIA_SEMANA    NUMBER      NOT NULL,
    NOMBRE_DIA    VARCHAR(20) NOT NULL,
    ES_FIN_SEMANA BOOLEAN     NOT NULL,
    ES_FESTIVO    BOOLEAN     NOT NULL
);

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_DEPARTAMENTO (
    SK_DEPARTAMENTO       NUMBER       NOT NULL AUTOINCREMENT PRIMARY KEY,
    ID_DEPARTAMENTO       NUMBER       NOT NULL,
    NOMBRE_DEPARTAMENTO   VARCHAR(200) NOT NULL,
    ID_DEPARTAMENTO_PADRE NUMBER,
    SK_DEPARTAMENTO_PADRE NUMBER,
    NIVEL_JERARQUIA       NUMBER       NOT NULL,
    RESPONSABLE           VARCHAR(200),
    TELEFONO_DEPARTAMENTO VARCHAR(50),
    EMAIL_DEPARTAMENTO    VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_FABRICANTE (
    SK_FABRICANTE     NUMBER        NOT NULL AUTOINCREMENT PRIMARY KEY,
    ID_FABRICANTE     NUMBER        NOT NULL,
    NOMBRE_FABRICANTE VARCHAR(200)  NOT NULL,
    PAIS_ORIGEN       VARCHAR(100),
    TELEFONO_CONTACTO VARCHAR(50),
    EMAIL_CONTACTO    VARCHAR(100),
    SITIO_WEB         VARCHAR(200),
    CERTIFICACION_ISO VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_UBICACION (
    SK_UBICACION NUMBER       NOT NULL AUTOINCREMENT PRIMARY KEY,
    ID_UBICACION NUMBER       NOT NULL,
    EDIFICIO     VARCHAR(200) NOT NULL,
    PLANTA       NUMBER,
    ALA          VARCHAR(50),
    SALA         VARCHAR(100) NOT NULL,
    TIPO_SALA    VARCHAR(100),
    CAPACIDAD    NUMBER
);

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_MEDICO (
    SK_MEDICO        NUMBER       NOT NULL AUTOINCREMENT PRIMARY KEY,
    ID_MEDICO        NUMBER       NOT NULL,
    NOMBRE           VARCHAR(100) NOT NULL,
    APELLIDOS        VARCHAR(200) NOT NULL,
    NUMERO_COLEGIADO VARCHAR(50)  NOT NULL,
    TELEFONO         VARCHAR(50),
    EMAIL            VARCHAR(100),
    ESPECIALIDAD     VARCHAR(200) NOT NULL,
    DEPARTAMENTO     VARCHAR(200),
    FECHA_INICIO     DATE         NOT NULL,
    FECHA_FIN        DATE,
    ES_ACTUAL        BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_TECNICO (
    SK_TECNICO          NUMBER       NOT NULL AUTOINCREMENT PRIMARY KEY,
    ID_TECNICO          NUMBER       NOT NULL,
    NOMBRE              VARCHAR(200) NOT NULL,
    APELLIDOS           VARCHAR(200),
    ESPECIALIDAD        VARCHAR(200),
    ANIOS_EXPERIENCIA   NUMBER,
    TELEFONO            VARCHAR(50),
    EMAIL               VARCHAR(100),
    DEPARTAMENTO        VARCHAR(200),
    NIVEL_CERTIFICACION VARCHAR(50),
    FECHA_INICIO        DATE         NOT NULL,
    FECHA_FIN           DATE,
    ES_ACTUAL           BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_PACIENTE (
    SK_PACIENTE      NUMBER       NOT NULL AUTOINCREMENT PRIMARY KEY,
    ID_PACIENTE      NUMBER       NOT NULL,
    NOMBRE           VARCHAR(100) NOT NULL,
    APELLIDOS        VARCHAR(200) NOT NULL,
    FECHA_NACIMIENTO DATE,
    GENERO           VARCHAR(20),
    TELEFONO         VARCHAR(50),
    EMAIL            VARCHAR(100),
    GRUPO_SANGUINEO  VARCHAR(5),
    DIRECCION        VARCHAR(300),
    CIUDAD           VARCHAR(100),
    CODIGO_POSTAL    VARCHAR(10),
    SEGURO_MEDICO    VARCHAR(200),
    TIPO_SEGURO      VARCHAR(50),
    FECHA_INICIO     DATE         NOT NULL,
    FECHA_FIN        DATE,
    ES_ACTUAL        BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_EQUIPO (
    SK_EQUIPO           NUMBER       NOT NULL AUTOINCREMENT PRIMARY KEY,
    ID_EQUIPO           NUMBER       NOT NULL,
    NOMBRE_EQUIPO       VARCHAR(200) NOT NULL,
    DESCRIPCION         VARCHAR(500),
    NUMERO_SERIE        VARCHAR(100) NOT NULL,
    MODELO              VARCHAR(200),
    FECHA_ADQUISICION   DATE,
    FECHA_FIN_GARANTIA  DATE,
    ESTADO_EQUIPO       VARCHAR(50)  NOT NULL,
    CLASE_RIESGO        VARCHAR(10)  NOT NULL,
    DEPARTAMENTO_ACTUAL VARCHAR(200),
    UBICACION_ACTUAL    VARCHAR(200),
    FECHA_INICIO        DATE         NOT NULL,
    FECHA_FIN           DATE,
    ES_ACTUAL           BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_ENSAYO (
    SK_ENSAYO           NUMBER       NOT NULL AUTOINCREMENT PRIMARY KEY,
    ID_ENSAYO           NUMBER       NOT NULL,
    CODIGO_ENSAYO       VARCHAR(50)  NOT NULL,
    NOMBRE_ENSAYO       VARCHAR(300) NOT NULL,
    DESCRIPCION         VARCHAR(500),
    PATROCINADOR        VARCHAR(200),
    FECHA_INICIO_ENSAYO DATE,
    FECHA_FIN_PREVISTA  DATE,
    ESTADO_ENSAYO       VARCHAR(50),
    OBJETIVO_PRINCIPAL  VARCHAR(500),
    MOLECULA_FARMACO    VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_DIAGNOSTICO (
    SK_DIAGNOSTICO          NUMBER       NOT NULL AUTOINCREMENT PRIMARY KEY,
    ID_DIAGNOSTICO          NUMBER       NOT NULL,
    CODIGO_CIE10            VARCHAR(10)  NOT NULL,
    DESCRIPCION_DIAGNOSTICO VARCHAR(500) NOT NULL,
    CATEGORIA               VARCHAR(200),
    SUBCATEGORIA            VARCHAR(200),
    ES_CRONICO              BOOLEAN
);

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_PERFIL_MANTENIMIENTO (
    SK_PERFIL_MANTENIMIENTO NUMBER      NOT NULL AUTOINCREMENT PRIMARY KEY,
    TIPO_MANTENIMIENTO      VARCHAR(50) NOT NULL,
    PRIORIDAD               VARCHAR(20) NOT NULL,
    GRAVEDAD                VARCHAR(20) NOT NULL,
    ES_GARANTIA             BOOLEAN     NOT NULL,
    REQUIERE_PARADA_EQUIPO  BOOLEAN     NOT NULL
);

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_PERFIL_ENSAYO (
    SK_PERFIL_ENSAYO    NUMBER      NOT NULL AUTOINCREMENT PRIMARY KEY,
    FASE_ENSAYO         VARCHAR(20) NOT NULL,
    TIPO_CIEGO          VARCHAR(30) NOT NULL,
    TIPO_ALEATORIZACION VARCHAR(30) NOT NULL,
    GRUPO_TRATAMIENTO   VARCHAR(30) NOT NULL,
    VIA_ADMINISTRACION  VARCHAR(30) NOT NULL
);


-- ============================================================
-- HECHOS
-- ============================================================

CREATE TABLE IF NOT EXISTS CONFORMED.FACT_MANTENIMIENTO_EQUIPOS (
    SK_MANTENIMIENTO           NUMBER    NOT NULL AUTOINCREMENT PRIMARY KEY,
    SK_FECHA                   NUMBER    NOT NULL,
    SK_EQUIPO                  NUMBER    NOT NULL,
    SK_TECNICO                 NUMBER    NOT NULL,
    SK_DEPARTAMENTO            NUMBER    NOT NULL,
    SK_UBICACION               NUMBER    NOT NULL,
    SK_FABRICANTE              NUMBER    NOT NULL,
    SK_PERFIL_MANTENIMIENTO    NUMBER    NOT NULL,
    ID_ORDEN                   NUMBER    NOT NULL,
    HORAS_TRABAJADAS           NUMBER(8,2),
    TARIFA_HORA                NUMBER(10,2),
    COSTO_REPUESTOS            NUMBER(12,2),
    COSTO_MANO_OBRA            NUMBER(12,2),
    COSTO_TOTAL                NUMBER(12,2),
    DURACION_HORAS             NUMBER(8,2),
    NUMERO_PIEZAS_REEMPLAZADAS NUMBER,
    INDICADOR_REINCIDENCIA     BOOLEAN   NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS CONFORMED.FACT_MONITORIZACION_PACIENTES (
    SK_MONITORIZACION           NUMBER    NOT NULL AUTOINCREMENT PRIMARY KEY,
    SK_FECHA                    NUMBER    NOT NULL,
    SK_PACIENTE                 NUMBER    NOT NULL,
    SK_MEDICO                   NUMBER    NOT NULL,
    SK_EQUIPO                   NUMBER    NOT NULL,
    SK_DEPARTAMENTO             NUMBER    NOT NULL,
    SK_UBICACION                NUMBER    NOT NULL,
    SK_DIAGNOSTICO              NUMBER    NOT NULL,
    ID_SESION                   NUMBER    NOT NULL,
    DURACION_MONITORIZACION_MIN NUMBER,
    FRECUENCIA_CARDIACA         NUMBER(6,2),
    PRESION_SISTOLICA           NUMBER(6,2),
    PRESION_DIASTOLICA          NUMBER(6,2),
    TEMPERATURA                 NUMBER(5,2),
    SATURACION_OXIGENO          NUMBER(5,2),
    NIVEL_GLUCOSA               NUMBER(8,2),
    ALERTA_GENERADA             BOOLEAN   NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS CONFORMED.FACT_ENSAYOS_CLINICOS (
    SK_ENSAYO_CLINICO             NUMBER    NOT NULL AUTOINCREMENT PRIMARY KEY,
    SK_FECHA                      NUMBER    NOT NULL,
    SK_FECHA_INICIO               NUMBER    NOT NULL,
    SK_FECHA_FIN                  NUMBER,
    SK_ENSAYO                     NUMBER    NOT NULL,
    SK_PACIENTE                   NUMBER    NOT NULL,
    SK_MEDICO                     NUMBER    NOT NULL,
    SK_DIAGNOSTICO                NUMBER    NOT NULL,
    SK_DEPARTAMENTO               NUMBER    NOT NULL,
    SK_PERFIL_ENSAYO              NUMBER    NOT NULL,
    ID_PARTICIPACION              NUMBER    NOT NULL,
    DOSIS_ADMINISTRADA            NUMBER(10,4),
    UNIDAD_DOSIS                  VARCHAR(10),
    NUMERO_EFECTOS_ADVERSOS       NUMBER,
    RESULTADO_MEDICION_PRINCIPAL  NUMBER(8,4),
    RESULTADO_MEDICION_SECUNDARIA NUMBER(8,4),
    NIVEL_EFICACIA                NUMBER(5,4)
);


-- ============================================================
-- SP_DEPLOY_CONFORMED
-- Crea streams, ejecuta la carga inicial desde CLEANSED y
-- construye el Task DAG para incrementales via SP_LOAD_*.
-- Los streams recien creados estan vacios (Snowflake no captura
-- datos previos), por eso la carga inicial lee CLEANSED directo.
-- ============================================================

CREATE OR REPLACE PROCEDURE CONFORMED.SP_DEPLOY_CONFORMED()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    -- -------------------------------------------------------
    -- Streams CONFORMED sobre tablas CLEANSED
    -- Deben crearse ANTES de los SP_LOAD_*, que los leen
    -- Las tablas CLEANSED ya existen (FASE 3 precede a FASE 4)
    -- -------------------------------------------------------
    EXECUTE IMMEDIATE 'CREATE STREAM IF NOT EXISTS CONFORMED.STREAM_DEPARTAMENTOS         ON TABLE CLEANSED.DEPARTAMENTOS';
    EXECUTE IMMEDIATE 'CREATE STREAM IF NOT EXISTS CONFORMED.STREAM_UBICACIONES           ON TABLE CLEANSED.UBICACIONES';
    EXECUTE IMMEDIATE 'CREATE STREAM IF NOT EXISTS CONFORMED.STREAM_FABRICANTES           ON TABLE CLEANSED.FABRICANTES';
    EXECUTE IMMEDIATE 'CREATE STREAM IF NOT EXISTS CONFORMED.STREAM_MEDICOS               ON TABLE CLEANSED.MEDICOS';
    EXECUTE IMMEDIATE 'CREATE STREAM IF NOT EXISTS CONFORMED.STREAM_TECNICOS              ON TABLE CLEANSED.TECNICOS';
    EXECUTE IMMEDIATE 'CREATE STREAM IF NOT EXISTS CONFORMED.STREAM_PACIENTES             ON TABLE CLEANSED.PACIENTES';
    EXECUTE IMMEDIATE 'CREATE STREAM IF NOT EXISTS CONFORMED.STREAM_EQUIPOS               ON TABLE CLEANSED.EQUIPOS';
    EXECUTE IMMEDIATE 'CREATE STREAM IF NOT EXISTS CONFORMED.STREAM_ENSAYOS_CLINICOS      ON TABLE CLEANSED.ENSAYOS_CLINICOS';
    EXECUTE IMMEDIATE 'CREATE STREAM IF NOT EXISTS CONFORMED.STREAM_DIAGNOSTICOS          ON TABLE CLEANSED.DIAGNOSTICOS_CIE10';
    EXECUTE IMMEDIATE 'CREATE STREAM IF NOT EXISTS CONFORMED.STREAM_ORDENES_MANTENIMIENTO ON TABLE CLEANSED.ORDENES_MANTENIMIENTO';
    EXECUTE IMMEDIATE 'CREATE STREAM IF NOT EXISTS CONFORMED.STREAM_MONITORIZACIONES      ON TABLE CLEANSED.MONITORIZACIONES';
    EXECUTE IMMEDIATE 'CREATE STREAM IF NOT EXISTS CONFORMED.STREAM_PARTICIPACION_ENSAYOS ON TABLE CLEANSED.PARTICIPACION_ENSAYOS';

    -- -------------------------------------------------------
    -- Carga inicial: lectura directa de CLEANSED
    -- Los streams recien creados no capturan datos previos;
    -- se leen las tablas CLEANSED directamente para poblar
    -- las dimensiones y hechos en la instalacion inicial.
    -- El Task DAG usara los SP_LOAD_* (via streams) para incrementales.
    -- -------------------------------------------------------

    -- DIM_FECHA (calculada, sin dependencia de CLEANSED)
    CALL CONFORMED.SP_LOAD_DIM_FECHA();

    -- DIM_DEPARTAMENTO (su logica de jerarquia ya lee CLEANSED directamente)
    CALL CONFORMED.SP_LOAD_DIM_DEPARTAMENTO();

    -- DIM_PERFIL_MANTENIMIENTO / DIM_PERFIL_ENSAYO (valores fijos, sin stream)
    CALL CONFORMED.SP_LOAD_DIM_PERFIL_MANTENIMIENTO();
    CALL CONFORMED.SP_LOAD_DIM_PERFIL_ENSAYO();

    -- DIM_UBICACION (SCD1, leer CLEANSED directamente)
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_UBICACIONES AS
    SELECT ID_UBICACION, EDIFICIO, PLANTA, ALA, SALA, TIPO_SALA, CAPACIDAD
    FROM CLEANSED.UBICACIONES;
    CALL CONFORMED.SP_MERGE_SCD1(
        'CONFORMED.DIM_UBICACION',
        'SELECT ID_UBICACION, EDIFICIO, PLANTA, ALA, SALA, TIPO_SALA, CAPACIDAD FROM CONFORMED._TMP_UBICACIONES',
        'ID_UBICACION',
        'EDIFICIO,PLANTA,ALA,SALA,TIPO_SALA,CAPACIDAD'
    );

    -- DIM_FABRICANTE (SCD1, leer CLEANSED directamente)
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_FABRICANTES AS
    SELECT ID_FABRICANTE, RAZON_SOCIAL AS NOMBRE_FABRICANTE,
           PAIS_ORIGEN, TELEFONO_CONTACTO, EMAIL_CONTACTO,
           SITIO_WEB, CERTIFICACION_ISO
    FROM CLEANSED.FABRICANTES;
    CALL CONFORMED.SP_MERGE_SCD1(
        'CONFORMED.DIM_FABRICANTE',
        'SELECT ID_FABRICANTE, NOMBRE_FABRICANTE, PAIS_ORIGEN,
                TELEFONO_CONTACTO, EMAIL_CONTACTO, SITIO_WEB, CERTIFICACION_ISO
         FROM CONFORMED._TMP_FABRICANTES',
        'ID_FABRICANTE',
        'NOMBRE_FABRICANTE,PAIS_ORIGEN,TELEFONO_CONTACTO,EMAIL_CONTACTO,SITIO_WEB,CERTIFICACION_ISO'
    );

    -- DIM_MEDICO (SCD1+SCD2, leer CLEANSED directamente con JOINs)
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_MEDICOS AS
    SELECT s.ID_MEDICO, s.NOMBRE,
           s.APELLIDO1 || ' ' || s.APELLIDO2 AS APELLIDOS,
           s.NUMERO_COLEGIADO, s.TELEFONO, s.EMAIL,
           COALESCE(esp.NOMBRE_ESPECIALIDAD, 'Sin especialidad') AS ESPECIALIDAD,
           dep.NOMBRE_DEPARTAMENTO AS DEPARTAMENTO
    FROM CLEANSED.MEDICOS s
    LEFT JOIN CLEANSED.ESPECIALIDADES esp ON esp.ID_ESPECIALIDAD     = s.ID_ESPECIALIDAD
    LEFT JOIN CLEANSED.DEPARTAMENTOS  dep ON dep.CODIGO_DEPARTAMENTO = s.CODIGO_DEPARTAMENTO;
    CALL CONFORMED.SP_MERGE_SCD1_SCD2(
        'CONFORMED.DIM_MEDICO',
        'SELECT ID_MEDICO, NOMBRE, APELLIDOS, NUMERO_COLEGIADO,
                TELEFONO, EMAIL, ESPECIALIDAD, DEPARTAMENTO
         FROM CONFORMED._TMP_MEDICOS',
        'ID_MEDICO',
        'NOMBRE,APELLIDOS,NUMERO_COLEGIADO,TELEFONO,EMAIL',
        'ESPECIALIDAD,DEPARTAMENTO'
    );

    -- DIM_TECNICO (SCD1+SCD2, leer CLEANSED directamente)
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_TECNICOS AS
    SELECT tc.ID_TECNICO,
           CASE WHEN ARRAY_SIZE(SPLIT(tc.NOMBRE_TECNICO, ' ')) = 4
                THEN SPLIT_PART(tc.NOMBRE_TECNICO, ' ', 1) || ' ' || SPLIT_PART(tc.NOMBRE_TECNICO, ' ', 2)
                ELSE SPLIT_PART(tc.NOMBRE_TECNICO, ' ', 1)
           END AS NOMBRE,
           CASE WHEN ARRAY_SIZE(SPLIT(tc.NOMBRE_TECNICO, ' ')) = 4
                THEN SPLIT_PART(tc.NOMBRE_TECNICO, ' ', 3) || ' ' || SPLIT_PART(tc.NOMBRE_TECNICO, ' ', 4)
                ELSE NULLIF(SUBSTR(tc.NOMBRE_TECNICO, LENGTH(SPLIT_PART(tc.NOMBRE_TECNICO, ' ', 1)) + 2), '')
           END AS APELLIDOS,
           tc.ESPECIALIDAD, tc.ANIOS_EXPERIENCIA,
           tc.TELEFONO_MOVIL AS TELEFONO, tc.EMAIL_CORPORATIVO AS EMAIL,
           dep.NOMBRE_DEPARTAMENTO AS DEPARTAMENTO,
           CASE tc.NIVEL_CERTIFICACION
               WHEN 1 THEN 'Junior'       WHEN 2 THEN 'Senior'
               WHEN 3 THEN 'Especialista' WHEN 4 THEN 'Jefe'
           END AS NIVEL_CERTIFICACION
    FROM CLEANSED.TECNICOS tc
    LEFT JOIN CLEANSED.DEPARTAMENTOS dep ON dep.ID_DEPARTAMENTO = tc.ID_DEPARTAMENTO;
    CALL CONFORMED.SP_MERGE_SCD1_SCD2(
        'CONFORMED.DIM_TECNICO',
        'SELECT ID_TECNICO, NOMBRE, APELLIDOS, ESPECIALIDAD, ANIOS_EXPERIENCIA,
                TELEFONO, EMAIL, DEPARTAMENTO, NIVEL_CERTIFICACION
         FROM CONFORMED._TMP_TECNICOS',
        'ID_TECNICO',
        'NOMBRE,APELLIDOS,ESPECIALIDAD,ANIOS_EXPERIENCIA,TELEFONO,EMAIL',
        'DEPARTAMENTO,NIVEL_CERTIFICACION'
    );

    -- DIM_PACIENTE (SCD1+SCD2, leer CLEANSED directamente)
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_PACIENTES AS
    SELECT ID_PACIENTE, NOMBRE,
           APELLIDO1 || ' ' || APELLIDO2 AS APELLIDOS,
           FECHA_NACIMIENTO, SEXO AS GENERO,
           TELEFONO_MOVIL AS TELEFONO, EMAIL, GRUPO_SANGUINEO,
           DIRECCION, CIUDAD, CODIGO_POSTAL,
           COMPANIA_SEGURO AS SEGURO_MEDICO,
           TIPO_COBERTURA  AS TIPO_SEGURO
    FROM CLEANSED.PACIENTES;
    CALL CONFORMED.SP_MERGE_SCD1_SCD2(
        'CONFORMED.DIM_PACIENTE',
        'SELECT ID_PACIENTE, NOMBRE, APELLIDOS, FECHA_NACIMIENTO, GENERO,
                TELEFONO, EMAIL, GRUPO_SANGUINEO,
                DIRECCION, CIUDAD, CODIGO_POSTAL, SEGURO_MEDICO, TIPO_SEGURO
         FROM CONFORMED._TMP_PACIENTES',
        'ID_PACIENTE',
        'NOMBRE,APELLIDOS,FECHA_NACIMIENTO,GENERO,TELEFONO,EMAIL,GRUPO_SANGUINEO',
        'DIRECCION,CIUDAD,CODIGO_POSTAL,SEGURO_MEDICO,TIPO_SEGURO'
    );

    -- DIM_EQUIPO (SCD1+SCD2, leer CLEANSED directamente con JOINs)
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_EQUIPOS AS
    SELECT e.ID_EQUIPO, e.NOMBRE_EQUIPO,
           CASE
               WHEN LEFT(e.DESCRIPCION, LENGTH(e.NOMBRE_EQUIPO) + 3) = e.NOMBRE_EQUIPO || ' - '
               THEN SUBSTR(e.DESCRIPCION, LENGTH(e.NOMBRE_EQUIPO) + 4)
               ELSE e.DESCRIPCION
           END AS DESCRIPCION,
           e.NUMERO_SERIE, e.MODELO, e.FECHA_ADQUISICION,
           e.FECHA_FIN_GARANTIA, e.CLASE_RIESGO,
           CASE e.ESTADO_CODIGO
               WHEN 1 THEN 'Activo'            WHEN 2 THEN 'En Reparacion'
               WHEN 3 THEN 'Fuera de Servicio' WHEN 4 THEN 'Baja'
           END                              AS ESTADO_EQUIPO,
           d.NOMBRE_DEPARTAMENTO            AS DEPARTAMENTO_ACTUAL,
           u.EDIFICIO || ' - ' || u.SALA   AS UBICACION_ACTUAL
    FROM CLEANSED.EQUIPOS e
    LEFT JOIN CLEANSED.DEPARTAMENTOS d ON e.ID_DEPARTAMENTO = d.ID_DEPARTAMENTO
    LEFT JOIN CLEANSED.UBICACIONES   u ON e.ID_UBICACION    = u.ID_UBICACION;
    CALL CONFORMED.SP_MERGE_SCD1_SCD2(
        'CONFORMED.DIM_EQUIPO',
        'SELECT ID_EQUIPO, NOMBRE_EQUIPO, DESCRIPCION, NUMERO_SERIE, MODELO,
                FECHA_ADQUISICION, FECHA_FIN_GARANTIA, CLASE_RIESGO,
                ESTADO_EQUIPO, DEPARTAMENTO_ACTUAL, UBICACION_ACTUAL
         FROM CONFORMED._TMP_EQUIPOS',
        'ID_EQUIPO',
        'NOMBRE_EQUIPO,DESCRIPCION,NUMERO_SERIE,MODELO,FECHA_ADQUISICION,FECHA_FIN_GARANTIA,CLASE_RIESGO',
        'ESTADO_EQUIPO,DEPARTAMENTO_ACTUAL,UBICACION_ACTUAL'
    );

    -- DIM_ENSAYO (SCD1, leer CLEANSED directamente)
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_ENSAYOS AS
    SELECT ID_ENSAYO, CODIGO_ENSAYO,
           TITULO_ENSAYO      AS NOMBRE_ENSAYO,
           DESCRIPCION_ENSAYO AS DESCRIPCION,
           PATROCINADOR, FECHA_INICIO AS FECHA_INICIO_ENSAYO,
           FECHA_FIN_PREVISTA, ESTADO_ENSAYO,
           OBJETIVO_PRINCIPAL, MOLECULA_FARMACO
    FROM CLEANSED.ENSAYOS_CLINICOS;
    CALL CONFORMED.SP_MERGE_SCD1(
        'CONFORMED.DIM_ENSAYO',
        'SELECT ID_ENSAYO, CODIGO_ENSAYO, NOMBRE_ENSAYO, DESCRIPCION,
                PATROCINADOR, FECHA_INICIO_ENSAYO, FECHA_FIN_PREVISTA,
                ESTADO_ENSAYO, OBJETIVO_PRINCIPAL, MOLECULA_FARMACO
         FROM CONFORMED._TMP_ENSAYOS',
        'ID_ENSAYO',
        'CODIGO_ENSAYO,NOMBRE_ENSAYO,DESCRIPCION,PATROCINADOR,FECHA_INICIO_ENSAYO,FECHA_FIN_PREVISTA,ESTADO_ENSAYO,OBJETIVO_PRINCIPAL,MOLECULA_FARMACO'
    );

    -- DIM_DIAGNOSTICO (SCD1, leer CLEANSED directamente)
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_DIAGNOSTICOS AS
    SELECT ID_DIAGNOSTICO, CODIGO_CIE10,
           DESCRIPCION AS DESCRIPCION_DIAGNOSTICO,
           CAPITULO    AS CATEGORIA,
           GRUPO       AS SUBCATEGORIA,
           ES_CRONICO
    FROM CLEANSED.DIAGNOSTICOS_CIE10;
    CALL CONFORMED.SP_MERGE_SCD1(
        'CONFORMED.DIM_DIAGNOSTICO',
        'SELECT ID_DIAGNOSTICO, CODIGO_CIE10, DESCRIPCION_DIAGNOSTICO,
                CATEGORIA, SUBCATEGORIA, ES_CRONICO
         FROM CONFORMED._TMP_DIAGNOSTICOS',
        'ID_DIAGNOSTICO',
        'CODIGO_CIE10,DESCRIPCION_DIAGNOSTICO,CATEGORIA,SUBCATEGORIA,ES_CRONICO'
    );

    -- FACT_MANTENIMIENTO_EQUIPOS (leer CLEANSED directamente, sin filtro de stream)
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_ORDENES AS
    SELECT * FROM CLEANSED.ORDENES_MANTENIMIENTO;
    INSERT INTO CONFORMED.FACT_MANTENIMIENTO_EQUIPOS (
        SK_FECHA, SK_EQUIPO, SK_TECNICO, SK_DEPARTAMENTO, SK_UBICACION,
        SK_FABRICANTE, SK_PERFIL_MANTENIMIENTO, ID_ORDEN,
        HORAS_TRABAJADAS, TARIFA_HORA, COSTO_REPUESTOS,
        COSTO_MANO_OBRA, COSTO_TOTAL,
        DURACION_HORAS, NUMERO_PIEZAS_REEMPLAZADAS, INDICADOR_REINCIDENCIA
    )
    SELECT
        TO_NUMBER(TO_CHAR(CAST(o.FECHA_INICIO_TRABAJO AS DATE), 'YYYYMMDD')) AS SK_FECHA,
        eq.SK_EQUIPO,
        tc.SK_TECNICO,
        dp.SK_DEPARTAMENTO,
        ub.SK_UBICACION,
        fa.SK_FABRICANTE,
        pm.SK_PERFIL_MANTENIMIENTO,
        o.ID_ORDEN,
        o.HORAS_TRABAJADAS,
        tc_src.TARIFA_HORA,
        cr.COSTO_REPUESTOS,
        o.HORAS_TRABAJADAS * tc_src.TARIFA_HORA                                AS COSTO_MANO_OBRA,
        COALESCE(cr.COSTO_REPUESTOS, 0) + (o.HORAS_TRABAJADAS * tc_src.TARIFA_HORA) AS COSTO_TOTAL,
        DATEDIFF(MINUTE, o.FECHA_INICIO_TRABAJO, o.FECHA_FIN_TRABAJO) / 60.0  AS DURACION_HORAS,
        cr.NUMERO_PIEZAS_REEMPLAZADAS,
        CASE WHEN EXISTS (
            SELECT ID_ORDEN FROM CLEANSED.ORDENES_MANTENIMIENTO prev
            WHERE prev.ID_EQUIPO          = o.ID_EQUIPO
              AND prev.TIPO_MANTENIMIENTO = 'Correctivo'
              AND prev.FECHA_INICIO_TRABAJO  < o.FECHA_INICIO_TRABAJO
              AND prev.FECHA_INICIO_TRABAJO >= DATEADD(DAY, -30, o.FECHA_INICIO_TRABAJO)
        ) THEN TRUE ELSE FALSE END AS INDICADOR_REINCIDENCIA
    FROM CONFORMED._TMP_ORDENES o
    JOIN CLEANSED.EQUIPOS               eq_src ON eq_src.ID_EQUIPO  = o.ID_EQUIPO
    JOIN CLEANSED.TECNICOS              tc_src ON tc_src.ID_TECNICO = o.ID_TECNICO
    LEFT JOIN (
        SELECT ID_ORDEN,
               SUM(CANTIDAD * PRECIO_UNITARIO_EN_MOMENTO) AS COSTO_REPUESTOS,
               SUM(CANTIDAD)                              AS NUMERO_PIEZAS_REEMPLAZADAS
        FROM CLEANSED.CONSUMO_REPUESTOS
        GROUP BY ID_ORDEN
    ) cr ON cr.ID_ORDEN = o.ID_ORDEN
    JOIN CONFORMED.DIM_EQUIPO               eq ON eq.ID_EQUIPO      = o.ID_EQUIPO        AND eq.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_TECNICO              tc ON tc.ID_TECNICO      = o.ID_TECNICO       AND tc.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_DEPARTAMENTO         dp ON dp.ID_DEPARTAMENTO = eq_src.ID_DEPARTAMENTO
    JOIN CONFORMED.DIM_UBICACION            ub ON ub.ID_UBICACION    = eq_src.ID_UBICACION
    JOIN CONFORMED.DIM_FABRICANTE           fa ON fa.ID_FABRICANTE   = eq_src.ID_FABRICANTE
    JOIN CONFORMED.DIM_PERFIL_MANTENIMIENTO pm
        ON  pm.TIPO_MANTENIMIENTO = CASE o.TIPO_MANTENIMIENTO
                                        WHEN 'PREV' THEN 'Preventivo'
                                        WHEN 'CORR' THEN 'Correctivo'
                                        WHEN 'CAL'  THEN 'Calibracion'
                                        WHEN 'INSP' THEN 'Inspeccion' END
        AND pm.PRIORIDAD = CASE o.PRIORIDAD
                               WHEN 1 THEN 'Baja' WHEN 2 THEN 'Media'
                               WHEN 3 THEN 'Alta' WHEN 4 THEN 'Critica' END
        AND pm.GRAVEDAD  = CASE o.GRAVEDAD
                               WHEN 1 THEN 'Leve' WHEN 2 THEN 'Moderada' WHEN 3 THEN 'Grave' END
        AND pm.ES_GARANTIA            = o.ES_CUBIERTO_POR_GARANTIA
        AND pm.REQUIERE_PARADA_EQUIPO = o.REQUIERE_PARADA
    WHERE NOT EXISTS (
        SELECT ID_ORDEN FROM CONFORMED.FACT_MANTENIMIENTO_EQUIPOS
        WHERE  ID_ORDEN = o.ID_ORDEN
    );

    -- FACT_MONITORIZACION_PACIENTES (leer CLEANSED directamente, sin filtro de stream)
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_MONITORIZACIONES AS
    SELECT * FROM CLEANSED.MONITORIZACIONES;
    INSERT INTO CONFORMED.FACT_MONITORIZACION_PACIENTES (
        SK_FECHA, SK_PACIENTE, SK_MEDICO, SK_EQUIPO,
        SK_DEPARTAMENTO, SK_UBICACION, SK_DIAGNOSTICO, ID_SESION,
        DURACION_MONITORIZACION_MIN,
        FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA,
        TEMPERATURA, SATURACION_OXIGENO, NIVEL_GLUCOSA, ALERTA_GENERADA
    )
    SELECT
        TO_NUMBER(TO_CHAR(m.FECHA_MONITORIZACION, 'YYYYMMDD')) AS SK_FECHA,
        pa.SK_PACIENTE, me.SK_MEDICO, eq.SK_EQUIPO,
        dp.SK_DEPARTAMENTO, ub.SK_UBICACION, di.SK_DIAGNOSTICO,
        m.ID_MONITORIZACION                                    AS ID_SESION,
        DATEDIFF(MINUTE, m.HORA_INICIO, m.HORA_FIN)           AS DURACION_MONITORIZACION_MIN,
        lsv.FRECUENCIA_CARDIACA, lsv.PRESION_SISTOLICA, lsv.PRESION_DIASTOLICA,
        lsv.TEMPERATURA, lsv.SATURACION_OXIGENO, lsv.NIVEL_GLUCOSA,
        CASE WHEN
            lsv.FRECUENCIA_CARDIACA < 60   OR lsv.FRECUENCIA_CARDIACA > 100  OR
            lsv.PRESION_SISTOLICA   < 90   OR lsv.PRESION_SISTOLICA   > 140  OR
            lsv.PRESION_DIASTOLICA  < 60   OR lsv.PRESION_DIASTOLICA  > 90   OR
            lsv.TEMPERATURA         < 36.0 OR lsv.TEMPERATURA         > 37.5 OR
            lsv.SATURACION_OXIGENO  < 95                                      OR
            lsv.NIVEL_GLUCOSA       < 70   OR lsv.NIVEL_GLUCOSA       > 140
        THEN TRUE ELSE FALSE END                               AS ALERTA_GENERADA
    FROM CONFORMED._TMP_MONITORIZACIONES m
    JOIN (
        SELECT ID_MONITORIZACION,
               AVG(FRECUENCIA_CARDIACA) AS FRECUENCIA_CARDIACA,
               AVG(PRESION_SISTOLICA)   AS PRESION_SISTOLICA,
               AVG(PRESION_DIASTOLICA)  AS PRESION_DIASTOLICA,
               AVG(TEMPERATURA)         AS TEMPERATURA,
               AVG(SATURACION_OXIGENO)  AS SATURACION_OXIGENO,
               AVG(NIVEL_GLUCOSA)       AS NIVEL_GLUCOSA
        FROM CLEANSED.LECTURAS_SIGNOS_VITALES
        GROUP BY ID_MONITORIZACION
    ) lsv ON lsv.ID_MONITORIZACION = m.ID_MONITORIZACION
    JOIN CLEANSED.EQUIPOS       eq_src ON eq_src.CODIGO_EQUIPO        = m.CODIGO_EQUIPO
    JOIN CLEANSED.DEPARTAMENTOS dp_src ON dp_src.CODIGO_DEPARTAMENTO  = m.CODIGO_DEPARTAMENTO
    JOIN CLEANSED.UBICACIONES   ub_src ON ub_src.CODIGO_UBICACION     = m.CODIGO_UBICACION
    JOIN CONFORMED.DIM_PACIENTE     pa ON pa.ID_PACIENTE     = m.ID_PACIENTE          AND pa.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_MEDICO       me ON me.ID_MEDICO       = m.ID_MEDICO            AND me.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_EQUIPO       eq ON eq.ID_EQUIPO       = eq_src.ID_EQUIPO       AND eq.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_DEPARTAMENTO dp ON dp.ID_DEPARTAMENTO = dp_src.ID_DEPARTAMENTO
    JOIN CONFORMED.DIM_UBICACION    ub ON ub.ID_UBICACION    = ub_src.ID_UBICACION
    JOIN CONFORMED.DIM_DIAGNOSTICO  di ON di.ID_DIAGNOSTICO  = m.ID_DIAGNOSTICO
    WHERE NOT EXISTS (
        SELECT ID_SESION FROM CONFORMED.FACT_MONITORIZACION_PACIENTES
        WHERE  ID_SESION = m.ID_MONITORIZACION
    );

    -- FACT_ENSAYOS_CLINICOS: 1 fila por paciente/ensayo/dia
    -- Expande cada participacion al rango FECHA_INICIO_PARTICIPACION → FECHA_FIN_PARTICIPACION.
    -- LEFT JOIN a VISITAS_ENSAYO para incluir metricas de la visita de ese dia (NULL si no hay visita).
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_PARTICIPACIONES AS
    SELECT * FROM CLEANSED.PARTICIPACION_ENSAYOS;

    INSERT INTO CONFORMED.FACT_ENSAYOS_CLINICOS (
        SK_FECHA, SK_FECHA_INICIO, SK_FECHA_FIN,
        SK_ENSAYO, SK_PACIENTE, SK_MEDICO, SK_DIAGNOSTICO,
        SK_DEPARTAMENTO, SK_PERFIL_ENSAYO, ID_PARTICIPACION,
        DOSIS_ADMINISTRADA, UNIDAD_DOSIS, NUMERO_EFECTOS_ADVERSOS,
        RESULTADO_MEDICION_PRINCIPAL, RESULTADO_MEDICION_SECUNDARIA, NIVEL_EFICACIA
    )
    SELECT
        TO_NUMBER(TO_CHAR(DATEADD('day', dias.n, p.FECHA_INICIO_PARTICIPACION), 'YYYYMMDD')) AS SK_FECHA,
        TO_NUMBER(TO_CHAR(p.FECHA_INICIO_PARTICIPACION, 'YYYYMMDD'))                         AS SK_FECHA_INICIO,
        TO_NUMBER(TO_CHAR(p.FECHA_FIN_PARTICIPACION,    'YYYYMMDD'))                         AS SK_FECHA_FIN,
        en.SK_ENSAYO, pa.SK_PACIENTE, me.SK_MEDICO, di.SK_DIAGNOSTICO,
        dp.SK_DEPARTAMENTO, pe.SK_PERFIL_ENSAYO,
        p.ID_PARTICIPACION,
        v.DOSIS_ADMINISTRADA, v.UNIDAD_DOSIS,
        v.NUMERO_EFECTOS_ADVERSOS, v.RESULTADO_MEDICION_PRINCIPAL,
        v.RESULTADO_MEDICION_SECUNDARIA, v.NIVEL_EFICACIA
    FROM CONFORMED._TMP_PARTICIPACIONES p
    JOIN (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 AS n
          FROM TABLE(GENERATOR(ROWCOUNT => 3650))) dias
    JOIN CLEANSED.ENSAYOS_CLINICOS       ec      ON ec.ID_ENSAYO               = p.ID_ENSAYO
    JOIN CLEANSED.DEPARTAMENTOS         dep_src ON dep_src.CODIGO_DEPARTAMENTO = ec.CODIGO_DEPARTAMENTO
    JOIN CONFORMED.DIM_ENSAYO        en ON en.ID_ENSAYO        = p.ID_ENSAYO
    JOIN CONFORMED.DIM_PACIENTE      pa ON pa.ID_PACIENTE       = p.ID_PACIENTE          AND pa.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_MEDICO        me ON me.ID_MEDICO         = p.ID_MEDICO_ASIGNADO   AND me.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_DIAGNOSTICO   di ON di.ID_DIAGNOSTICO    = p.ID_DIAGNOSTICO
    JOIN CONFORMED.DIM_DEPARTAMENTO  dp ON dp.ID_DEPARTAMENTO   = dep_src.ID_DEPARTAMENTO
    JOIN CONFORMED.DIM_PERFIL_ENSAYO pe
        ON  pe.FASE_ENSAYO         = CASE p.FASE
                                         WHEN 'F1' THEN 'Fase I'   WHEN 'F2' THEN 'Fase II'
                                         WHEN 'F3' THEN 'Fase III' WHEN 'F4' THEN 'Fase IV' END
        AND pe.TIPO_CIEGO          = CASE p.TIPO_CIEGO
                                         WHEN 'AB' THEN 'Abierto'
                                         WHEN 'SC' THEN 'Simple Ciego'
                                         WHEN 'DC' THEN 'Doble Ciego' END
        AND pe.TIPO_ALEATORIZACION = CASE p.TIPO_ALEATORIZACION
                                         WHEN 'AL' THEN 'Aleatorizado'
                                         WHEN 'NA' THEN 'No Aleatorizado' END
        AND pe.GRUPO_TRATAMIENTO   = CASE p.GRUPO_ASIGNADO
                                         WHEN 'EXP' THEN 'Experimental'
                                         WHEN 'CTR' THEN 'Control'
                                         WHEN 'PLA' THEN 'Placebo' END
        AND pe.VIA_ADMINISTRACION  = CASE p.VIA_ADMINISTRACION
                                         WHEN 'ORL' THEN 'Oral'
                                         WHEN 'IV'  THEN 'Intravenosa'
                                         WHEN 'SC'  THEN 'Subcutanea'
                                         WHEN 'TOP' THEN 'Topica'
                                         WHEN 'INH' THEN 'Inhalatoria' END
    LEFT JOIN CLEANSED.VISITAS_ENSAYO v
           ON v.ID_PARTICIPACION = p.ID_PARTICIPACION
          AND CAST(v.FECHA_VISITA AS DATE) = DATEADD('day', dias.n, p.FECHA_INICIO_PARTICIPACION)
    WHERE DATEADD('day', dias.n, p.FECHA_INICIO_PARTICIPACION)
              <= COALESCE(p.FECHA_FIN_PARTICIPACION, CURRENT_DATE)
      AND NOT EXISTS (
              SELECT 1 FROM CONFORMED.FACT_ENSAYOS_CLINICOS
              WHERE  ID_PARTICIPACION = p.ID_PARTICIPACION
                AND  SK_FECHA = TO_NUMBER(TO_CHAR(DATEADD('day', dias.n, p.FECHA_INICIO_PARTICIPACION), 'YYYYMMDD'))
          );

    -- -------------------------------------------------------
    -- Task DAG CONFORMED
    -- ROOT (5 MINUTE) → dimensiones en paralelo → hechos en paralelo
    -- Los streams ya existen (creados arriba), los SP_LOAD_* ya
    -- existen (definidos en sp_load_conformed.sql, FASE 0)
    
    --El Task DAG llama a los SP_LOAD_*, 
    --que leen de esos streams → eso es exactamente "coger los datos del stream de CLEANSED
    -- -------------------------------------------------------
    EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK CONFORMED.TASK_CONFORMED_ROOT
        WAREHOUSE = COMPUTE_WH
        SCHEDULE  = ''5 MINUTE''
    AS
        SELECT ''Inicio carga CONFORMED''';

    -- Sin WHEN: siempre se ejecutan con ROOT
    EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK CONFORMED.TASK_DIM_FECHA
        WAREHOUSE = COMPUTE_WH
        AFTER CONFORMED.TASK_CONFORMED_ROOT
    AS
        CALL CONFORMED.SP_LOAD_DIM_FECHA()';

    EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK CONFORMED.TASK_DIM_PERFIL_MANTENIMIENTO
        WAREHOUSE = COMPUTE_WH
        AFTER CONFORMED.TASK_CONFORMED_ROOT
    AS
        CALL CONFORMED.SP_LOAD_DIM_PERFIL_MANTENIMIENTO()';

    EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK CONFORMED.TASK_DIM_PERFIL_ENSAYO
        WAREHOUSE = COMPUTE_WH
        AFTER CONFORMED.TASK_CONFORMED_ROOT
    AS
        CALL CONFORMED.SP_LOAD_DIM_PERFIL_ENSAYO()';

    -- Con WHEN: solo si el stream tiene datos nuevos
    EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK CONFORMED.TASK_DIM_DEPARTAMENTO
        WAREHOUSE = COMPUTE_WH
        AFTER CONFORMED.TASK_CONFORMED_ROOT
        WHEN SYSTEM$STREAM_HAS_DATA(''CONFORMED.STREAM_DEPARTAMENTOS'')
    AS
        CALL CONFORMED.SP_LOAD_DIM_DEPARTAMENTO()';

    EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK CONFORMED.TASK_DIM_UBICACION
        WAREHOUSE = COMPUTE_WH
        AFTER CONFORMED.TASK_CONFORMED_ROOT
        WHEN SYSTEM$STREAM_HAS_DATA(''CONFORMED.STREAM_UBICACIONES'')
    AS
        CALL CONFORMED.SP_LOAD_DIM_UBICACION()';

    EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK CONFORMED.TASK_DIM_FABRICANTE
        WAREHOUSE = COMPUTE_WH
        AFTER CONFORMED.TASK_CONFORMED_ROOT
        WHEN SYSTEM$STREAM_HAS_DATA(''CONFORMED.STREAM_FABRICANTES'')
    AS
        CALL CONFORMED.SP_LOAD_DIM_FABRICANTE()';

    EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK CONFORMED.TASK_DIM_MEDICO
        WAREHOUSE = COMPUTE_WH
        AFTER CONFORMED.TASK_CONFORMED_ROOT
        WHEN SYSTEM$STREAM_HAS_DATA(''CONFORMED.STREAM_MEDICOS'')
    AS
        CALL CONFORMED.SP_LOAD_DIM_MEDICO()';

    EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK CONFORMED.TASK_DIM_TECNICO
        WAREHOUSE = COMPUTE_WH
        AFTER CONFORMED.TASK_CONFORMED_ROOT
        WHEN SYSTEM$STREAM_HAS_DATA(''CONFORMED.STREAM_TECNICOS'')
    AS
        CALL CONFORMED.SP_LOAD_DIM_TECNICO()';

    EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK CONFORMED.TASK_DIM_PACIENTE
        WAREHOUSE = COMPUTE_WH
        AFTER CONFORMED.TASK_CONFORMED_ROOT
        WHEN SYSTEM$STREAM_HAS_DATA(''CONFORMED.STREAM_PACIENTES'')
    AS
        CALL CONFORMED.SP_LOAD_DIM_PACIENTE()';

    EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK CONFORMED.TASK_DIM_EQUIPO
        WAREHOUSE = COMPUTE_WH
        AFTER CONFORMED.TASK_CONFORMED_ROOT
        WHEN SYSTEM$STREAM_HAS_DATA(''CONFORMED.STREAM_EQUIPOS'')
    AS
        CALL CONFORMED.SP_LOAD_DIM_EQUIPO()';

    EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK CONFORMED.TASK_DIM_ENSAYO
        WAREHOUSE = COMPUTE_WH
        AFTER CONFORMED.TASK_CONFORMED_ROOT
        WHEN SYSTEM$STREAM_HAS_DATA(''CONFORMED.STREAM_ENSAYOS_CLINICOS'')
    AS
        CALL CONFORMED.SP_LOAD_DIM_ENSAYO()';

    EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK CONFORMED.TASK_DIM_DIAGNOSTICO
        WAREHOUSE = COMPUTE_WH
        AFTER CONFORMED.TASK_CONFORMED_ROOT
        WHEN SYSTEM$STREAM_HAS_DATA(''CONFORMED.STREAM_DIAGNOSTICOS'')
    AS
        CALL CONFORMED.SP_LOAD_DIM_DIAGNOSTICO()';

    -- Hechos: esperan a todas las dimensiones
    EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK CONFORMED.TASK_FACT_MANTENIMIENTO_EQUIPOS
        WAREHOUSE = COMPUTE_WH
        AFTER CONFORMED.TASK_DIM_FECHA,
              CONFORMED.TASK_DIM_DEPARTAMENTO, CONFORMED.TASK_DIM_UBICACION,
              CONFORMED.TASK_DIM_FABRICANTE,   CONFORMED.TASK_DIM_MEDICO,
              CONFORMED.TASK_DIM_TECNICO,      CONFORMED.TASK_DIM_PACIENTE,
              CONFORMED.TASK_DIM_EQUIPO,       CONFORMED.TASK_DIM_ENSAYO,
              CONFORMED.TASK_DIM_DIAGNOSTICO,  CONFORMED.TASK_DIM_PERFIL_MANTENIMIENTO,
              CONFORMED.TASK_DIM_PERFIL_ENSAYO
        WHEN SYSTEM$STREAM_HAS_DATA(''CONFORMED.STREAM_ORDENES_MANTENIMIENTO'')
    AS
        CALL CONFORMED.SP_LOAD_FACT_MANTENIMIENTO_EQUIPOS()';

    EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK CONFORMED.TASK_FACT_MONITORIZACION_PACIENTES
        WAREHOUSE = COMPUTE_WH
        AFTER CONFORMED.TASK_DIM_FECHA,
              CONFORMED.TASK_DIM_DEPARTAMENTO, CONFORMED.TASK_DIM_UBICACION,
              CONFORMED.TASK_DIM_FABRICANTE,   CONFORMED.TASK_DIM_MEDICO,
              CONFORMED.TASK_DIM_TECNICO,      CONFORMED.TASK_DIM_PACIENTE,
              CONFORMED.TASK_DIM_EQUIPO,       CONFORMED.TASK_DIM_ENSAYO,
              CONFORMED.TASK_DIM_DIAGNOSTICO,  CONFORMED.TASK_DIM_PERFIL_MANTENIMIENTO,
              CONFORMED.TASK_DIM_PERFIL_ENSAYO
        WHEN SYSTEM$STREAM_HAS_DATA(''CONFORMED.STREAM_MONITORIZACIONES'')
    AS
        CALL CONFORMED.SP_LOAD_FACT_MONITORIZACION_PACIENTES()';

    EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK CONFORMED.TASK_FACT_ENSAYOS_CLINICOS
        WAREHOUSE = COMPUTE_WH
        AFTER CONFORMED.TASK_DIM_FECHA,
              CONFORMED.TASK_DIM_DEPARTAMENTO, CONFORMED.TASK_DIM_UBICACION,
              CONFORMED.TASK_DIM_FABRICANTE,   CONFORMED.TASK_DIM_MEDICO,
              CONFORMED.TASK_DIM_TECNICO,      CONFORMED.TASK_DIM_PACIENTE,
              CONFORMED.TASK_DIM_EQUIPO,       CONFORMED.TASK_DIM_ENSAYO,
              CONFORMED.TASK_DIM_DIAGNOSTICO,  CONFORMED.TASK_DIM_PERFIL_MANTENIMIENTO,
              CONFORMED.TASK_DIM_PERFIL_ENSAYO
        WHEN SYSTEM$STREAM_HAS_DATA(''CONFORMED.STREAM_PARTICIPACION_ENSAYOS'')
    AS
        CALL CONFORMED.SP_LOAD_FACT_ENSAYOS_CLINICOS()';

    -- Tasks creados como SUSPENDED por defecto en Snowflake.
    -- Usar opcion [A] del menu principal para activarlos cuando se necesite carga incremental.

    RETURN 'SP_DEPLOY_CONFORMED completado correctamente.';
END;
$$;

-- Orden de ejecucion completo:
--   1. CALL RAW.SP_DEPLOY_RAW()
--   2. CALL CLEANSED.SP_DEPLOY_CLEANSED()
--   3. CALL CONFORMED.SP_DEPLOY_CONFORMED()


