-- sp_load_conformed.sql
-- Define los SP_LOAD_* de cada dimension y hecho de la capa CONFORMED.
-- Estos SPs son llamados tanto por SP_DEPLOY_CONFORMED (carga inicial) como por el Task DAG (incrementales).
--El Task DAG llama a los SP_LOAD_*, que leen de esos streams → eso es exactamente "coger los datos del stream de CLEANSED
CREATE SCHEMA IF NOT EXISTS CONFORMED;


-- ============================================================
-- STORED PROCEDURES — DIMENSIONES
-- ============================================================

-- DIM_FECHA: sin stream (generada por calculo)
CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_FECHA()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CREATE OR REPLACE TABLE CONFORMED.DIM_FECHA AS
    WITH SERIE AS (
        SELECT DATEADD(DAY, SEQ4(), '2015-01-01'::DATE) AS FECHA
        FROM TABLE(GENERATOR(ROWCOUNT => 5844))
    )
    SELECT
        TO_NUMBER(TO_CHAR(FECHA, 'YYYYMMDD'))                   AS SK_FECHA,
        FECHA                                                   AS FECHA,
        YEAR(FECHA)                                             AS ANIO,
        CASE WHEN MONTH(FECHA) <= 6 THEN 1 ELSE 2 END          AS SEMESTRE,
        QUARTER(FECHA)                                          AS TRIMESTRE,
        MONTH(FECHA)                                            AS MES,
        CASE MONTH(FECHA)
            WHEN 1  THEN 'Enero'        WHEN 2  THEN 'Febrero'
            WHEN 3  THEN 'Marzo'        WHEN 4  THEN 'Abril'
            WHEN 5  THEN 'Mayo'         WHEN 6  THEN 'Junio'
            WHEN 7  THEN 'Julio'        WHEN 8  THEN 'Agosto'
            WHEN 9  THEN 'Septiembre'   WHEN 10 THEN 'Octubre'
            WHEN 11 THEN 'Noviembre'    WHEN 12 THEN 'Diciembre'
        END                                                     AS NOMBRE_MES,
        WEEKISO(FECHA)                                          AS SEMANA_ANIO,
        DAY(FECHA)                                              AS DIA,
        DAYOFWEEKISO(FECHA)                                     AS DIA_SEMANA,
        CASE DAYOFWEEKISO(FECHA)
            WHEN 1 THEN 'Lunes'         WHEN 2 THEN 'Martes'
            WHEN 3 THEN 'Miercoles'     WHEN 4 THEN 'Jueves'
            WHEN 5 THEN 'Viernes'       WHEN 6 THEN 'Sabado'
            WHEN 7 THEN 'Domingo'
        END                                                     AS NOMBRE_DIA,
        DAYOFWEEKISO(FECHA) IN (6, 7)                          AS ES_FIN_SEMANA,
        FALSE                                                   AS ES_FESTIVO
    FROM SERIE;

    ALTER TABLE CONFORMED.DIM_FECHA
        ADD CONSTRAINT PK_DIM_FECHA PRIMARY KEY (SK_FECHA);

    RETURN 'DIM_FECHA OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_DEPARTAMENTO()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    -- Materializar stream para consumir el offset
    -- La jerarquia requiere CTE recursiva sobre la tabla completa (no compatible con stream)
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_DEPT_CAMBIOS AS
    SELECT * FROM CONFORMED.STREAM_DEPARTAMENTOS WHERE METADATA$ACTION = 'INSERT';

    -- Reconstruir jerarquia completa desde CLEANSED (necesario por la recursion)
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_JERARQUIA AS
    WITH JERARQUIA AS (
        SELECT ID_DEPARTAMENTO, ID_DEPARTAMENTO_PADRE, 1 AS NIVEL_JERARQUIA
        FROM CLEANSED.DEPARTAMENTOS
        WHERE ID_DEPARTAMENTO_PADRE IS NULL
        UNION ALL
        SELECT d.ID_DEPARTAMENTO, d.ID_DEPARTAMENTO_PADRE, j.NIVEL_JERARQUIA + 1
        FROM CLEANSED.DEPARTAMENTOS d
        JOIN JERARQUIA j ON j.ID_DEPARTAMENTO = d.ID_DEPARTAMENTO_PADRE
    )
    SELECT ID_DEPARTAMENTO, ID_DEPARTAMENTO_PADRE, NIVEL_JERARQUIA FROM JERARQUIA;

    UPDATE CONFORMED.DIM_DEPARTAMENTO t
    SET
        NOMBRE_DEPARTAMENTO   = s.NOMBRE_DEPARTAMENTO,
        ID_DEPARTAMENTO_PADRE = s.ID_DEPARTAMENTO_PADRE,
        SK_DEPARTAMENTO_PADRE = (
            SELECT SK_DEPARTAMENTO FROM CONFORMED.DIM_DEPARTAMENTO
            WHERE  ID_DEPARTAMENTO = s.ID_DEPARTAMENTO_PADRE
        ),
        NIVEL_JERARQUIA       = s.NIVEL_JERARQUIA,
        RESPONSABLE           = s.RESPONSABLE,
        TELEFONO_DEPARTAMENTO = s.TELEFONO_DEPARTAMENTO,
        EMAIL_DEPARTAMENTO    = s.EMAIL_DEPARTAMENTO
    FROM (
        SELECT d.ID_DEPARTAMENTO, d.NOMBRE_DEPARTAMENTO, d.ID_DEPARTAMENTO_PADRE,
               j.NIVEL_JERARQUIA, d.NOMBRE_RESPONSABLE AS RESPONSABLE,
               d.TELEFONO_DEPARTAMENTO, d.EMAIL_DEPARTAMENTO
        FROM CLEANSED.DEPARTAMENTOS d
        JOIN CONFORMED._TMP_JERARQUIA j ON j.ID_DEPARTAMENTO = d.ID_DEPARTAMENTO
    ) s
    WHERE t.ID_DEPARTAMENTO = s.ID_DEPARTAMENTO
      AND (t.NOMBRE_DEPARTAMENTO   IS DISTINCT FROM s.NOMBRE_DEPARTAMENTO   OR
           t.ID_DEPARTAMENTO_PADRE IS DISTINCT FROM s.ID_DEPARTAMENTO_PADRE OR
           t.NIVEL_JERARQUIA       IS DISTINCT FROM s.NIVEL_JERARQUIA       OR
           t.RESPONSABLE           IS DISTINCT FROM s.RESPONSABLE           OR
           t.TELEFONO_DEPARTAMENTO IS DISTINCT FROM s.TELEFONO_DEPARTAMENTO OR
           t.EMAIL_DEPARTAMENTO    IS DISTINCT FROM s.EMAIL_DEPARTAMENTO);

    INSERT INTO CONFORMED.DIM_DEPARTAMENTO (
        ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ID_DEPARTAMENTO_PADRE,
        SK_DEPARTAMENTO_PADRE, NIVEL_JERARQUIA, RESPONSABLE,
        TELEFONO_DEPARTAMENTO, EMAIL_DEPARTAMENTO
    )
    SELECT d.ID_DEPARTAMENTO, d.NOMBRE_DEPARTAMENTO, d.ID_DEPARTAMENTO_PADRE,
           (SELECT SK_DEPARTAMENTO FROM CONFORMED.DIM_DEPARTAMENTO
            WHERE  ID_DEPARTAMENTO = d.ID_DEPARTAMENTO_PADRE),
           j.NIVEL_JERARQUIA, d.NOMBRE_RESPONSABLE AS RESPONSABLE,
           d.TELEFONO_DEPARTAMENTO, d.EMAIL_DEPARTAMENTO
    FROM CLEANSED.DEPARTAMENTOS d
    JOIN CONFORMED._TMP_JERARQUIA j ON j.ID_DEPARTAMENTO = d.ID_DEPARTAMENTO
    WHERE NOT EXISTS (
        SELECT ID_DEPARTAMENTO FROM CONFORMED.DIM_DEPARTAMENTO
        WHERE  ID_DEPARTAMENTO = d.ID_DEPARTAMENTO
    );

    UPDATE CONFORMED.DIM_DEPARTAMENTO t
    SET    SK_DEPARTAMENTO_PADRE = p.SK_DEPARTAMENTO
    FROM   CONFORMED.DIM_DEPARTAMENTO p
    WHERE  t.ID_DEPARTAMENTO_PADRE = p.ID_DEPARTAMENTO
      AND  t.SK_DEPARTAMENTO_PADRE IS NULL
      AND  t.ID_DEPARTAMENTO_PADRE IS NOT NULL;

    RETURN 'DIM_DEPARTAMENTO OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_UBICACION()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_UBICACIONES AS
    SELECT ID_UBICACION, EDIFICIO, PLANTA, ALA, SALA, TIPO_SALA, CAPACIDAD
    FROM CONFORMED.STREAM_UBICACIONES
    WHERE METADATA$ACTION = 'INSERT';

    CALL CONFORMED.SP_MERGE_SCD1(
        'CONFORMED.DIM_UBICACION',
        'SELECT ID_UBICACION, EDIFICIO, PLANTA, ALA, SALA, TIPO_SALA, CAPACIDAD
         FROM CONFORMED._TMP_UBICACIONES',
        'ID_UBICACION',
        'EDIFICIO,PLANTA,ALA,SALA,TIPO_SALA,CAPACIDAD'
    );
    RETURN 'DIM_UBICACION OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_FABRICANTE()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_FABRICANTES AS
    SELECT ID_FABRICANTE, RAZON_SOCIAL AS NOMBRE_FABRICANTE,
           PAIS_ORIGEN, TELEFONO_CONTACTO, EMAIL_CONTACTO,
           SITIO_WEB, CERTIFICACION_ISO
    FROM CONFORMED.STREAM_FABRICANTES
    WHERE METADATA$ACTION = 'INSERT';

    CALL CONFORMED.SP_MERGE_SCD1(
        'CONFORMED.DIM_FABRICANTE',
        'SELECT ID_FABRICANTE, NOMBRE_FABRICANTE, PAIS_ORIGEN,
                TELEFONO_CONTACTO, EMAIL_CONTACTO, SITIO_WEB, CERTIFICACION_ISO
         FROM CONFORMED._TMP_FABRICANTES',
        'ID_FABRICANTE',
        'NOMBRE_FABRICANTE,PAIS_ORIGEN,TELEFONO_CONTACTO,EMAIL_CONTACTO,SITIO_WEB,CERTIFICACION_ISO'
    );
    RETURN 'DIM_FABRICANTE OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_MEDICO()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    -- JOIN con tablas secundarias al materializar (no al leer el stream dos veces)
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_MEDICOS AS
    SELECT s.ID_MEDICO, s.NOMBRE,
           s.APELLIDO1 || ' ' || s.APELLIDO2 AS APELLIDOS,
           s.NUMERO_COLEGIADO, s.TELEFONO, s.EMAIL,
           COALESCE(esp.NOMBRE_ESPECIALIDAD, 'Sin especialidad') AS ESPECIALIDAD,
           dep.NOMBRE_DEPARTAMENTO AS DEPARTAMENTO
    FROM CONFORMED.STREAM_MEDICOS s
    LEFT JOIN CLEANSED.ESPECIALIDADES esp ON esp.ID_ESPECIALIDAD     = s.ID_ESPECIALIDAD
    LEFT JOIN CLEANSED.DEPARTAMENTOS  dep ON dep.CODIGO_DEPARTAMENTO = s.CODIGO_DEPARTAMENTO
    WHERE s.METADATA$ACTION = 'INSERT';

    CALL CONFORMED.SP_MERGE_SCD1_SCD2(
        'CONFORMED.DIM_MEDICO',
        'SELECT ID_MEDICO, NOMBRE, APELLIDOS, NUMERO_COLEGIADO,
                TELEFONO, EMAIL, ESPECIALIDAD, DEPARTAMENTO
         FROM CONFORMED._TMP_MEDICOS',
        'ID_MEDICO',
        'NOMBRE,APELLIDOS,NUMERO_COLEGIADO,TELEFONO,EMAIL',
        'ESPECIALIDAD,DEPARTAMENTO'
    );
    RETURN 'DIM_MEDICO OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_TECNICO()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_TECNICOS AS
    SELECT tc.ID_TECNICO, tc.NOMBRE_TECNICO AS NOMBRE,
           tc.ESPECIALIDAD, tc.ANIOS_EXPERIENCIA,
           tc.TELEFONO_MOVIL AS TELEFONO, tc.EMAIL_CORPORATIVO AS EMAIL,
           dep.NOMBRE_DEPARTAMENTO AS DEPARTAMENTO,
           CASE tc.NIVEL_CERTIFICACION
               WHEN 1 THEN 'Junior'       WHEN 2 THEN 'Senior'
               WHEN 3 THEN 'Especialista' WHEN 4 THEN 'Jefe'
           END AS NIVEL_CERTIFICACION
    FROM CONFORMED.STREAM_TECNICOS tc
    LEFT JOIN CLEANSED.DEPARTAMENTOS dep ON dep.ID_DEPARTAMENTO = tc.ID_DEPARTAMENTO
    WHERE tc.METADATA$ACTION = 'INSERT';

    CALL CONFORMED.SP_MERGE_SCD1_SCD2(
        'CONFORMED.DIM_TECNICO',
        'SELECT ID_TECNICO, NOMBRE, ESPECIALIDAD, ANIOS_EXPERIENCIA,
                TELEFONO, EMAIL, DEPARTAMENTO, NIVEL_CERTIFICACION
         FROM CONFORMED._TMP_TECNICOS',
        'ID_TECNICO',
        'NOMBRE,ESPECIALIDAD,ANIOS_EXPERIENCIA,TELEFONO,EMAIL',
        'DEPARTAMENTO,NIVEL_CERTIFICACION'
    );
    RETURN 'DIM_TECNICO OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_PACIENTE()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_PACIENTES AS
    SELECT ID_PACIENTE, NOMBRE,
           APELLIDO1 || ' ' || APELLIDO2 AS APELLIDOS,
           FECHA_NACIMIENTO, SEXO AS GENERO,
           TELEFONO_MOVIL AS TELEFONO, EMAIL, GRUPO_SANGUINEO,
           DIRECCION, CIUDAD, CODIGO_POSTAL,
           COMPANIA_SEGURO AS SEGURO_MEDICO,
           TIPO_COBERTURA  AS TIPO_SEGURO
    FROM CONFORMED.STREAM_PACIENTES
    WHERE METADATA$ACTION = 'INSERT';

    CALL CONFORMED.SP_MERGE_SCD1_SCD2(
        'CONFORMED.DIM_PACIENTE',
        'SELECT ID_PACIENTE, NOMBRE, APELLIDOS, FECHA_NACIMIENTO, GENERO,
                TELEFONO, EMAIL, GRUPO_SANGUINEO,
                DIRECCION, CIUDAD, CODIGO_POSTAL, SEGURO_MEDICO, TIPO_SEGURO
         FROM CONFORMED._TMP_PACIENTES',
        'ID_PACIENTE',
        'NOMBRE,APELLIDOS,FECHA_NACIMIENTO,GENERO,TELEFONO,EMAIL,GRUPO_SANGUINEO',
        'DIRECCION,CIUDAD,CODIGO_POSTAL,SEGURO_MEDICO,TIPO_SEGURO'
    );
    RETURN 'DIM_PACIENTE OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_EQUIPO()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_EQUIPOS AS
    SELECT e.ID_EQUIPO, e.NOMBRE_EQUIPO, e.DESCRIPCION,
           e.NUMERO_SERIE, e.MODELO, e.FECHA_ADQUISICION,
           e.FECHA_FIN_GARANTIA, e.CLASE_RIESGO,
           CASE e.ESTADO_CODIGO
               WHEN 1 THEN 'Activo'            WHEN 2 THEN 'En Reparacion'
               WHEN 3 THEN 'Fuera de Servicio' WHEN 4 THEN 'Baja'
           END                              AS ESTADO_EQUIPO,
           d.NOMBRE_DEPARTAMENTO            AS DEPARTAMENTO_ACTUAL,
           u.EDIFICIO || ' - ' || u.SALA   AS UBICACION_ACTUAL
    FROM CONFORMED.STREAM_EQUIPOS e
    LEFT JOIN CLEANSED.DEPARTAMENTOS d ON e.ID_DEPARTAMENTO = d.ID_DEPARTAMENTO
    LEFT JOIN CLEANSED.UBICACIONES   u ON e.ID_UBICACION    = u.ID_UBICACION
    WHERE e.METADATA$ACTION = 'INSERT';

    CALL CONFORMED.SP_MERGE_SCD1_SCD2(
        'CONFORMED.DIM_EQUIPO',
        'SELECT ID_EQUIPO, NOMBRE_EQUIPO, DESCRIPCION, NUMERO_SERIE, MODELO,
                FECHA_ADQUISICION, FECHA_FIN_GARANTIA, CLASE_RIESGO,
                ESTADO_EQUIPO, DEPARTAMENTO_ACTUAL, UBICACION_ACTUAL
         FROM CONFORMED._TMP_EQUIPOS',
        'ID_EQUIPO',
        'NOMBRE_EQUIPO,DESCRIPCION,NUMERO_SERIE,MODELO,FECHA_ADQUISICION,FECHA_FIN_GARANTIA,CLASE_RIESGO',
        'ESTADO_EQUIPO,DEPARTAMENTO_ACTUAL,UBICACION_ACTUAL'
    );
    RETURN 'DIM_EQUIPO OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_ENSAYO()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_ENSAYOS AS
    SELECT ID_ENSAYO, CODIGO_ENSAYO,
           TITULO_ENSAYO      AS NOMBRE_ENSAYO,
           DESCRIPCION_ENSAYO AS DESCRIPCION,
           PATROCINADOR, FECHA_INICIO AS FECHA_INICIO_ENSAYO,
           FECHA_FIN_PREVISTA, ESTADO_ENSAYO,
           OBJETIVO_PRINCIPAL, MOLECULA_FARMACO
    FROM CONFORMED.STREAM_ENSAYOS_CLINICOS
    WHERE METADATA$ACTION = 'INSERT';

    CALL CONFORMED.SP_MERGE_SCD1(
        'CONFORMED.DIM_ENSAYO',
        'SELECT ID_ENSAYO, CODIGO_ENSAYO, NOMBRE_ENSAYO, DESCRIPCION,
                PATROCINADOR, FECHA_INICIO_ENSAYO, FECHA_FIN_PREVISTA,
                ESTADO_ENSAYO, OBJETIVO_PRINCIPAL, MOLECULA_FARMACO
         FROM CONFORMED._TMP_ENSAYOS',
        'ID_ENSAYO',
        'CODIGO_ENSAYO,NOMBRE_ENSAYO,DESCRIPCION,PATROCINADOR,FECHA_INICIO_ENSAYO,FECHA_FIN_PREVISTA,ESTADO_ENSAYO,OBJETIVO_PRINCIPAL,MOLECULA_FARMACO'
    );
    RETURN 'DIM_ENSAYO OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_DIAGNOSTICO()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_DIAGNOSTICOS AS
    SELECT ID_DIAGNOSTICO, CODIGO_CIE10,
           DESCRIPCION AS DESCRIPCION_DIAGNOSTICO,
           CAPITULO    AS CATEGORIA,
           GRUPO       AS SUBCATEGORIA,
           ES_CRONICO
    FROM CONFORMED.STREAM_DIAGNOSTICOS
    WHERE METADATA$ACTION = 'INSERT';

    CALL CONFORMED.SP_MERGE_SCD1(
        'CONFORMED.DIM_DIAGNOSTICO',
        'SELECT ID_DIAGNOSTICO, CODIGO_CIE10, DESCRIPCION_DIAGNOSTICO,
                CATEGORIA, SUBCATEGORIA, ES_CRONICO
         FROM CONFORMED._TMP_DIAGNOSTICOS',
        'ID_DIAGNOSTICO',
        'CODIGO_CIE10,DESCRIPCION_DIAGNOSTICO,CATEGORIA,SUBCATEGORIA,ES_CRONICO'
    );
    RETURN 'DIM_DIAGNOSTICO OK';
END;
$$;


-- DIM_PERFIL_MANTENIMIENTO: sin stream (generada por CROSS JOIN de valores fijos)
CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_PERFIL_MANTENIMIENTO()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO CONFORMED.DIM_PERFIL_MANTENIMIENTO (
        TIPO_MANTENIMIENTO, PRIORIDAD, GRAVEDAD, ES_GARANTIA, REQUIERE_PARADA_EQUIPO
    )
    SELECT tipo, prioridad, gravedad, garantia, parada
    FROM (VALUES ('Preventivo'), ('Correctivo'), ('Calibracion'), ('Inspeccion')) AS t(tipo)
    CROSS JOIN (VALUES ('Baja'), ('Media'), ('Alta'), ('Critica'))               AS p(prioridad)
    CROSS JOIN (VALUES ('Leve'), ('Moderada'), ('Grave'))                        AS g(gravedad)
    CROSS JOIN (VALUES (TRUE), (FALSE))                                          AS ga(garantia)
    CROSS JOIN (VALUES (TRUE), (FALSE))                                          AS pa(parada)
    WHERE NOT EXISTS (
        SELECT SK_PERFIL_MANTENIMIENTO FROM CONFORMED.DIM_PERFIL_MANTENIMIENTO
        WHERE TIPO_MANTENIMIENTO     = tipo
          AND PRIORIDAD              = prioridad
          AND GRAVEDAD               = gravedad
          AND ES_GARANTIA            = garantia
          AND REQUIERE_PARADA_EQUIPO = parada
    );

    RETURN 'DIM_PERFIL_MANTENIMIENTO OK';
END;
$$;


-- DIM_PERFIL_ENSAYO: sin stream (generada por CROSS JOIN de valores fijos)
CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_PERFIL_ENSAYO()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO CONFORMED.DIM_PERFIL_ENSAYO (
        FASE_ENSAYO, TIPO_CIEGO, TIPO_ALEATORIZACION, GRUPO_TRATAMIENTO, VIA_ADMINISTRACION
    )
    SELECT fase, ciego, aleatorizacion, grupo, via
    FROM (VALUES ('Fase I'), ('Fase II'), ('Fase III'), ('Fase IV'))                   AS f(fase)
    CROSS JOIN (VALUES ('Abierto'), ('Simple Ciego'), ('Doble Ciego'))                 AS c(ciego)
    CROSS JOIN (VALUES ('Aleatorizado'), ('No Aleatorizado'))                          AS a(aleatorizacion)
    CROSS JOIN (VALUES ('Experimental'), ('Control'), ('Placebo'))                     AS g(grupo)
    CROSS JOIN (VALUES ('Oral'), ('Intravenosa'), ('Subcutanea'), ('Topica'), ('Inhalatoria')) AS v(via)
    WHERE NOT EXISTS (
        SELECT SK_PERFIL_ENSAYO FROM CONFORMED.DIM_PERFIL_ENSAYO
        WHERE FASE_ENSAYO         = fase
          AND TIPO_CIEGO          = ciego
          AND TIPO_ALEATORIZACION = aleatorizacion
          AND GRUPO_TRATAMIENTO   = grupo
          AND VIA_ADMINISTRACION  = via
    );

    RETURN 'DIM_PERFIL_ENSAYO OK';
END;
$$;


-- ============================================================
-- STORED PROCEDURES — HECHOS
-- ============================================================

CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_FACT_MANTENIMIENTO_EQUIPOS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    -- Materializar stream de ordenes (tabla principal de esta fact)
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_ORDENES AS
    SELECT * FROM CONFORMED.STREAM_ORDENES_MANTENIMIENTO WHERE METADATA$ACTION = 'INSERT';

    INSERT INTO CONFORMED.FACT_MANTENIMIENTO_EQUIPOS (
        SK_FECHA, SK_EQUIPO, SK_TECNICO, SK_DEPARTAMENTO, SK_UBICACION,
        SK_FABRICANTE, SK_PERFIL_MANTENIMIENTO, ID_ORDEN,
        HORAS_TRABAJADAS, TARIFA_HORA, COSTO_REPUESTOS,
        COSTO_MANO_OBRA, COSTO_TOTAL,
        DURACION_HORAS, NUMERO_PIEZAS_REEMPLAZADAS, INDICADOR_REINCIDENCIA
    )
    SELECT
        TO_NUMBER(TO_CHAR(CAST(o.FECHA_INICIO_TRABAJO AS DATE), 'YYYYMMDD')) AS SK_FECHA,
        eq.SK_EQUIPO,
        tc.SK_TECNICO,
        dp.SK_DEPARTAMENTO,
        ub.SK_UBICACION,
        fa.SK_FABRICANTE,
        pm.SK_PERFIL_MANTENIMIENTO,
        o.ID_ORDEN,
        o.HORAS_TRABAJADAS,
        tc_src.TARIFA_HORA,
        cr.COSTO_REPUESTOS,
        o.HORAS_TRABAJADAS * tc_src.TARIFA_HORA                                AS COSTO_MANO_OBRA,
        COALESCE(cr.COSTO_REPUESTOS, 0) + (o.HORAS_TRABAJADAS * tc_src.TARIFA_HORA) AS COSTO_TOTAL,
        DATEDIFF(MINUTE, o.FECHA_INICIO_TRABAJO, o.FECHA_FIN_TRABAJO) / 60.0  AS DURACION_HORAS,
        cr.NUMERO_PIEZAS_REEMPLAZADAS,
        CASE WHEN EXISTS (
            SELECT ID_ORDEN FROM CLEANSED.ORDENES_MANTENIMIENTO prev
            WHERE prev.ID_EQUIPO          = o.ID_EQUIPO
              AND prev.TIPO_MANTENIMIENTO = 'Correctivo'
              AND prev.FECHA_INICIO_TRABAJO  < o.FECHA_INICIO_TRABAJO
              AND prev.FECHA_INICIO_TRABAJO >= DATEADD(DAY, -30, o.FECHA_INICIO_TRABAJO)
        ) THEN TRUE ELSE FALSE END AS INDICADOR_REINCIDENCIA
    FROM CONFORMED._TMP_ORDENES o
    JOIN CLEANSED.EQUIPOS               eq_src ON eq_src.ID_EQUIPO  = o.ID_EQUIPO
    JOIN CLEANSED.TECNICOS              tc_src ON tc_src.ID_TECNICO = o.ID_TECNICO
    LEFT JOIN (
        SELECT ID_ORDEN,
               SUM(CANTIDAD * PRECIO_UNITARIO_EN_MOMENTO) AS COSTO_REPUESTOS,
               SUM(CANTIDAD)                              AS NUMERO_PIEZAS_REEMPLAZADAS
        FROM CLEANSED.CONSUMO_REPUESTOS
        GROUP BY ID_ORDEN
    ) cr ON cr.ID_ORDEN = o.ID_ORDEN
    JOIN CONFORMED.DIM_EQUIPO               eq ON eq.ID_EQUIPO      = o.ID_EQUIPO        AND eq.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_TECNICO              tc ON tc.ID_TECNICO      = o.ID_TECNICO       AND tc.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_DEPARTAMENTO         dp ON dp.ID_DEPARTAMENTO = eq_src.ID_DEPARTAMENTO
    JOIN CONFORMED.DIM_UBICACION            ub ON ub.ID_UBICACION    = eq_src.ID_UBICACION
    JOIN CONFORMED.DIM_FABRICANTE           fa ON fa.ID_FABRICANTE   = eq_src.ID_FABRICANTE
    JOIN CONFORMED.DIM_PERFIL_MANTENIMIENTO pm
        ON  pm.TIPO_MANTENIMIENTO = CASE o.TIPO_MANTENIMIENTO
                                        WHEN 'PREV' THEN 'Preventivo'
                                        WHEN 'CORR' THEN 'Correctivo'
                                        WHEN 'CAL'  THEN 'Calibracion'
                                        WHEN 'INSP' THEN 'Inspeccion' END
        AND pm.PRIORIDAD = CASE o.PRIORIDAD
                               WHEN 1 THEN 'Baja' WHEN 2 THEN 'Media'
                               WHEN 3 THEN 'Alta' WHEN 4 THEN 'Critica' END
        AND pm.GRAVEDAD  = CASE o.GRAVEDAD
                               WHEN 1 THEN 'Leve' WHEN 2 THEN 'Moderada' WHEN 3 THEN 'Grave' END
        AND pm.ES_GARANTIA            = o.ES_CUBIERTO_POR_GARANTIA
        AND pm.REQUIERE_PARADA_EQUIPO = o.REQUIERE_PARADA
    WHERE NOT EXISTS (
        SELECT ID_ORDEN FROM CONFORMED.FACT_MANTENIMIENTO_EQUIPOS
        WHERE  ID_ORDEN = o.ID_ORDEN
    );

    RETURN 'FACT_MANTENIMIENTO_EQUIPOS OK';
END;
$$;

-- FACT_MONITORIZACION_PACIENTES: hecho de monitorizacion de pacientes
CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_FACT_MONITORIZACION_PACIENTES()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    -- Materializar stream de monitorizaciones (tabla principal de esta fact)
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_MONITORIZACIONES AS
    SELECT * FROM CONFORMED.STREAM_MONITORIZACIONES WHERE METADATA$ACTION = 'INSERT';

    INSERT INTO CONFORMED.FACT_MONITORIZACION_PACIENTES (
        SK_FECHA, SK_PACIENTE, SK_MEDICO, SK_EQUIPO,
        SK_DEPARTAMENTO, SK_UBICACION, SK_DIAGNOSTICO, ID_SESION,
        DURACION_MONITORIZACION_MIN,
        FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA,
        TEMPERATURA, SATURACION_OXIGENO, NIVEL_GLUCOSA, ALERTA_GENERADA
    )
    SELECT
        TO_NUMBER(TO_CHAR(m.FECHA_MONITORIZACION, 'YYYYMMDD')) AS SK_FECHA,
        pa.SK_PACIENTE, me.SK_MEDICO, eq.SK_EQUIPO,
        dp.SK_DEPARTAMENTO, ub.SK_UBICACION, di.SK_DIAGNOSTICO,
        m.ID_MONITORIZACION                                    AS ID_SESION,
        DATEDIFF(MINUTE, m.HORA_INICIO, m.HORA_FIN)           AS DURACION_MONITORIZACION_MIN,
        lsv.FRECUENCIA_CARDIACA, lsv.PRESION_SISTOLICA, lsv.PRESION_DIASTOLICA,
        lsv.TEMPERATURA, lsv.SATURACION_OXIGENO, lsv.NIVEL_GLUCOSA,
        CASE WHEN
            lsv.FRECUENCIA_CARDIACA < 60   OR lsv.FRECUENCIA_CARDIACA > 100  OR
            lsv.PRESION_SISTOLICA   < 90   OR lsv.PRESION_SISTOLICA   > 140  OR
            lsv.PRESION_DIASTOLICA  < 60   OR lsv.PRESION_DIASTOLICA  > 90   OR
            lsv.TEMPERATURA         < 36.0 OR lsv.TEMPERATURA         > 37.5 OR
            lsv.SATURACION_OXIGENO  < 95                                      OR
            lsv.NIVEL_GLUCOSA       < 70   OR lsv.NIVEL_GLUCOSA       > 140
        THEN TRUE ELSE FALSE END                               AS ALERTA_GENERADA
    FROM CONFORMED._TMP_MONITORIZACIONES m
    JOIN (
        SELECT ID_MONITORIZACION,
               AVG(FRECUENCIA_CARDIACA) AS FRECUENCIA_CARDIACA,
               AVG(PRESION_SISTOLICA)   AS PRESION_SISTOLICA,
               AVG(PRESION_DIASTOLICA)  AS PRESION_DIASTOLICA,
               AVG(TEMPERATURA)         AS TEMPERATURA,
               AVG(SATURACION_OXIGENO)  AS SATURACION_OXIGENO,
               AVG(NIVEL_GLUCOSA)       AS NIVEL_GLUCOSA
        FROM CLEANSED.LECTURAS_SIGNOS_VITALES
        GROUP BY ID_MONITORIZACION
    ) lsv ON lsv.ID_MONITORIZACION = m.ID_MONITORIZACION
    JOIN CLEANSED.EQUIPOS      eq_src ON eq_src.CODIGO_EQUIPO        = m.CODIGO_EQUIPO
    JOIN CLEANSED.DEPARTAMENTOS dp_src ON dp_src.CODIGO_DEPARTAMENTO = m.CODIGO_DEPARTAMENTO
    JOIN CLEANSED.UBICACIONES  ub_src ON ub_src.CODIGO_UBICACION     = m.CODIGO_UBICACION
    JOIN CONFORMED.DIM_PACIENTE     pa ON pa.ID_PACIENTE     = m.ID_PACIENTE          AND pa.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_MEDICO       me ON me.ID_MEDICO       = m.ID_MEDICO            AND me.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_EQUIPO       eq ON eq.ID_EQUIPO       = eq_src.ID_EQUIPO       AND eq.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_DEPARTAMENTO dp ON dp.ID_DEPARTAMENTO = dp_src.ID_DEPARTAMENTO
    JOIN CONFORMED.DIM_UBICACION    ub ON ub.ID_UBICACION    = ub_src.ID_UBICACION
    JOIN CONFORMED.DIM_DIAGNOSTICO  di ON di.ID_DIAGNOSTICO  = m.ID_DIAGNOSTICO
    WHERE NOT EXISTS (
        SELECT ID_SESION FROM CONFORMED.FACT_MONITORIZACION_PACIENTES
        WHERE  ID_SESION = m.ID_MONITORIZACION
    );

    RETURN 'FACT_MONITORIZACION_PACIENTES OK';
END;
$$;

-- FACT_ENSAYOS_CLINICOS: hecho de participacion en ensayos clinicos (con expansión a nivel de día)
CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_FACT_ENSAYOS_CLINICOS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    -- Materializar nuevas participaciones desde el stream
    CREATE OR REPLACE TEMPORARY TABLE CONFORMED._TMP_PARTICIPACIONES AS
    SELECT * FROM CONFORMED.STREAM_PARTICIPACION_ENSAYOS WHERE METADATA$ACTION = 'INSERT';

    -- Expandir cada nueva participacion a 1 fila por dia del rango
    INSERT INTO CONFORMED.FACT_ENSAYOS_CLINICOS (
        SK_FECHA, SK_FECHA_INICIO, SK_FECHA_FIN,
        SK_ENSAYO, SK_PACIENTE, SK_MEDICO, SK_DIAGNOSTICO,
        SK_DEPARTAMENTO, SK_PERFIL_ENSAYO, ID_PARTICIPACION,
        DOSIS_ADMINISTRADA, UNIDAD_DOSIS, NUMERO_EFECTOS_ADVERSOS,
        RESULTADO_MEDICION_PRINCIPAL, RESULTADO_MEDICION_SECUNDARIA, NIVEL_EFICACIA
    )
    SELECT
        TO_NUMBER(TO_CHAR(DATEADD('day', dias.n, p.FECHA_INICIO_PARTICIPACION), 'YYYYMMDD')) AS SK_FECHA,
        TO_NUMBER(TO_CHAR(p.FECHA_INICIO_PARTICIPACION, 'YYYYMMDD'))                         AS SK_FECHA_INICIO,
        TO_NUMBER(TO_CHAR(p.FECHA_FIN_PARTICIPACION,    'YYYYMMDD'))                         AS SK_FECHA_FIN,
        en.SK_ENSAYO, pa.SK_PACIENTE, me.SK_MEDICO, di.SK_DIAGNOSTICO,
        dp.SK_DEPARTAMENTO, pe.SK_PERFIL_ENSAYO,
        p.ID_PARTICIPACION,
        v.DOSIS_ADMINISTRADA, v.UNIDAD_DOSIS,
        v.NUMERO_EFECTOS_ADVERSOS, v.RESULTADO_MEDICION_PRINCIPAL,
        v.RESULTADO_MEDICION_SECUNDARIA, v.NIVEL_EFICACIA
    FROM CONFORMED._TMP_PARTICIPACIONES p
    JOIN (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 AS n
          FROM TABLE(GENERATOR(ROWCOUNT => 3650))) dias
    JOIN CLEANSED.ENSAYOS_CLINICOS       ec      ON ec.ID_ENSAYO               = p.ID_ENSAYO
    JOIN CLEANSED.DEPARTAMENTOS         dep_src ON dep_src.CODIGO_DEPARTAMENTO = ec.CODIGO_DEPARTAMENTO
    JOIN CONFORMED.DIM_ENSAYO        en ON en.ID_ENSAYO        = p.ID_ENSAYO
    JOIN CONFORMED.DIM_PACIENTE      pa ON pa.ID_PACIENTE       = p.ID_PACIENTE          AND pa.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_MEDICO        me ON me.ID_MEDICO         = p.ID_MEDICO_ASIGNADO   AND me.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_DIAGNOSTICO   di ON di.ID_DIAGNOSTICO    = p.ID_DIAGNOSTICO
    JOIN CONFORMED.DIM_DEPARTAMENTO  dp ON dp.ID_DEPARTAMENTO   = dep_src.ID_DEPARTAMENTO
    JOIN CONFORMED.DIM_PERFIL_ENSAYO pe
        ON  pe.FASE_ENSAYO         = CASE p.FASE
                                         WHEN 'F1' THEN 'Fase I'   WHEN 'F2' THEN 'Fase II'
                                         WHEN 'F3' THEN 'Fase III' WHEN 'F4' THEN 'Fase IV' END
        AND pe.TIPO_CIEGO          = CASE p.TIPO_CIEGO
                                         WHEN 'AB' THEN 'Abierto'
                                         WHEN 'SC' THEN 'Simple Ciego'
                                         WHEN 'DC' THEN 'Doble Ciego' END
        AND pe.TIPO_ALEATORIZACION = CASE p.TIPO_ALEATORIZACION
                                         WHEN 'AL' THEN 'Aleatorizado'
                                         WHEN 'NA' THEN 'No Aleatorizado' END
        AND pe.GRUPO_TRATAMIENTO   = CASE p.GRUPO_ASIGNADO
                                         WHEN 'EXP' THEN 'Experimental'
                                         WHEN 'CTR' THEN 'Control'
                                         WHEN 'PLA' THEN 'Placebo' END
        AND pe.VIA_ADMINISTRACION  = CASE p.VIA_ADMINISTRACION
                                         WHEN 'ORL' THEN 'Oral'
                                         WHEN 'IV'  THEN 'Intravenosa'
                                         WHEN 'SC'  THEN 'Subcutanea'
                                         WHEN 'TOP' THEN 'Topica'
                                         WHEN 'INH' THEN 'Inhalatoria' END
    LEFT JOIN CLEANSED.VISITAS_ENSAYO v
           ON v.ID_PARTICIPACION = p.ID_PARTICIPACION
          AND CAST(v.FECHA_VISITA AS DATE) = DATEADD('day', dias.n, p.FECHA_INICIO_PARTICIPACION)
    WHERE DATEADD('day', dias.n, p.FECHA_INICIO_PARTICIPACION)
              <= COALESCE(p.FECHA_FIN_PARTICIPACION, CURRENT_DATE)
      AND NOT EXISTS (
              SELECT 1 FROM CONFORMED.FACT_ENSAYOS_CLINICOS
              WHERE  ID_PARTICIPACION = p.ID_PARTICIPACION
                AND  SK_FECHA = TO_NUMBER(TO_CHAR(DATEADD('day', dias.n, p.FECHA_INICIO_PARTICIPACION), 'YYYYMMDD'))
          );

    RETURN 'FACT_ENSAYOS_CLINICOS OK';
END;
$$;


