-- streams_tasks.sql
-- Stored procedures y Task DAG para la capa CONFORMED
--
-- EJECUCION COMPLETA:
--   EXECUTE TASK CONFORMED.TASK_CONFORMED_ROOT;
--
-- EJECUCION POR DIMENSION INDIVIDUAL (asumiendo schema ya inicializado):
--   EXECUTE TASK CONFORMED.TASK_DIM_MEDICO;
--   EXECUTE TASK CONFORMED.TASK_DIM_PACIENTE;
--   EXECUTE TASK CONFORMED.TASK_DIM_ENSAYO;
--   ...
--
-- EJECUCION DE UN HECHO INDIVIDUAL (asumiendo dimensiones ya cargadas):
--   EXECUTE TASK CONFORMED.TASK_FACT_ENSAYOS_CLINICOS;

CREATE SCHEMA IF NOT EXISTS CONFORMED;


-- ============================================================
-- STORED PROCEDURES — DIMENSIONES
-- ============================================================

CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_FECHA()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CREATE OR REPLACE TABLE CONFORMED.DIM_FECHA AS
    WITH SERIE AS (
        SELECT DATEADD(DAY, SEQ4(), '2015-01-01'::DATE) AS FECHA
        FROM TABLE(GENERATOR(ROWCOUNT => 5844))
    )
    SELECT
        TO_NUMBER(TO_CHAR(FECHA, 'YYYYMMDD'))                   AS SK_FECHA,
        FECHA                                                   AS FECHA,
        YEAR(FECHA)                                             AS ANIO,
        CASE WHEN MONTH(FECHA) <= 6 THEN 1 ELSE 2 END          AS SEMESTRE,
        QUARTER(FECHA)                                          AS TRIMESTRE,
        MONTH(FECHA)                                            AS MES,
        CASE MONTH(FECHA)
            WHEN 1  THEN 'Enero'        WHEN 2  THEN 'Febrero'
            WHEN 3  THEN 'Marzo'        WHEN 4  THEN 'Abril'
            WHEN 5  THEN 'Mayo'         WHEN 6  THEN 'Junio'
            WHEN 7  THEN 'Julio'        WHEN 8  THEN 'Agosto'
            WHEN 9  THEN 'Septiembre'   WHEN 10 THEN 'Octubre'
            WHEN 11 THEN 'Noviembre'    WHEN 12 THEN 'Diciembre'
        END                                                     AS NOMBRE_MES,
        WEEKISO(FECHA)                                          AS SEMANA_ANIO,
        DAY(FECHA)                                              AS DIA,
        DAYOFWEEKISO(FECHA)                                     AS DIA_SEMANA,
        CASE DAYOFWEEKISO(FECHA)
            WHEN 1 THEN 'Lunes'         WHEN 2 THEN 'Martes'
            WHEN 3 THEN 'Miercoles'     WHEN 4 THEN 'Jueves'
            WHEN 5 THEN 'Viernes'       WHEN 6 THEN 'Sabado'
            WHEN 7 THEN 'Domingo'
        END                                                     AS NOMBRE_DIA,
        DAYOFWEEKISO(FECHA) IN (6, 7)                          AS ES_FIN_SEMANA,
        FALSE                                                   AS ES_FESTIVO
    FROM SERIE;

    ALTER TABLE CONFORMED.DIM_FECHA
        ADD CONSTRAINT PK_DIM_FECHA PRIMARY KEY (SK_FECHA);

    RETURN 'DIM_FECHA OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_DEPARTAMENTO()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    WITH JERARQUIA AS (
        SELECT ID_DEPARTAMENTO, ID_DEPARTAMENTO_PADRE, 1 AS NIVEL_JERARQUIA
        FROM CLEANSED_MEDICARE.DEPARTAMENTOS
        WHERE ID_DEPARTAMENTO_PADRE IS NULL
        UNION ALL
        SELECT d.ID_DEPARTAMENTO, d.ID_DEPARTAMENTO_PADRE, j.NIVEL_JERARQUIA + 1
        FROM CLEANSED_MEDICARE.DEPARTAMENTOS d
        JOIN JERARQUIA j ON j.ID_DEPARTAMENTO = d.ID_DEPARTAMENTO_PADRE
    )
    UPDATE CONFORMED.DIM_DEPARTAMENTO t
    SET
        NOMBRE_DEPARTAMENTO   = s.NOMBRE_DEPARTAMENTO,
        ID_DEPARTAMENTO_PADRE = s.ID_DEPARTAMENTO_PADRE,
        SK_DEPARTAMENTO_PADRE = (
            SELECT SK_DEPARTAMENTO FROM CONFORMED.DIM_DEPARTAMENTO
            WHERE  ID_DEPARTAMENTO = s.ID_DEPARTAMENTO_PADRE
        ),
        NIVEL_JERARQUIA       = s.NIVEL_JERARQUIA,
        RESPONSABLE           = s.RESPONSABLE,
        TELEFONO_DEPARTAMENTO = s.TELEFONO_DEPARTAMENTO,
        EMAIL_DEPARTAMENTO    = s.EMAIL_DEPARTAMENTO
    FROM (
        SELECT d.ID_DEPARTAMENTO, d.NOMBRE_DEPARTAMENTO, d.ID_DEPARTAMENTO_PADRE,
               j.NIVEL_JERARQUIA, d.NOMBRE_RESPONSABLE AS RESPONSABLE,
               d.TELEFONO_DEPARTAMENTO, d.EMAIL_DEPARTAMENTO
        FROM CLEANSED_MEDICARE.DEPARTAMENTOS d
        JOIN JERARQUIA j ON j.ID_DEPARTAMENTO = d.ID_DEPARTAMENTO
    ) s
    WHERE t.ID_DEPARTAMENTO = s.ID_DEPARTAMENTO
      AND (t.NOMBRE_DEPARTAMENTO   IS DISTINCT FROM s.NOMBRE_DEPARTAMENTO   OR
           t.ID_DEPARTAMENTO_PADRE IS DISTINCT FROM s.ID_DEPARTAMENTO_PADRE OR
           t.NIVEL_JERARQUIA       IS DISTINCT FROM s.NIVEL_JERARQUIA       OR
           t.RESPONSABLE           IS DISTINCT FROM s.RESPONSABLE           OR
           t.TELEFONO_DEPARTAMENTO IS DISTINCT FROM s.TELEFONO_DEPARTAMENTO OR
           t.EMAIL_DEPARTAMENTO    IS DISTINCT FROM s.EMAIL_DEPARTAMENTO);

    WITH JERARQUIA AS (
        SELECT ID_DEPARTAMENTO, ID_DEPARTAMENTO_PADRE, 1 AS NIVEL_JERARQUIA
        FROM CLEANSED_MEDICARE.DEPARTAMENTOS
        WHERE ID_DEPARTAMENTO_PADRE IS NULL
        UNION ALL
        SELECT d.ID_DEPARTAMENTO, d.ID_DEPARTAMENTO_PADRE, j.NIVEL_JERARQUIA + 1
        FROM CLEANSED_MEDICARE.DEPARTAMENTOS d
        JOIN JERARQUIA j ON j.ID_DEPARTAMENTO = d.ID_DEPARTAMENTO_PADRE
    )
    INSERT INTO CONFORMED.DIM_DEPARTAMENTO (
        ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ID_DEPARTAMENTO_PADRE,
        SK_DEPARTAMENTO_PADRE, NIVEL_JERARQUIA, RESPONSABLE,
        TELEFONO_DEPARTAMENTO, EMAIL_DEPARTAMENTO
    )
    SELECT d.ID_DEPARTAMENTO, d.NOMBRE_DEPARTAMENTO, d.ID_DEPARTAMENTO_PADRE,
           (SELECT SK_DEPARTAMENTO FROM CONFORMED.DIM_DEPARTAMENTO
            WHERE  ID_DEPARTAMENTO = d.ID_DEPARTAMENTO_PADRE),
           j.NIVEL_JERARQUIA, d.NOMBRE_RESPONSABLE AS RESPONSABLE,
           d.TELEFONO_DEPARTAMENTO, d.EMAIL_DEPARTAMENTO
    FROM CLEANSED_MEDICARE.DEPARTAMENTOS d
    JOIN JERARQUIA j ON j.ID_DEPARTAMENTO = d.ID_DEPARTAMENTO
    WHERE NOT EXISTS (
        SELECT ID_DEPARTAMENTO FROM CONFORMED.DIM_DEPARTAMENTO
        WHERE  ID_DEPARTAMENTO = d.ID_DEPARTAMENTO
    );

    UPDATE CONFORMED.DIM_DEPARTAMENTO t
    SET    SK_DEPARTAMENTO_PADRE = p.SK_DEPARTAMENTO
    FROM   CONFORMED.DIM_DEPARTAMENTO p
    WHERE  t.ID_DEPARTAMENTO_PADRE = p.ID_DEPARTAMENTO
      AND  t.SK_DEPARTAMENTO_PADRE IS NULL
      AND  t.ID_DEPARTAMENTO_PADRE IS NOT NULL;

    RETURN 'DIM_DEPARTAMENTO OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_UBICACION()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CALL CONFORMED.SP_MERGE_SCD1(
        'CONFORMED.DIM_UBICACION',
        'SELECT ID_UBICACION, EDIFICIO, PLANTA, ALA, SALA, TIPO_SALA, CAPACIDAD
         FROM CLEANSED_MEDICARE.UBICACIONES',
        'ID_UBICACION',
        'EDIFICIO,PLANTA,ALA,SALA,TIPO_SALA,CAPACIDAD'
    );
    RETURN 'DIM_UBICACION OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_FABRICANTE()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CALL CONFORMED.SP_MERGE_SCD1(
        'CONFORMED.DIM_FABRICANTE',
        'SELECT ID_FABRICANTE, RAZON_SOCIAL AS NOMBRE_FABRICANTE,
                PAIS_ORIGEN, TELEFONO_CONTACTO, EMAIL_CONTACTO,
                SITIO_WEB, CERTIFICACION_ISO
         FROM CLEANSED_MEDICARE.FABRICANTES',
        'ID_FABRICANTE',
        'NOMBRE_FABRICANTE,PAIS_ORIGEN,TELEFONO_CONTACTO,EMAIL_CONTACTO,SITIO_WEB,CERTIFICACION_ISO'
    );
    RETURN 'DIM_FABRICANTE OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_MEDICO()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CALL CONFORMED.SP_MERGE_SCD1_SCD2(
        'CONFORMED.DIM_MEDICO',
        'SELECT m.ID_MEDICO, m.NOMBRE,
                m.APELLIDO1 || '' '' || m.APELLIDO2 AS APELLIDOS,
                m.NUMERO_COLEGIADO, m.TELEFONO, m.EMAIL,
                esp.NOMBRE_ESPECIALIDAD AS ESPECIALIDAD,
                dep.NOMBRE_DEPARTAMENTO AS DEPARTAMENTO
         FROM CLEANSED_MEDICARE.MEDICOS m
         LEFT JOIN CLEANSED_MEDICARE.ESPECIALIDADES esp ON esp.ID_ESPECIALIDAD     = m.ID_ESPECIALIDAD
         LEFT JOIN CLEANSED_MEDICARE.DEPARTAMENTOS  dep ON dep.CODIGO_DEPARTAMENTO = m.CODIGO_DEPARTAMENTO',
        'ID_MEDICO',
        'NOMBRE,APELLIDOS,NUMERO_COLEGIADO,TELEFONO,EMAIL',
        'ESPECIALIDAD,DEPARTAMENTO'
    );
    RETURN 'DIM_MEDICO OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_TECNICO()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CALL CONFORMED.SP_MERGE_SCD1_SCD2(
        'CONFORMED.DIM_TECNICO',
        'SELECT tc.ID_TECNICO, tc.NOMBRE_TECNICO AS NOMBRE,
                tc.ESPECIALIDAD, tc.ANIOS_EXPERIENCIA,
                tc.TELEFONO_MOVIL AS TELEFONO, tc.EMAIL_CORPORATIVO AS EMAIL,
                dep.NOMBRE_DEPARTAMENTO AS DEPARTAMENTO,
                CASE tc.NIVEL_CERTIFICACION
                    WHEN 1 THEN ''Junior''  WHEN 2 THEN ''Senior''
                    WHEN 3 THEN ''Especialista'' WHEN 4 THEN ''Jefe''
                END AS NIVEL_CERTIFICACION
         FROM CLEANSED_MEDICARE.TECNICOS tc
         LEFT JOIN CLEANSED_MEDICARE.DEPARTAMENTOS dep ON dep.ID_DEPARTAMENTO = tc.ID_DEPARTAMENTO',
        'ID_TECNICO',
        'NOMBRE,ESPECIALIDAD,ANIOS_EXPERIENCIA,TELEFONO,EMAIL',
        'DEPARTAMENTO,NIVEL_CERTIFICACION'
    );
    RETURN 'DIM_TECNICO OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_PACIENTE()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CALL CONFORMED.SP_MERGE_SCD1_SCD2(
        'CONFORMED.DIM_PACIENTE',
        'SELECT ID_PACIENTE, NOMBRE,
                APELLIDO1 || '' '' || APELLIDO2 AS APELLIDOS,
                FECHA_NACIMIENTO, SEXO AS GENERO,
                TELEFONO_MOVIL AS TELEFONO, EMAIL, GRUPO_SANGUINEO,
                DIRECCION, CIUDAD, CODIGO_POSTAL,
                COMPANIA_SEGURO AS SEGURO_MEDICO,
                TIPO_COBERTURA  AS TIPO_SEGURO
         FROM CLEANSED_MEDICARE.PACIENTES',
        'ID_PACIENTE',
        'NOMBRE,APELLIDOS,FECHA_NACIMIENTO,GENERO,TELEFONO,EMAIL,GRUPO_SANGUINEO',
        'DIRECCION,CIUDAD,CODIGO_POSTAL,SEGURO_MEDICO,TIPO_SEGURO'
    );
    RETURN 'DIM_PACIENTE OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_EQUIPO()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CALL CONFORMED.SP_MERGE_SCD1_SCD2(
        'CONFORMED.DIM_EQUIPO',
        'SELECT e.ID_EQUIPO, e.NOMBRE_EQUIPO, e.DESCRIPCION,
                e.NUMERO_SERIE, e.MODELO, e.FECHA_ADQUISICION,
                e.FECHA_FIN_GARANTIA, e.CLASE_RIESGO,
                CASE e.ESTADO_CODIGO
                    WHEN 1 THEN ''Activo''          WHEN 2 THEN ''En Reparacion''
                    WHEN 3 THEN ''Fuera de Servicio'' WHEN 4 THEN ''Baja''
                END                              AS ESTADO_EQUIPO,
                d.NOMBRE_DEPARTAMENTO            AS DEPARTAMENTO_ACTUAL,
                u.EDIFICIO || '' - '' || u.SALA  AS UBICACION_ACTUAL
         FROM CLEANSED_MEDICARE.EQUIPOS e
         LEFT JOIN CLEANSED_MEDICARE.DEPARTAMENTOS d ON e.ID_DEPARTAMENTO = d.ID_DEPARTAMENTO
         LEFT JOIN CLEANSED_MEDICARE.UBICACIONES   u ON e.ID_UBICACION    = u.ID_UBICACION',
        'ID_EQUIPO',
        'NOMBRE_EQUIPO,DESCRIPCION,NUMERO_SERIE,MODELO,FECHA_ADQUISICION,FECHA_FIN_GARANTIA,CLASE_RIESGO',
        'ESTADO_EQUIPO,DEPARTAMENTO_ACTUAL,UBICACION_ACTUAL'
    );
    RETURN 'DIM_EQUIPO OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_ENSAYO()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CALL CONFORMED.SP_MERGE_SCD1(
        'CONFORMED.DIM_ENSAYO',
        'SELECT ID_ENSAYO, CODIGO_ENSAYO,
                TITULO_ENSAYO      AS NOMBRE_ENSAYO,
                DESCRIPCION_ENSAYO AS DESCRIPCION,
                PATROCINADOR, FECHA_INICIO AS FECHA_INICIO_ENSAYO,
                FECHA_FIN_PREVISTA, ESTADO_ENSAYO,
                OBJETIVO_PRINCIPAL, MOLECULA_FARMACO
         FROM CLEANSED_MEDICARE.ENSAYOS_CLINICOS',
        'ID_ENSAYO',
        'CODIGO_ENSAYO,NOMBRE_ENSAYO,DESCRIPCION,PATROCINADOR,FECHA_INICIO_ENSAYO,FECHA_FIN_PREVISTA,ESTADO_ENSAYO,OBJETIVO_PRINCIPAL,MOLECULA_FARMACO'
    );
    RETURN 'DIM_ENSAYO OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_DIAGNOSTICO()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CALL CONFORMED.SP_MERGE_SCD1(
        'CONFORMED.DIM_DIAGNOSTICO',
        'SELECT ID_DIAGNOSTICO, CODIGO_CIE10,
                DESCRIPCION AS DESCRIPCION_DIAGNOSTICO,
                CAPITULO    AS CATEGORIA,
                GRUPO       AS SUBCATEGORIA,
                ES_CRONICO
         FROM CLEANSED_MEDICARE.DIAGNOSTICOS_CIE10',
        'ID_DIAGNOSTICO',
        'CODIGO_CIE10,DESCRIPCION_DIAGNOSTICO,CATEGORIA,SUBCATEGORIA,ES_CRONICO'
    );
    RETURN 'DIM_DIAGNOSTICO OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_PERFIL_MANTENIMIENTO()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO CONFORMED.DIM_PERFIL_MANTENIMIENTO (
        TIPO_MANTENIMIENTO, PRIORIDAD, GRAVEDAD, ES_GARANTIA, REQUIERE_PARADA_EQUIPO
    )
    SELECT tipo, prioridad, gravedad, garantia, parada
    FROM (VALUES ('Preventivo'), ('Correctivo'), ('Calibracion'), ('Inspeccion')) AS t(tipo)
    CROSS JOIN (VALUES ('Baja'), ('Media'), ('Alta'), ('Critica'))               AS p(prioridad)
    CROSS JOIN (VALUES ('Leve'), ('Moderada'), ('Grave'))                        AS g(gravedad)
    CROSS JOIN (VALUES (TRUE), (FALSE))                                          AS ga(garantia)
    CROSS JOIN (VALUES (TRUE), (FALSE))                                          AS pa(parada)
    WHERE NOT EXISTS (
        SELECT SK_PERFIL_MANTENIMIENTO FROM CONFORMED.DIM_PERFIL_MANTENIMIENTO
        WHERE TIPO_MANTENIMIENTO     = tipo
          AND PRIORIDAD              = prioridad
          AND GRAVEDAD               = gravedad
          AND ES_GARANTIA            = garantia
          AND REQUIERE_PARADA_EQUIPO = parada
    );

    RETURN 'DIM_PERFIL_MANTENIMIENTO OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_DIM_PERFIL_ENSAYO()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO CONFORMED.DIM_PERFIL_ENSAYO (
        FASE_ENSAYO, TIPO_CIEGO, TIPO_ALEATORIZACION, GRUPO_TRATAMIENTO, VIA_ADMINISTRACION
    )
    SELECT fase, ciego, aleatorizacion, grupo, via
    FROM (VALUES ('Fase I'), ('Fase II'), ('Fase III'), ('Fase IV'))                   AS f(fase)
    CROSS JOIN (VALUES ('Abierto'), ('Simple Ciego'), ('Doble Ciego'))                 AS c(ciego)
    CROSS JOIN (VALUES ('Aleatorizado'), ('No Aleatorizado'))                          AS a(aleatorizacion)
    CROSS JOIN (VALUES ('Experimental'), ('Control'), ('Placebo'))                     AS g(grupo)
    CROSS JOIN (VALUES ('Oral'), ('Intravenosa'), ('Subcutanea'), ('Topica'), ('Inhalatoria')) AS v(via)
    WHERE NOT EXISTS (
        SELECT SK_PERFIL_ENSAYO FROM CONFORMED.DIM_PERFIL_ENSAYO
        WHERE FASE_ENSAYO         = fase
          AND TIPO_CIEGO          = ciego
          AND TIPO_ALEATORIZACION = aleatorizacion
          AND GRUPO_TRATAMIENTO   = grupo
          AND VIA_ADMINISTRACION  = via
    );

    RETURN 'DIM_PERFIL_ENSAYO OK';
END;
$$;


-- ============================================================
-- STORED PROCEDURES — HECHOS
-- ============================================================

CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_FACT_MANTENIMIENTO_EQUIPOS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO CONFORMED.FACT_MANTENIMIENTO_EQUIPOS (
        SK_FECHA, SK_EQUIPO, SK_TECNICO, SK_DEPARTAMENTO, SK_UBICACION,
        SK_FABRICANTE, SK_PERFIL_MANTENIMIENTO, ID_ORDEN,
        HORAS_TRABAJADAS, TARIFA_HORA, COSTO_REPUESTOS,
        COSTO_MANO_OBRA, COSTO_TOTAL,
        DURACION_HORAS, NUMERO_PIEZAS_REEMPLAZADAS, INDICADOR_REINCIDENCIA
    )
    SELECT
        TO_NUMBER(TO_CHAR(CAST(o.FECHA_INICIO_TRABAJO AS DATE), 'YYYYMMDD')) AS SK_FECHA,
        eq.SK_EQUIPO,
        tc.SK_TECNICO,
        dp.SK_DEPARTAMENTO,
        ub.SK_UBICACION,
        fa.SK_FABRICANTE,
        pm.SK_PERFIL_MANTENIMIENTO,
        o.ID_ORDEN,
        o.HORAS_TRABAJADAS,
        tc_src.TARIFA_HORA,
        cr.COSTO_REPUESTOS,
        o.HORAS_TRABAJADAS * tc_src.TARIFA_HORA                                AS COSTO_MANO_OBRA,
        COALESCE(cr.COSTO_REPUESTOS, 0) + (o.HORAS_TRABAJADAS * tc_src.TARIFA_HORA) AS COSTO_TOTAL,
        DATEDIFF(MINUTE, o.FECHA_INICIO_TRABAJO, o.FECHA_FIN_TRABAJO) / 60.0  AS DURACION_HORAS,
        cr.NUMERO_PIEZAS_REEMPLAZADAS,
        CASE WHEN EXISTS (
            SELECT ID_ORDEN FROM CLEANSED_MEDICARE.ORDENES_MANTENIMIENTO prev
            WHERE prev.ID_EQUIPO          = o.ID_EQUIPO
              AND prev.TIPO_MANTENIMIENTO = 'Correctivo'
              AND prev.FECHA_INICIO_TRABAJO  < o.FECHA_INICIO_TRABAJO
              AND prev.FECHA_INICIO_TRABAJO >= DATEADD(DAY, -30, o.FECHA_INICIO_TRABAJO)
        ) THEN TRUE ELSE FALSE END AS INDICADOR_REINCIDENCIA
    FROM CLEANSED_MEDICARE.ORDENES_MANTENIMIENTO o
    JOIN CLEANSED_MEDICARE.EQUIPOS               eq_src ON eq_src.ID_EQUIPO  = o.ID_EQUIPO
    JOIN CLEANSED_MEDICARE.TECNICOS              tc_src ON tc_src.ID_TECNICO = o.ID_TECNICO
    LEFT JOIN (
        SELECT ID_ORDEN,
               SUM(CANTIDAD * PRECIO_UNITARIO_EN_MOMENTO) AS COSTO_REPUESTOS,
               SUM(CANTIDAD)                              AS NUMERO_PIEZAS_REEMPLAZADAS
        FROM CLEANSED_MEDICARE.CONSUMO_REPUESTOS
        GROUP BY ID_ORDEN
    ) cr ON cr.ID_ORDEN = o.ID_ORDEN
    JOIN CONFORMED.DIM_EQUIPO               eq ON eq.ID_EQUIPO      = o.ID_EQUIPO        AND eq.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_TECNICO              tc ON tc.ID_TECNICO      = o.ID_TECNICO       AND tc.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_DEPARTAMENTO         dp ON dp.ID_DEPARTAMENTO = eq_src.ID_DEPARTAMENTO
    JOIN CONFORMED.DIM_UBICACION            ub ON ub.ID_UBICACION    = eq_src.ID_UBICACION
    JOIN CONFORMED.DIM_FABRICANTE           fa ON fa.ID_FABRICANTE   = eq_src.ID_FABRICANTE
    JOIN CONFORMED.DIM_PERFIL_MANTENIMIENTO pm ON pm.TIPO_MANTENIMIENTO = o.TIPO_MANTENIMIENTO
        AND pm.PRIORIDAD = CASE o.PRIORIDAD
                               WHEN 1 THEN 'Baja' WHEN 2 THEN 'Media'
                               WHEN 3 THEN 'Alta' WHEN 4 THEN 'Critica' END
        AND pm.GRAVEDAD  = CASE o.GRAVEDAD
                               WHEN 1 THEN 'Leve' WHEN 2 THEN 'Moderada' WHEN 3 THEN 'Grave' END
        AND pm.ES_GARANTIA            = o.ES_CUBIERTO_POR_GARANTIA
        AND pm.REQUIERE_PARADA_EQUIPO = o.REQUIERE_PARADA
    WHERE NOT EXISTS (
        SELECT ID_ORDEN FROM CONFORMED.FACT_MANTENIMIENTO_EQUIPOS
        WHERE  ID_ORDEN = o.ID_ORDEN
    );

    RETURN 'FACT_MANTENIMIENTO_EQUIPOS OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_FACT_MONITORIZACION_PACIENTES()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO CONFORMED.FACT_MONITORIZACION_PACIENTES (
        SK_FECHA, SK_PACIENTE, SK_MEDICO, SK_EQUIPO,
        SK_DEPARTAMENTO, SK_UBICACION, SK_DIAGNOSTICO, ID_SESION,
        DURACION_MONITORIZACION_MIN,
        FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA,
        TEMPERATURA, SATURACION_OXIGENO, NIVEL_GLUCOSA, ALERTA_GENERADA
    )
    SELECT
        TO_NUMBER(TO_CHAR(m.FECHA_MONITORIZACION, 'YYYYMMDD')) AS SK_FECHA,
        pa.SK_PACIENTE, me.SK_MEDICO, eq.SK_EQUIPO,
        dp.SK_DEPARTAMENTO, ub.SK_UBICACION, di.SK_DIAGNOSTICO,
        m.ID_MONITORIZACION                                    AS ID_SESION,
        DATEDIFF(MINUTE, m.HORA_INICIO, m.HORA_FIN)           AS DURACION_MONITORIZACION_MIN,
        lsv.FRECUENCIA_CARDIACA, lsv.PRESION_SISTOLICA, lsv.PRESION_DIASTOLICA,
        lsv.TEMPERATURA, lsv.SATURACION_OXIGENO, lsv.NIVEL_GLUCOSA,
        CASE WHEN
            lsv.FRECUENCIA_CARDIACA < 60   OR lsv.FRECUENCIA_CARDIACA > 100  OR
            lsv.PRESION_SISTOLICA   < 90   OR lsv.PRESION_SISTOLICA   > 140  OR
            lsv.PRESION_DIASTOLICA  < 60   OR lsv.PRESION_DIASTOLICA  > 90   OR
            lsv.TEMPERATURA         < 36.0 OR lsv.TEMPERATURA         > 37.5 OR
            lsv.SATURACION_OXIGENO  < 95                                      OR
            lsv.NIVEL_GLUCOSA       < 70   OR lsv.NIVEL_GLUCOSA       > 140
        THEN TRUE ELSE FALSE END                               AS ALERTA_GENERADA
    FROM CLEANSED_MEDICARE.MONITORIZACIONES m
    JOIN (
        SELECT ID_MONITORIZACION,
               AVG(FRECUENCIA_CARDIACA) AS FRECUENCIA_CARDIACA,
               AVG(PRESION_SISTOLICA)   AS PRESION_SISTOLICA,
               AVG(PRESION_DIASTOLICA)  AS PRESION_DIASTOLICA,
               AVG(TEMPERATURA)         AS TEMPERATURA,
               AVG(SATURACION_OXIGENO)  AS SATURACION_OXIGENO,
               AVG(NIVEL_GLUCOSA)       AS NIVEL_GLUCOSA
        FROM CLEANSED_MEDICARE.LECTURAS_SIGNOS_VITALES
        GROUP BY ID_MONITORIZACION
    ) lsv ON lsv.ID_MONITORIZACION = m.ID_MONITORIZACION
    JOIN CLEANSED_MEDICARE.EQUIPOS      eq_src ON eq_src.CODIGO_EQUIPO        = m.CODIGO_EQUIPO
    JOIN CLEANSED_MEDICARE.DEPARTAMENTOS dp_src ON dp_src.CODIGO_DEPARTAMENTO = m.CODIGO_DEPARTAMENTO
    JOIN CLEANSED_MEDICARE.UBICACIONES  ub_src ON ub_src.CODIGO_UBICACION     = m.CODIGO_UBICACION
    JOIN CONFORMED.DIM_PACIENTE     pa ON pa.ID_PACIENTE     = m.ID_PACIENTE          AND pa.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_MEDICO       me ON me.ID_MEDICO       = m.ID_MEDICO            AND me.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_EQUIPO       eq ON eq.ID_EQUIPO       = eq_src.ID_EQUIPO       AND eq.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_DEPARTAMENTO dp ON dp.ID_DEPARTAMENTO = dp_src.ID_DEPARTAMENTO
    JOIN CONFORMED.DIM_UBICACION    ub ON ub.ID_UBICACION    = ub_src.ID_UBICACION
    JOIN CONFORMED.DIM_DIAGNOSTICO  di ON di.ID_DIAGNOSTICO  = m.ID_DIAGNOSTICO
    WHERE NOT EXISTS (
        SELECT ID_SESION FROM CONFORMED.FACT_MONITORIZACION_PACIENTES
        WHERE  ID_SESION = m.ID_MONITORIZACION
    );

    RETURN 'FACT_MONITORIZACION_PACIENTES OK';
END;
$$;


CREATE OR REPLACE PROCEDURE CONFORMED.SP_LOAD_FACT_ENSAYOS_CLINICOS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO CONFORMED.FACT_ENSAYOS_CLINICOS (
        SK_FECHA, SK_FECHA_INICIO, SK_FECHA_FIN,
        SK_ENSAYO, SK_PACIENTE, SK_MEDICO, SK_DIAGNOSTICO,
        SK_DEPARTAMENTO, SK_PERFIL_ENSAYO, ID_VISITA,
        DOSIS_ADMINISTRADA, UNIDAD_DOSIS, NUMERO_EFECTOS_ADVERSOS,
        RESULTADO_MEDICION_PRINCIPAL, RESULTADO_MEDICION_SECUNDARIA, NIVEL_EFICACIA
    )
    SELECT
        TO_NUMBER(TO_CHAR(v.FECHA_VISITA, 'YYYYMMDD'))               AS SK_FECHA,
        TO_NUMBER(TO_CHAR(p.FECHA_INICIO_PARTICIPACION, 'YYYYMMDD')) AS SK_FECHA_INICIO,
        TO_NUMBER(TO_CHAR(p.FECHA_FIN_PARTICIPACION,    'YYYYMMDD')) AS SK_FECHA_FIN,
        en.SK_ENSAYO, pa.SK_PACIENTE, me.SK_MEDICO, di.SK_DIAGNOSTICO,
        dp.SK_DEPARTAMENTO, pe.SK_PERFIL_ENSAYO,
        v.ID_VISITA, v.DOSIS_ADMINISTRADA, v.UNIDAD_DOSIS,
        v.NUMERO_EFECTOS_ADVERSOS, v.RESULTADO_MEDICION_PRINCIPAL,
        v.RESULTADO_MEDICION_SECUNDARIA, v.NIVEL_EFICACIA
    FROM CLEANSED_MEDICARE.VISITAS_ENSAYO v
    JOIN CLEANSED_MEDICARE.PARTICIPACION_ENSAYOS p   ON p.ID_PARTICIPACION       = v.ID_PARTICIPACION
    JOIN CLEANSED_MEDICARE.ENSAYOS_CLINICOS      ec  ON ec.ID_ENSAYO             = p.ID_ENSAYO
    JOIN CLEANSED_MEDICARE.DEPARTAMENTOS         dep_src ON dep_src.CODIGO_DEPARTAMENTO = ec.CODIGO_DEPARTAMENTO
    JOIN CONFORMED.DIM_ENSAYO        en ON en.ID_ENSAYO        = p.ID_ENSAYO
    JOIN CONFORMED.DIM_PACIENTE      pa ON pa.ID_PACIENTE       = p.ID_PACIENTE       AND pa.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_MEDICO        me ON me.ID_MEDICO         = p.ID_MEDICO_ASIGNADO AND me.ES_ACTUAL = TRUE
    JOIN CONFORMED.DIM_DIAGNOSTICO   di ON di.ID_DIAGNOSTICO    = p.ID_DIAGNOSTICO
    JOIN CONFORMED.DIM_DEPARTAMENTO  dp ON dp.ID_DEPARTAMENTO   = dep_src.ID_DEPARTAMENTO
    JOIN CONFORMED.DIM_PERFIL_ENSAYO pe ON pe.FASE_ENSAYO         = p.FASE
                                       AND pe.TIPO_CIEGO           = p.TIPO_CIEGO
                                       AND pe.TIPO_ALEATORIZACION  = p.TIPO_ALEATORIZACION
                                       AND pe.GRUPO_TRATAMIENTO    = p.GRUPO_ASIGNADO
                                       AND pe.VIA_ADMINISTRACION   = p.VIA_ADMINISTRACION
    WHERE NOT EXISTS (
        SELECT ID_VISITA FROM CONFORMED.FACT_ENSAYOS_CLINICOS
        WHERE  ID_VISITA = v.ID_VISITA
    );

    RETURN 'FACT_ENSAYOS_CLINICOS OK';
END;
$$;


-- ============================================================
-- TASK DAG
-- Estructura:
--   ROOT → 12 dimensiones en paralelo → 3 hechos en paralelo
--
-- Para cambiar la frecuencia edita el SCHEDULE del ROOT.
-- Para ejecutar manualmente: EXECUTE TASK CONFORMED.TASK_CONFORMED_ROOT;
-- Para ejecutar una sola dimension: EXECUTE TASK CONFORMED.TASK_DIM_MEDICO;
-- ============================================================

CREATE OR REPLACE TASK CONFORMED.TASK_CONFORMED_ROOT
    WAREHOUSE = COMPUTE_WH
    SCHEDULE  = 'USING CRON 0 3 * * * UTC'
AS
    SELECT 'Inicio carga CONFORMED';

-- Dimensiones (se ejecutan en paralelo tras ROOT)
CREATE OR REPLACE TASK CONFORMED.TASK_DIM_FECHA
    WAREHOUSE = COMPUTE_WH
    AFTER CONFORMED.TASK_CONFORMED_ROOT
AS
    CALL CONFORMED.SP_LOAD_DIM_FECHA();

CREATE OR REPLACE TASK CONFORMED.TASK_DIM_DEPARTAMENTO
    WAREHOUSE = COMPUTE_WH
    AFTER CONFORMED.TASK_CONFORMED_ROOT
AS
    CALL CONFORMED.SP_LOAD_DIM_DEPARTAMENTO();

CREATE OR REPLACE TASK CONFORMED.TASK_DIM_UBICACION
    WAREHOUSE = COMPUTE_WH
    AFTER CONFORMED.TASK_CONFORMED_ROOT
AS
    CALL CONFORMED.SP_LOAD_DIM_UBICACION();

CREATE OR REPLACE TASK CONFORMED.TASK_DIM_FABRICANTE
    WAREHOUSE = COMPUTE_WH
    AFTER CONFORMED.TASK_CONFORMED_ROOT
AS
    CALL CONFORMED.SP_LOAD_DIM_FABRICANTE();

CREATE OR REPLACE TASK CONFORMED.TASK_DIM_MEDICO
    WAREHOUSE = COMPUTE_WH
    AFTER CONFORMED.TASK_CONFORMED_ROOT
AS
    CALL CONFORMED.SP_LOAD_DIM_MEDICO();

CREATE OR REPLACE TASK CONFORMED.TASK_DIM_TECNICO
    WAREHOUSE = COMPUTE_WH
    AFTER CONFORMED.TASK_CONFORMED_ROOT
AS
    CALL CONFORMED.SP_LOAD_DIM_TECNICO();

CREATE OR REPLACE TASK CONFORMED.TASK_DIM_PACIENTE
    WAREHOUSE = COMPUTE_WH
    AFTER CONFORMED.TASK_CONFORMED_ROOT
AS
    CALL CONFORMED.SP_LOAD_DIM_PACIENTE();

CREATE OR REPLACE TASK CONFORMED.TASK_DIM_EQUIPO
    WAREHOUSE = COMPUTE_WH
    AFTER CONFORMED.TASK_CONFORMED_ROOT
AS
    CALL CONFORMED.SP_LOAD_DIM_EQUIPO();

CREATE OR REPLACE TASK CONFORMED.TASK_DIM_ENSAYO
    WAREHOUSE = COMPUTE_WH
    AFTER CONFORMED.TASK_CONFORMED_ROOT
AS
    CALL CONFORMED.SP_LOAD_DIM_ENSAYO();

CREATE OR REPLACE TASK CONFORMED.TASK_DIM_DIAGNOSTICO
    WAREHOUSE = COMPUTE_WH
    AFTER CONFORMED.TASK_CONFORMED_ROOT
AS
    CALL CONFORMED.SP_LOAD_DIM_DIAGNOSTICO();

CREATE OR REPLACE TASK CONFORMED.TASK_DIM_PERFIL_MANTENIMIENTO
    WAREHOUSE = COMPUTE_WH
    AFTER CONFORMED.TASK_CONFORMED_ROOT
AS
    CALL CONFORMED.SP_LOAD_DIM_PERFIL_MANTENIMIENTO();

CREATE OR REPLACE TASK CONFORMED.TASK_DIM_PERFIL_ENSAYO
    WAREHOUSE = COMPUTE_WH
    AFTER CONFORMED.TASK_CONFORMED_ROOT
AS
    CALL CONFORMED.SP_LOAD_DIM_PERFIL_ENSAYO();

-- Hechos (se ejecutan en paralelo, tras completarse TODAS las dimensiones)
CREATE OR REPLACE TASK CONFORMED.TASK_FACT_MANTENIMIENTO_EQUIPOS
    WAREHOUSE = COMPUTE_WH
    AFTER CONFORMED.TASK_DIM_FECHA,
          CONFORMED.TASK_DIM_DEPARTAMENTO,
          CONFORMED.TASK_DIM_UBICACION,
          CONFORMED.TASK_DIM_FABRICANTE,
          CONFORMED.TASK_DIM_MEDICO,
          CONFORMED.TASK_DIM_TECNICO,
          CONFORMED.TASK_DIM_PACIENTE,
          CONFORMED.TASK_DIM_EQUIPO,
          CONFORMED.TASK_DIM_ENSAYO,
          CONFORMED.TASK_DIM_DIAGNOSTICO,
          CONFORMED.TASK_DIM_PERFIL_MANTENIMIENTO,
          CONFORMED.TASK_DIM_PERFIL_ENSAYO
AS
    CALL CONFORMED.SP_LOAD_FACT_MANTENIMIENTO_EQUIPOS();

CREATE OR REPLACE TASK CONFORMED.TASK_FACT_MONITORIZACION_PACIENTES
    WAREHOUSE = COMPUTE_WH
    AFTER CONFORMED.TASK_DIM_FECHA,
          CONFORMED.TASK_DIM_DEPARTAMENTO,
          CONFORMED.TASK_DIM_UBICACION,
          CONFORMED.TASK_DIM_FABRICANTE,
          CONFORMED.TASK_DIM_MEDICO,
          CONFORMED.TASK_DIM_TECNICO,
          CONFORMED.TASK_DIM_PACIENTE,
          CONFORMED.TASK_DIM_EQUIPO,
          CONFORMED.TASK_DIM_ENSAYO,
          CONFORMED.TASK_DIM_DIAGNOSTICO,
          CONFORMED.TASK_DIM_PERFIL_MANTENIMIENTO,
          CONFORMED.TASK_DIM_PERFIL_ENSAYO
AS
    CALL CONFORMED.SP_LOAD_FACT_MONITORIZACION_PACIENTES();

CREATE OR REPLACE TASK CONFORMED.TASK_FACT_ENSAYOS_CLINICOS
    WAREHOUSE = COMPUTE_WH
    AFTER CONFORMED.TASK_DIM_FECHA,
          CONFORMED.TASK_DIM_DEPARTAMENTO,
          CONFORMED.TASK_DIM_UBICACION,
          CONFORMED.TASK_DIM_FABRICANTE,
          CONFORMED.TASK_DIM_MEDICO,
          CONFORMED.TASK_DIM_TECNICO,
          CONFORMED.TASK_DIM_PACIENTE,
          CONFORMED.TASK_DIM_EQUIPO,
          CONFORMED.TASK_DIM_ENSAYO,
          CONFORMED.TASK_DIM_DIAGNOSTICO,
          CONFORMED.TASK_DIM_PERFIL_MANTENIMIENTO,
          CONFORMED.TASK_DIM_PERFIL_ENSAYO
AS
    CALL CONFORMED.SP_LOAD_FACT_ENSAYOS_CLINICOS();


-- ============================================================
-- ACTIVAR EL DAG
-- Las tasks hijas deben resumirse antes que la raiz
-- ============================================================
ALTER TASK CONFORMED.TASK_DIM_FECHA                     RESUME;
ALTER TASK CONFORMED.TASK_DIM_DEPARTAMENTO              RESUME;
ALTER TASK CONFORMED.TASK_DIM_UBICACION                 RESUME;
ALTER TASK CONFORMED.TASK_DIM_FABRICANTE                RESUME;
ALTER TASK CONFORMED.TASK_DIM_MEDICO                    RESUME;
ALTER TASK CONFORMED.TASK_DIM_TECNICO                   RESUME;
ALTER TASK CONFORMED.TASK_DIM_PACIENTE                  RESUME;
ALTER TASK CONFORMED.TASK_DIM_EQUIPO                    RESUME;
ALTER TASK CONFORMED.TASK_DIM_ENSAYO                    RESUME;
ALTER TASK CONFORMED.TASK_DIM_DIAGNOSTICO               RESUME;
ALTER TASK CONFORMED.TASK_DIM_PERFIL_MANTENIMIENTO      RESUME;
ALTER TASK CONFORMED.TASK_DIM_PERFIL_ENSAYO             RESUME;
ALTER TASK CONFORMED.TASK_FACT_MANTENIMIENTO_EQUIPOS    RESUME;
ALTER TASK CONFORMED.TASK_FACT_MONITORIZACION_PACIENTES RESUME;
ALTER TASK CONFORMED.TASK_FACT_ENSAYOS_CLINICOS         RESUME;
ALTER TASK CONFORMED.TASK_CONFORMED_ROOT                RESUME;
