-- fact_ensayos_clinicos.sql
-- Tabla de hechos de ensayos clinicos con granularidad diaria
-- Granularidad: UNA FILA POR PACIENTE/ENSAYO/DIA
--   Se expande cada participacion al rango FECHA_INICIO_PARTICIPACION → FECHA_FIN_PARTICIPACION.
--   LEFT JOIN a VISITAS_ENSAYO para incluir medidas del dia si hubo visita (NULL si no la hubo).
-- Fuentes principales:
--   CLEANSED.PARTICIPACION_ENSAYOS  (claves de participacion y atributos junk)
--   CLEANSED.VISITAS_ENSAYO         (medidas: dosis, efectos adversos, resultados)
--   CLEANSED.ENSAYOS_CLINICOS       (CODIGO_DEPARTAMENTO para resolver SK_DEPARTAMENTO)
--
-- Nota de nomenclatura:
--   ID_PARTICIPACION       → dimension degenerada (identifica la participacion del paciente en el ensayo)
--   FECHA expansion        → SK_FECHA  (cada dia dentro del rango de participacion)
--   ID_MEDICO_ASIGNADO     → SK_MEDICO
--   FASE                   → FASE_ENSAYO  (atributo junk dimension, codigos CLEANSED: F1/F2/F3/F4)
--   GRUPO_ASIGNADO         → GRUPO_TRATAMIENTO (atributo junk dimension, codigos: EXP/CTR/PLA)
--   SK_DEPARTAMENTO        → resuelto via ENSAYOS_CLINICOS.CODIGO_DEPARTAMENTO → DEPARTAMENTOS


CREATE SCHEMA IF NOT EXISTS CONFORMED;

CREATE TABLE IF NOT EXISTS CONFORMED.FACT_ENSAYOS_CLINICOS (
    SK_ENSAYO_CLINICO              NUMBER    NOT NULL AUTOINCREMENT PRIMARY KEY,
    -- Claves foraneas
    SK_FECHA                       NUMBER    NOT NULL,  -- FK → DIM_FECHA (dia del rango de participacion)
    SK_FECHA_INICIO                NUMBER    NOT NULL,  -- FK → DIM_FECHA (inicio participacion)
    SK_FECHA_FIN                   NUMBER,              -- FK → DIM_FECHA (fin participacion, NULL si sigue activa)
    SK_ENSAYO                      NUMBER    NOT NULL,  -- FK → DIM_ENSAYO
    SK_PACIENTE                    NUMBER    NOT NULL,  -- FK → DIM_PACIENTE
    SK_MEDICO                      NUMBER    NOT NULL,  -- FK → DIM_MEDICO
    SK_DIAGNOSTICO                 NUMBER    NOT NULL,  -- FK → DIM_DIAGNOSTICO
    SK_DEPARTAMENTO                NUMBER    NOT NULL,  -- FK → DIM_DEPARTAMENTO
    SK_PERFIL_ENSAYO               NUMBER    NOT NULL,  -- FK → DIM_PERFIL_ENSAYO
    -- Dimension degenerada
    ID_PARTICIPACION               NUMBER    NOT NULL,
    -- Medidas (NULL cuando no hay visita registrada ese dia)
    DOSIS_ADMINISTRADA             NUMBER(10,4),
    UNIDAD_DOSIS                   VARCHAR(10),
    NUMERO_EFECTOS_ADVERSOS        NUMBER,
    RESULTADO_MEDICION_PRINCIPAL   NUMBER(8,4),
    RESULTADO_MEDICION_SECUNDARIA  NUMBER(8,4),
    NIVEL_EFICACIA                 NUMBER(5,4)
);


-- Restricciones de clave foranea (informativas en Snowflake, utiles para BI tools)
ALTER TABLE CONFORMED.FACT_ENSAYOS_CLINICOS
    ADD CONSTRAINT FK_ENS_FECHA        FOREIGN KEY (SK_FECHA)         REFERENCES CONFORMED.DIM_FECHA(SK_FECHA);
ALTER TABLE CONFORMED.FACT_ENSAYOS_CLINICOS
    ADD CONSTRAINT FK_ENS_FECHA_INI    FOREIGN KEY (SK_FECHA_INICIO)  REFERENCES CONFORMED.DIM_FECHA(SK_FECHA);
ALTER TABLE CONFORMED.FACT_ENSAYOS_CLINICOS
    ADD CONSTRAINT FK_ENS_FECHA_FIN    FOREIGN KEY (SK_FECHA_FIN)     REFERENCES CONFORMED.DIM_FECHA(SK_FECHA);
ALTER TABLE CONFORMED.FACT_ENSAYOS_CLINICOS
    ADD CONSTRAINT FK_ENS_ENSAYO       FOREIGN KEY (SK_ENSAYO)        REFERENCES CONFORMED.DIM_ENSAYO(SK_ENSAYO);
ALTER TABLE CONFORMED.FACT_ENSAYOS_CLINICOS
    ADD CONSTRAINT FK_ENS_PACIENTE     FOREIGN KEY (SK_PACIENTE)      REFERENCES CONFORMED.DIM_PACIENTE(SK_PACIENTE);
ALTER TABLE CONFORMED.FACT_ENSAYOS_CLINICOS
    ADD CONSTRAINT FK_ENS_MEDICO       FOREIGN KEY (SK_MEDICO)        REFERENCES CONFORMED.DIM_MEDICO(SK_MEDICO);
ALTER TABLE CONFORMED.FACT_ENSAYOS_CLINICOS
    ADD CONSTRAINT FK_ENS_DIAG         FOREIGN KEY (SK_DIAGNOSTICO)   REFERENCES CONFORMED.DIM_DIAGNOSTICO(SK_DIAGNOSTICO);
ALTER TABLE CONFORMED.FACT_ENSAYOS_CLINICOS
    ADD CONSTRAINT FK_ENS_DEPTO        FOREIGN KEY (SK_DEPARTAMENTO)  REFERENCES CONFORMED.DIM_DEPARTAMENTO(SK_DEPARTAMENTO);
ALTER TABLE CONFORMED.FACT_ENSAYOS_CLINICOS
    ADD CONSTRAINT FK_ENS_PERFIL       FOREIGN KEY (SK_PERFIL_ENSAYO) REFERENCES CONFORMED.DIM_PERFIL_ENSAYO(SK_PERFIL_ENSAYO);


-- ============================================================
-- INSERT — expandir participaciones a 1 fila por dia
-- ============================================================
INSERT INTO CONFORMED.FACT_ENSAYOS_CLINICOS (
    SK_FECHA, SK_FECHA_INICIO, SK_FECHA_FIN,
    SK_ENSAYO, SK_PACIENTE, SK_MEDICO, SK_DIAGNOSTICO,
    SK_DEPARTAMENTO, SK_PERFIL_ENSAYO, ID_PARTICIPACION,
    DOSIS_ADMINISTRADA, UNIDAD_DOSIS, NUMERO_EFECTOS_ADVERSOS,
    RESULTADO_MEDICION_PRINCIPAL, RESULTADO_MEDICION_SECUNDARIA, NIVEL_EFICACIA
)
SELECT
    TO_NUMBER(TO_CHAR(DATEADD('day', dias.n, p.FECHA_INICIO_PARTICIPACION), 'YYYYMMDD')) AS SK_FECHA,
    TO_NUMBER(TO_CHAR(p.FECHA_INICIO_PARTICIPACION, 'YYYYMMDD'))                         AS SK_FECHA_INICIO,
    TO_NUMBER(TO_CHAR(p.FECHA_FIN_PARTICIPACION,    'YYYYMMDD'))                         AS SK_FECHA_FIN,
    en.SK_ENSAYO, pa.SK_PACIENTE, me.SK_MEDICO, di.SK_DIAGNOSTICO,
    dp.SK_DEPARTAMENTO, pe.SK_PERFIL_ENSAYO,
    p.ID_PARTICIPACION,
    v.DOSIS_ADMINISTRADA, v.UNIDAD_DOSIS,
    v.NUMERO_EFECTOS_ADVERSOS, v.RESULTADO_MEDICION_PRINCIPAL,
    v.RESULTADO_MEDICION_SECUNDARIA, v.NIVEL_EFICACIA
FROM CLEANSED.PARTICIPACION_ENSAYOS p
JOIN (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 AS n
      FROM TABLE(GENERATOR(ROWCOUNT => 3650))) dias
JOIN CLEANSED.ENSAYOS_CLINICOS       ec     ON ec.ID_ENSAYO               = p.ID_ENSAYO
JOIN CLEANSED.DEPARTAMENTOS          dep_src ON dep_src.CODIGO_DEPARTAMENTO = ec.CODIGO_DEPARTAMENTO
JOIN CONFORMED.DIM_ENSAYO        en ON en.ID_ENSAYO        = p.ID_ENSAYO
JOIN CONFORMED.DIM_PACIENTE      pa ON pa.ID_PACIENTE       = p.ID_PACIENTE          AND pa.ES_ACTUAL = TRUE
JOIN CONFORMED.DIM_MEDICO        me ON me.ID_MEDICO         = p.ID_MEDICO_ASIGNADO   AND me.ES_ACTUAL = TRUE
JOIN CONFORMED.DIM_DIAGNOSTICO   di ON di.ID_DIAGNOSTICO    = p.ID_DIAGNOSTICO
JOIN CONFORMED.DIM_DEPARTAMENTO  dp ON dp.ID_DEPARTAMENTO   = dep_src.ID_DEPARTAMENTO
JOIN CONFORMED.DIM_PERFIL_ENSAYO pe
    ON  pe.FASE_ENSAYO         = CASE p.FASE
                                     WHEN 'F1' THEN 'Fase I'   WHEN 'F2' THEN 'Fase II'
                                     WHEN 'F3' THEN 'Fase III' WHEN 'F4' THEN 'Fase IV' END
    AND pe.TIPO_CIEGO          = CASE p.TIPO_CIEGO
                                     WHEN 'AB' THEN 'Abierto'
                                     WHEN 'SC' THEN 'Simple Ciego'
                                     WHEN 'DC' THEN 'Doble Ciego' END
    AND pe.TIPO_ALEATORIZACION = CASE p.TIPO_ALEATORIZACION
                                     WHEN 'AL' THEN 'Aleatorizado'
                                     WHEN 'NA' THEN 'No Aleatorizado' END
    AND pe.GRUPO_TRATAMIENTO   = CASE p.GRUPO_ASIGNADO
                                     WHEN 'EXP' THEN 'Experimental'
                                     WHEN 'CTR' THEN 'Control'
                                     WHEN 'PLA' THEN 'Placebo' END
    AND pe.VIA_ADMINISTRACION  = CASE p.VIA_ADMINISTRACION
                                     WHEN 'ORL' THEN 'Oral'
                                     WHEN 'IV'  THEN 'Intravenosa'
                                     WHEN 'SC'  THEN 'Subcutanea'
                                     WHEN 'TOP' THEN 'Topica'
                                     WHEN 'INH' THEN 'Inhalatoria' END
LEFT JOIN CLEANSED.VISITAS_ENSAYO v
       ON v.ID_PARTICIPACION = p.ID_PARTICIPACION
      AND CAST(v.FECHA_VISITA AS DATE) = DATEADD('day', dias.n, p.FECHA_INICIO_PARTICIPACION)
WHERE DATEADD('day', dias.n, p.FECHA_INICIO_PARTICIPACION)
          <= COALESCE(p.FECHA_FIN_PARTICIPACION, CURRENT_DATE)
  AND NOT EXISTS (
          SELECT 1 FROM CONFORMED.FACT_ENSAYOS_CLINICOS
          WHERE  ID_PARTICIPACION = p.ID_PARTICIPACION
            AND  SK_FECHA = TO_NUMBER(TO_CHAR(DATEADD('day', dias.n, p.FECHA_INICIO_PARTICIPACION), 'YYYYMMDD'))
      );
