-- fact_monitorizacion_pacientes.sql
-- Tabla de hechos de monitorizacion de pacientes
-- Granularidad: una fila por sesion de monitorizacion
-- Fuentes principales:
--   CLEANSED_MEDICARE.MONITORIZACIONES        (claves y fechas)
--   CLEANSED_MEDICARE.LECTURAS_SIGNOS_VITALES (signos vitales, AVG por sesion)
--
-- Nota de nomenclatura:
--   ID_MONITORIZACION  → ID_SESION (dimension degenerada)
--   FECHA_MONITORIZACION → SK_FECHA
--   CODIGO_EQUIPO      → JOIN a EQUIPOS para resolver ID_EQUIPO
--   CODIGO_DEPARTAMENTO→ JOIN a DEPARTAMENTOS para resolver ID_DEPARTAMENTO
--   CODIGO_UBICACION   → JOIN a UBICACIONES para resolver ID_UBICACION
--   DURACION_MONITORIZACION_MIN: calculado de HORA_INICIO y HORA_FIN
--   Signos vitales: media (AVG) de LECTURAS_SIGNOS_VITALES por ID_MONITORIZACION
--   ALERTA_GENERADA: calculada segun rangos clinicos sobre los valores promedio


CREATE SCHEMA IF NOT EXISTS CONFORMED;

CREATE TABLE IF NOT EXISTS CONFORMED.FACT_MONITORIZACION_PACIENTES (
    SK_MONITORIZACION           NUMBER    NOT NULL AUTOINCREMENT PRIMARY KEY,
    -- Claves foraneas
    SK_FECHA                    NUMBER    NOT NULL,  -- FK → DIM_FECHA
    SK_PACIENTE                 NUMBER    NOT NULL,  -- FK → DIM_PACIENTE
    SK_MEDICO                   NUMBER    NOT NULL,  -- FK → DIM_MEDICO
    SK_EQUIPO                   NUMBER    NOT NULL,  -- FK → DIM_EQUIPO
    SK_DEPARTAMENTO             NUMBER    NOT NULL,  -- FK → DIM_DEPARTAMENTO
    SK_UBICACION                NUMBER    NOT NULL,  -- FK → DIM_UBICACION
    SK_DIAGNOSTICO              NUMBER    NOT NULL,  -- FK → DIM_DIAGNOSTICO
    -- Dimension degenerada
    ID_SESION                   NUMBER    NOT NULL,
    -- Medidas aditivas
    DURACION_MONITORIZACION_MIN NUMBER,
    -- Medidas semi-aditivas (no sumar entre sesiones, usar AVG)
    FRECUENCIA_CARDIACA         NUMBER(6,2),
    PRESION_SISTOLICA           NUMBER(6,2),
    PRESION_DIASTOLICA          NUMBER(6,2),
    TEMPERATURA                 NUMBER(5,2),
    SATURACION_OXIGENO          NUMBER(5,2),
    NIVEL_GLUCOSA               NUMBER(8,2),
    ALERTA_GENERADA             BOOLEAN   NOT NULL DEFAULT FALSE
);


-- Restricciones de clave foranea (informativas en Snowflake, utiles para BI tools)
ALTER TABLE CONFORMED.FACT_MONITORIZACION_PACIENTES
    ADD CONSTRAINT FK_MON_FECHA    FOREIGN KEY (SK_FECHA)        REFERENCES CONFORMED.DIM_FECHA(SK_FECHA);
ALTER TABLE CONFORMED.FACT_MONITORIZACION_PACIENTES
    ADD CONSTRAINT FK_MON_PACIENTE FOREIGN KEY (SK_PACIENTE)     REFERENCES CONFORMED.DIM_PACIENTE(SK_PACIENTE);
ALTER TABLE CONFORMED.FACT_MONITORIZACION_PACIENTES
    ADD CONSTRAINT FK_MON_MEDICO   FOREIGN KEY (SK_MEDICO)       REFERENCES CONFORMED.DIM_MEDICO(SK_MEDICO);
ALTER TABLE CONFORMED.FACT_MONITORIZACION_PACIENTES
    ADD CONSTRAINT FK_MON_EQUIPO   FOREIGN KEY (SK_EQUIPO)       REFERENCES CONFORMED.DIM_EQUIPO(SK_EQUIPO);
ALTER TABLE CONFORMED.FACT_MONITORIZACION_PACIENTES
    ADD CONSTRAINT FK_MON_DEPTO    FOREIGN KEY (SK_DEPARTAMENTO) REFERENCES CONFORMED.DIM_DEPARTAMENTO(SK_DEPARTAMENTO);
ALTER TABLE CONFORMED.FACT_MONITORIZACION_PACIENTES
    ADD CONSTRAINT FK_MON_UBIC     FOREIGN KEY (SK_UBICACION)    REFERENCES CONFORMED.DIM_UBICACION(SK_UBICACION);
ALTER TABLE CONFORMED.FACT_MONITORIZACION_PACIENTES
    ADD CONSTRAINT FK_MON_DIAG     FOREIGN KEY (SK_DIAGNOSTICO)  REFERENCES CONFORMED.DIM_DIAGNOSTICO(SK_DIAGNOSTICO);


-- ============================================================
-- INSERT — cargar sesiones de monitorizacion nuevas
-- ============================================================
INSERT INTO CONFORMED.FACT_MONITORIZACION_PACIENTES (
    SK_FECHA, SK_PACIENTE, SK_MEDICO, SK_EQUIPO,
    SK_DEPARTAMENTO, SK_UBICACION, SK_DIAGNOSTICO, ID_SESION,
    DURACION_MONITORIZACION_MIN,
    FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA,
    TEMPERATURA, SATURACION_OXIGENO, NIVEL_GLUCOSA, ALERTA_GENERADA
)
SELECT
    TO_NUMBER(TO_CHAR(m.FECHA_MONITORIZACION, 'YYYYMMDD'))  AS SK_FECHA,
    pa.SK_PACIENTE,
    me.SK_MEDICO,
    eq.SK_EQUIPO,
    dp.SK_DEPARTAMENTO,
    ub.SK_UBICACION,
    di.SK_DIAGNOSTICO,
    m.ID_MONITORIZACION                                     AS ID_SESION,
    DATEDIFF(MINUTE, m.HORA_INICIO, m.HORA_FIN)            AS DURACION_MONITORIZACION_MIN,
    lsv.FRECUENCIA_CARDIACA,
    lsv.PRESION_SISTOLICA,
    lsv.PRESION_DIASTOLICA,
    lsv.TEMPERATURA,
    lsv.SATURACION_OXIGENO,
    lsv.NIVEL_GLUCOSA,
    CASE WHEN
        lsv.FRECUENCIA_CARDIACA < 60   OR lsv.FRECUENCIA_CARDIACA > 100  OR
        lsv.PRESION_SISTOLICA   < 90   OR lsv.PRESION_SISTOLICA   > 140  OR
        lsv.PRESION_DIASTOLICA  < 60   OR lsv.PRESION_DIASTOLICA  > 90   OR
        lsv.TEMPERATURA         < 36.0 OR lsv.TEMPERATURA         > 37.5 OR
        lsv.SATURACION_OXIGENO  < 95                                      OR
        lsv.NIVEL_GLUCOSA       < 70   OR lsv.NIVEL_GLUCOSA       > 140
    THEN TRUE ELSE FALSE END                                AS ALERTA_GENERADA
FROM CLEANSED_MEDICARE.MONITORIZACIONES m
-- Signos vitales promediados por sesion desde LECTURAS_SIGNOS_VITALES
JOIN (
    SELECT
        ID_MONITORIZACION,
        AVG(FRECUENCIA_CARDIACA)  AS FRECUENCIA_CARDIACA,
        AVG(PRESION_SISTOLICA)    AS PRESION_SISTOLICA,
        AVG(PRESION_DIASTOLICA)   AS PRESION_DIASTOLICA,
        AVG(TEMPERATURA)          AS TEMPERATURA,
        AVG(SATURACION_OXIGENO)   AS SATURACION_OXIGENO,
        AVG(NIVEL_GLUCOSA)        AS NIVEL_GLUCOSA
    FROM CLEANSED_MEDICARE.LECTURAS_SIGNOS_VITALES
    GROUP BY ID_MONITORIZACION
) lsv ON lsv.ID_MONITORIZACION = m.ID_MONITORIZACION
-- Resolver codigos a IDs para los JOINs a dimensiones
JOIN CLEANSED_MEDICARE.EQUIPOS      eq_src ON eq_src.CODIGO_EQUIPO      = m.CODIGO_EQUIPO
JOIN CLEANSED_MEDICARE.DEPARTAMENTOS dp_src ON dp_src.CODIGO_DEPARTAMENTO = m.CODIGO_DEPARTAMENTO
JOIN CLEANSED_MEDICARE.UBICACIONES  ub_src ON ub_src.CODIGO_UBICACION   = m.CODIGO_UBICACION
-- Dimensiones conformed
JOIN CONFORMED.DIM_PACIENTE     pa ON pa.ID_PACIENTE     = m.ID_PACIENTE     AND pa.ES_ACTUAL = TRUE
JOIN CONFORMED.DIM_MEDICO       me ON me.ID_MEDICO       = m.ID_MEDICO       AND me.ES_ACTUAL = TRUE
JOIN CONFORMED.DIM_EQUIPO       eq ON eq.ID_EQUIPO       = eq_src.ID_EQUIPO  AND eq.ES_ACTUAL = TRUE
JOIN CONFORMED.DIM_DEPARTAMENTO dp ON dp.ID_DEPARTAMENTO = dp_src.ID_DEPARTAMENTO
JOIN CONFORMED.DIM_UBICACION    ub ON ub.ID_UBICACION    = ub_src.ID_UBICACION
JOIN CONFORMED.DIM_DIAGNOSTICO  di ON di.ID_DIAGNOSTICO  = m.ID_DIAGNOSTICO
WHERE NOT EXISTS (
    SELECT ID_SESION FROM CONFORMED.FACT_MONITORIZACION_PACIENTES
    WHERE ID_SESION = m.ID_MONITORIZACION
);
