-- fact_mantenimiento_equipos.sql
-- Tabla de hechos de mantenimiento de equipos biomedicos
-- Granularidad: una fila por orden de mantenimiento
-- Fuentes principales:
--   CLEANSED_MEDICARE.ORDENES_MANTENIMIENTO  (hechos y claves)
--   CLEANSED_MEDICARE.EQUIPOS                (ID_DEPARTAMENTO, ID_UBICACION, ID_FABRICANTE)
--   CLEANSED_MEDICARE.TECNICOS               (TARIFA_HORA)
--   CLEANSED_MEDICARE.CONSUMO_REPUESTOS      (COSTO_REPUESTOS, NUMERO_PIEZAS_REEMPLAZADAS)
--
-- Nota de nomenclatura:
--   FECHA_INICIO_TRABAJO             → SK_FECHA (cast a DATE)
--   ES_CUBIERTO_POR_GARANTIA         → ES_GARANTIA en junk dimension
--   REQUIERE_PARADA                  → REQUIERE_PARADA_EQUIPO en junk dimension
--   PRIORIDAD (NUMBER): 1=Baja, 2=Media, 3=Alta, 4=Critica
--   GRAVEDAD  (NUMBER): 1=Leve, 2=Moderada, 3=Grave
--   DURACION_HORAS: calculado de FECHA_INICIO_TRABAJO y FECHA_FIN_TRABAJO
--   COSTO_REPUESTOS: SUM(CANTIDAD * PRECIO_UNITARIO_EN_MOMENTO) en CONSUMO_REPUESTOS
--   NUMERO_PIEZAS_REEMPLAZADAS: SUM(CANTIDAD) en CONSUMO_REPUESTOS
--   COSTO_MANO_OBRA: HORAS_TRABAJADAS * TARIFA_HORA (TARIFA_HORA viene de TECNICOS)
--   COSTO_TOTAL: COSTO_REPUESTOS + COSTO_MANO_OBRA


CREATE SCHEMA IF NOT EXISTS CONFORMED;

CREATE TABLE IF NOT EXISTS CONFORMED.FACT_MANTENIMIENTO_EQUIPOS (
    SK_MANTENIMIENTO           NUMBER    NOT NULL AUTOINCREMENT PRIMARY KEY,
    -- Claves foraneas
    SK_FECHA                   NUMBER    NOT NULL,  -- FK → DIM_FECHA
    SK_EQUIPO                  NUMBER    NOT NULL,  -- FK → DIM_EQUIPO
    SK_TECNICO                 NUMBER    NOT NULL,  -- FK → DIM_TECNICO
    SK_DEPARTAMENTO            NUMBER    NOT NULL,  -- FK → DIM_DEPARTAMENTO
    SK_UBICACION               NUMBER    NOT NULL,  -- FK → DIM_UBICACION
    SK_FABRICANTE              NUMBER    NOT NULL,  -- FK → DIM_FABRICANTE
    SK_PERFIL_MANTENIMIENTO    NUMBER    NOT NULL,  -- FK → DIM_PERFIL_MANTENIMIENTO
    -- Dimension degenerada
    ID_ORDEN                   NUMBER    NOT NULL,
    -- Medidas aditivas
    HORAS_TRABAJADAS           NUMBER(8,2),
    TARIFA_HORA                NUMBER(10,2),
    COSTO_REPUESTOS            NUMBER(12,2),
    COSTO_MANO_OBRA            NUMBER(12,2),        -- HORAS_TRABAJADAS * TARIFA_HORA
    COSTO_TOTAL                NUMBER(12,2),        -- COSTO_REPUESTOS + COSTO_MANO_OBRA
    DURACION_HORAS             NUMBER(8,2),         -- calculado de FECHA_INICIO/FIN_TRABAJO
    NUMERO_PIEZAS_REEMPLAZADAS NUMBER,
    -- Medida semi-aditiva
    INDICADOR_REINCIDENCIA     BOOLEAN   NOT NULL DEFAULT FALSE
);


-- Restricciones de clave foranea (informativas en Snowflake, utiles para BI tools)
ALTER TABLE CONFORMED.FACT_MANTENIMIENTO_EQUIPOS
    ADD CONSTRAINT FK_MANT_FECHA    FOREIGN KEY (SK_FECHA)                REFERENCES CONFORMED.DIM_FECHA(SK_FECHA);
ALTER TABLE CONFORMED.FACT_MANTENIMIENTO_EQUIPOS
    ADD CONSTRAINT FK_MANT_EQUIPO   FOREIGN KEY (SK_EQUIPO)               REFERENCES CONFORMED.DIM_EQUIPO(SK_EQUIPO);
ALTER TABLE CONFORMED.FACT_MANTENIMIENTO_EQUIPOS
    ADD CONSTRAINT FK_MANT_TECNICO  FOREIGN KEY (SK_TECNICO)              REFERENCES CONFORMED.DIM_TECNICO(SK_TECNICO);
ALTER TABLE CONFORMED.FACT_MANTENIMIENTO_EQUIPOS
    ADD CONSTRAINT FK_MANT_DEPTO    FOREIGN KEY (SK_DEPARTAMENTO)         REFERENCES CONFORMED.DIM_DEPARTAMENTO(SK_DEPARTAMENTO);
ALTER TABLE CONFORMED.FACT_MANTENIMIENTO_EQUIPOS
    ADD CONSTRAINT FK_MANT_UBIC     FOREIGN KEY (SK_UBICACION)            REFERENCES CONFORMED.DIM_UBICACION(SK_UBICACION);
ALTER TABLE CONFORMED.FACT_MANTENIMIENTO_EQUIPOS
    ADD CONSTRAINT FK_MANT_FABRIC   FOREIGN KEY (SK_FABRICANTE)           REFERENCES CONFORMED.DIM_FABRICANTE(SK_FABRICANTE);
ALTER TABLE CONFORMED.FACT_MANTENIMIENTO_EQUIPOS
    ADD CONSTRAINT FK_MANT_PERFIL   FOREIGN KEY (SK_PERFIL_MANTENIMIENTO) REFERENCES CONFORMED.DIM_PERFIL_MANTENIMIENTO(SK_PERFIL_MANTENIMIENTO);


-- ============================================================
-- INSERT — cargar ordenes de mantenimiento nuevas
-- ============================================================
INSERT INTO CONFORMED.FACT_MANTENIMIENTO_EQUIPOS (
    SK_FECHA, SK_EQUIPO, SK_TECNICO, SK_DEPARTAMENTO, SK_UBICACION,
    SK_FABRICANTE, SK_PERFIL_MANTENIMIENTO, ID_ORDEN,
    HORAS_TRABAJADAS, TARIFA_HORA, COSTO_REPUESTOS,
    COSTO_MANO_OBRA, COSTO_TOTAL,
    DURACION_HORAS, NUMERO_PIEZAS_REEMPLAZADAS, INDICADOR_REINCIDENCIA
)
SELECT
    TO_NUMBER(TO_CHAR(CAST(o.FECHA_INICIO_TRABAJO AS DATE), 'YYYYMMDD'))   AS SK_FECHA,
    eq.SK_EQUIPO,
    tc.SK_TECNICO,
    dp.SK_DEPARTAMENTO,
    ub.SK_UBICACION,
    fa.SK_FABRICANTE,
    pm.SK_PERFIL_MANTENIMIENTO,
    o.ID_ORDEN,
    o.HORAS_TRABAJADAS,
    tc_src.TARIFA_HORA,
    cr.COSTO_REPUESTOS,
    o.HORAS_TRABAJADAS * tc_src.TARIFA_HORA                                AS COSTO_MANO_OBRA,
    COALESCE(cr.COSTO_REPUESTOS, 0) + (o.HORAS_TRABAJADAS * tc_src.TARIFA_HORA) AS COSTO_TOTAL,
    DATEDIFF(MINUTE, o.FECHA_INICIO_TRABAJO, o.FECHA_FIN_TRABAJO) / 60.0  AS DURACION_HORAS,
    cr.NUMERO_PIEZAS_REEMPLAZADAS,
    CASE WHEN EXISTS (
        SELECT ID_ORDEN
        FROM CLEANSED_MEDICARE.ORDENES_MANTENIMIENTO prev
        WHERE prev.ID_EQUIPO          = o.ID_EQUIPO
          AND prev.TIPO_MANTENIMIENTO = 'Correctivo'
          AND prev.FECHA_INICIO_TRABAJO  < o.FECHA_INICIO_TRABAJO
          AND prev.FECHA_INICIO_TRABAJO >= DATEADD(DAY, -30, o.FECHA_INICIO_TRABAJO)
    ) THEN TRUE ELSE FALSE END                                             AS INDICADOR_REINCIDENCIA
FROM CLEANSED_MEDICARE.ORDENES_MANTENIMIENTO o
-- Fuente de equipos para resolver ID_DEPARTAMENTO, ID_UBICACION, ID_FABRICANTE
JOIN CLEANSED_MEDICARE.EQUIPOS               eq_src ON eq_src.ID_EQUIPO    = o.ID_EQUIPO
-- Fuente de tecnicos para resolver TARIFA_HORA
JOIN CLEANSED_MEDICARE.TECNICOS              tc_src ON tc_src.ID_TECNICO   = o.ID_TECNICO
-- Coste de repuestos y piezas reemplazadas agregados por orden
LEFT JOIN (
    SELECT
        ID_ORDEN,
        SUM(CANTIDAD * PRECIO_UNITARIO_EN_MOMENTO) AS COSTO_REPUESTOS,
        SUM(CANTIDAD)                              AS NUMERO_PIEZAS_REEMPLAZADAS
    FROM CLEANSED_MEDICARE.CONSUMO_REPUESTOS
    GROUP BY ID_ORDEN
) cr ON cr.ID_ORDEN = o.ID_ORDEN
-- Dimensiones conformed
JOIN CONFORMED.DIM_EQUIPO               eq ON eq.ID_EQUIPO        = o.ID_EQUIPO        AND eq.ES_ACTUAL = TRUE
JOIN CONFORMED.DIM_TECNICO              tc ON tc.ID_TECNICO        = o.ID_TECNICO       AND tc.ES_ACTUAL = TRUE
JOIN CONFORMED.DIM_DEPARTAMENTO         dp ON dp.ID_DEPARTAMENTO   = eq_src.ID_DEPARTAMENTO
JOIN CONFORMED.DIM_UBICACION            ub ON ub.ID_UBICACION      = eq_src.ID_UBICACION
JOIN CONFORMED.DIM_FABRICANTE           fa ON fa.ID_FABRICANTE     = eq_src.ID_FABRICANTE
JOIN CONFORMED.DIM_PERFIL_MANTENIMIENTO pm ON pm.TIPO_MANTENIMIENTO    = o.TIPO_MANTENIMIENTO
    AND pm.PRIORIDAD              = CASE o.PRIORIDAD
                                        WHEN 1 THEN 'Baja'
                                        WHEN 2 THEN 'Media'
                                        WHEN 3 THEN 'Alta'
                                        WHEN 4 THEN 'Critica'
                                    END
    AND pm.GRAVEDAD               = CASE o.GRAVEDAD
                                        WHEN 1 THEN 'Leve'
                                        WHEN 2 THEN 'Moderada'
                                        WHEN 3 THEN 'Grave'
                                    END
    AND pm.ES_GARANTIA            = o.ES_CUBIERTO_POR_GARANTIA
    AND pm.REQUIERE_PARADA_EQUIPO = o.REQUIERE_PARADA
WHERE NOT EXISTS (
    SELECT ID_ORDEN FROM CONFORMED.FACT_MANTENIMIENTO_EQUIPOS
    WHERE ID_ORDEN = o.ID_ORDEN
);
