-- [DETECTIVE]
SELECT
    t.TABLE_SCHEMA,
    t.TABLE_NAME,
    c.COLUMN_NAME AS CLAVE_PRIMARIA
FROM INFORMATION_SCHEMA.TABLES t
JOIN INFORMATION_SCHEMA.COLUMNS c
  ON t.TABLE_SCHEMA = c.TABLE_SCHEMA
 AND t.TABLE_NAME = c.TABLE_NAME
WHERE t.TABLE_SCHEMA LIKE 'LANDING_%'
  AND t.TABLE_TYPE = 'BASE TABLE'
  AND NOT STARTSWITH(t.TABLE_NAME, '_DLT')
  AND STARTSWITH(c.COLUMN_NAME, 'ID_')
QUALIFY ROW_NUMBER() OVER (PARTITION BY t.TABLE_NAME ORDER BY c.ORDINAL_POSITION) = 1

-- [COLUMNAS]
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = '{esquema}'
  AND TABLE_NAME   = '{nombre_tabla}'
ORDER BY ORDINAL_POSITION
