--CREACIONES------
CREATE DATABASE PROYECTO;

--CREACION DE LOS ESQUEMAS 
CREATE SCHEMA IF NOT EXISTS PROYECTO.RAW_NEXTBIO;
CREATE SCHEMA IF NOT EXISTS PROYECTO.RAW_PRODUCTOS;
CREATE SCHEMA IF NOT EXISTS PROYECTO.RAW_MEDICARE; 
CREATE SCHEMA IF NOT EXISTS PROYECTO.LANDING_MEDICARE;
CREATE SCHEMA IF NOT EXISTS PROYECTO.LANDING_NEXTBIO;
CREATE SCHEMA IF NOT EXISTS PROYECTO.LANDING_PRODUCTOS; 
CREATE SCHEMA IF NOT EXISTS PROYECTO.CLEANSED_MEDICARE;
CREATE SCHEMA IF NOT EXISTS PROYECTO.CLEANSED_NEXTBIO;
CREATE SCHEMA IF NOT EXISTS PROYECTO.CLEANSED_PRODUCTOS;

CREATE SCHEMA IF NOT EXISTS PROYECTO.STREAMS_Y_TASKS


--BORRAR DATABASE
DROP DATABASE PROYECTO;
--BORRAR ESQUEMAS 
DROP SCHEMA IF EXISTS PROYECTO.RAW_NEXTBIO;
DROP SCHEMA IF EXISTS PROYECTO.RAW_PRODUCTOS;
DROP SCHEMA IF EXISTS PROYECTO.RAW_MEDICARE; 
DROP SCHEMA IF EXISTS PROYECTO.CLEANSED_MEDICARE; 
DROP SCHEMA IF EXISTS PROYECTO.PUBLIC; 

--BORRAR TABLA   
DROP TABLE PROYECTO.CLEANSED_MEDICARE.CATEGORIA_EQUIPOS_ERRORS

--PARA BORRAR UN TASK O STREAM
DROP TASK IF EXISTS PROYECTO.PUBLIC.TASK_LOAD_RAW_CATEGORIA_EQUIPOS;
DROP STREAM IF EXISTS PROYECTO.PUBLIC.TASK_LOAD_RAW_CATEGORIA_EQUIPOS;