
--PRUEBA DE FUNCIONAMIENTO "SIMULAR" QUE PYTHON TRAE UN DATO NUEVO. EJECUTAR EL INSERT EN LA CAPA LANDING. 

INSERT INTO LANDING_MEDICARE.CATEGORIA_EQUIPOS 
  (ID_CATEGORIA, CODIGO_CATEGORIA, NOMBRE_CATEGORIA, FECHA_CREACION, FECHA_MODIFICACION, ID_CARGA, _DLT_LOAD_ID, _DLT_ID) 
VALUES 
  (978, 'CAT_PRUEBA', 'EQUIPO_PRUEBA_STREAM', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 0, 'manual_test', 'manual_test_999');



--prueba de simular meter un dato sucio en la capa RAW, para ver si CLEANSED lo pilla y lo clasifica 
INSERT INTO RAW_MEDICARE.CATEGORIA_EQUIPOS 
  (ID_CATEGORIA, CODIGO_CATEGORIA, NOMBRE_CATEGORIA, FECHA_CREACION, FECHA_MODIFICACION, ID_CARGA, _DLT_LOAD_ID, _DLT_ID)
VALUES 
  (858, 'CAT_ROTA8', NULL, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 0, 'test_error', 'test_error');


  