-- dimension_departamento.sql
-- Dimension SCD1 de departamentos con jerarquia padre-hijo
-- Todos los atributos son SCD1 (sobrescritura en sitio, sin historial)
-- Fuente: CLEANSED.DEPARTAMENTOS
--
-- Nota de nomenclatura:
-- NOMBRE_RESPONSABLE → RESPONSABLE (alias, se mantiene nombre del spec)
-- NIVEL_JERARQUIA    → no existe en la fuente, se calcula con CTE recursiva:
--                      raiz (ID_DEPARTAMENTO_PADRE IS NULL) = nivel 1,
--                      cada nivel de hijo suma 1


CREATE SCHEMA IF NOT EXISTS CONFORMED;

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_DEPARTAMENTO (
    SK_DEPARTAMENTO         NUMBER          NOT NULL AUTOINCREMENT PRIMARY KEY,
    ID_DEPARTAMENTO         NUMBER          NOT NULL,
    NOMBRE_DEPARTAMENTO     VARCHAR(200)    NOT NULL,
    ID_DEPARTAMENTO_PADRE   NUMBER,
    SK_DEPARTAMENTO_PADRE   NUMBER,
    NIVEL_JERARQUIA         NUMBER          NOT NULL,
    RESPONSABLE             VARCHAR(200),
    TELEFONO_DEPARTAMENTO   VARCHAR(50),
    EMAIL_DEPARTAMENTO      VARCHAR(200)
);


-- ============================================================
-- PASO 1: SCD1 — actualizar en sitio cuando cambia cualquier
--         atributo (incluida la referencia al padre)
-- ============================================================
WITH JERARQUIA AS (  -- CTE recursiva para calcular nivel de jerarquia de cada departamento
    -- Nivel raiz
    SELECT ID_DEPARTAMENTO, ID_DEPARTAMENTO_PADRE, 1 AS NIVEL_JERARQUIA
    FROM CLEANSED.DEPARTAMENTOS
    WHERE ID_DEPARTAMENTO_PADRE IS NULL
    UNION ALL
    -- Niveles hijo de forma recursiva
    SELECT d.ID_DEPARTAMENTO, d.ID_DEPARTAMENTO_PADRE, j.NIVEL_JERARQUIA + 1
    FROM CLEANSED.DEPARTAMENTOS d
    JOIN JERARQUIA j ON j.ID_DEPARTAMENTO = d.ID_DEPARTAMENTO_PADRE
)
UPDATE CONFORMED.DIM_DEPARTAMENTO t
SET
    NOMBRE_DEPARTAMENTO   = s.NOMBRE_DEPARTAMENTO,
    ID_DEPARTAMENTO_PADRE = s.ID_DEPARTAMENTO_PADRE,
    SK_DEPARTAMENTO_PADRE = (
        SELECT SK_DEPARTAMENTO
        FROM   CONFORMED.DIM_DEPARTAMENTO
        WHERE  ID_DEPARTAMENTO = s.ID_DEPARTAMENTO_PADRE
    ),
    NIVEL_JERARQUIA       = s.NIVEL_JERARQUIA,
    RESPONSABLE           = s.RESPONSABLE,
    TELEFONO_DEPARTAMENTO = s.TELEFONO_DEPARTAMENTO,
    EMAIL_DEPARTAMENTO    = s.EMAIL_DEPARTAMENTO
FROM (
    SELECT
        d.ID_DEPARTAMENTO,
        d.NOMBRE_DEPARTAMENTO,
        d.ID_DEPARTAMENTO_PADRE,
        j.NIVEL_JERARQUIA,
        d.NOMBRE_RESPONSABLE    AS RESPONSABLE,
        d.TELEFONO_DEPARTAMENTO,
        d.EMAIL_DEPARTAMENTO
    FROM CLEANSED.DEPARTAMENTOS d
    JOIN JERARQUIA j ON j.ID_DEPARTAMENTO = d.ID_DEPARTAMENTO
) s
WHERE t.ID_DEPARTAMENTO = s.ID_DEPARTAMENTO
  AND (
      t.NOMBRE_DEPARTAMENTO   IS DISTINCT FROM s.NOMBRE_DEPARTAMENTO   OR
      t.ID_DEPARTAMENTO_PADRE IS DISTINCT FROM s.ID_DEPARTAMENTO_PADRE OR
      t.NIVEL_JERARQUIA       IS DISTINCT FROM s.NIVEL_JERARQUIA       OR
      t.RESPONSABLE           IS DISTINCT FROM s.RESPONSABLE           OR
      t.TELEFONO_DEPARTAMENTO IS DISTINCT FROM s.TELEFONO_DEPARTAMENTO OR
      t.EMAIL_DEPARTAMENTO    IS DISTINCT FROM s.EMAIL_DEPARTAMENTO
  );


-- ============================================================
-- PASO 2: Insertar departamentos nuevos
-- SK_DEPARTAMENTO_PADRE se resuelve contra los registros ya
-- existentes en la dimension; queda NULL si el padre tambien
-- es nuevo en esta misma carga (se repara en el paso 3).
-- ============================================================
WITH JERARQUIA AS (
    SELECT ID_DEPARTAMENTO, ID_DEPARTAMENTO_PADRE, 1 AS NIVEL_JERARQUIA
    FROM CLEANSED.DEPARTAMENTOS
    WHERE ID_DEPARTAMENTO_PADRE IS NULL
    UNION ALL
    SELECT d.ID_DEPARTAMENTO, d.ID_DEPARTAMENTO_PADRE, j.NIVEL_JERARQUIA + 1
    FROM CLEANSED.DEPARTAMENTOS d
    JOIN JERARQUIA j ON j.ID_DEPARTAMENTO = d.ID_DEPARTAMENTO_PADRE
)
INSERT INTO CONFORMED.DIM_DEPARTAMENTO (
    ID_DEPARTAMENTO,
    NOMBRE_DEPARTAMENTO,
    ID_DEPARTAMENTO_PADRE,
    SK_DEPARTAMENTO_PADRE,
    NIVEL_JERARQUIA,
    RESPONSABLE,
    TELEFONO_DEPARTAMENTO,
    EMAIL_DEPARTAMENTO
)
SELECT
    d.ID_DEPARTAMENTO,
    d.NOMBRE_DEPARTAMENTO,
    d.ID_DEPARTAMENTO_PADRE,
    (
        SELECT SK_DEPARTAMENTO
        FROM   CONFORMED.DIM_DEPARTAMENTO
        WHERE  ID_DEPARTAMENTO = d.ID_DEPARTAMENTO_PADRE
    ),
    j.NIVEL_JERARQUIA,
    d.NOMBRE_RESPONSABLE    AS RESPONSABLE,
    d.TELEFONO_DEPARTAMENTO,
    d.EMAIL_DEPARTAMENTO
FROM CLEANSED.DEPARTAMENTOS d
JOIN JERARQUIA j ON j.ID_DEPARTAMENTO = d.ID_DEPARTAMENTO
WHERE NOT EXISTS (
    SELECT ID_DEPARTAMENTO FROM CONFORMED.DIM_DEPARTAMENTO
    WHERE ID_DEPARTAMENTO = d.ID_DEPARTAMENTO
);


-- ============================================================
-- PASO 3: Reparar SK_DEPARTAMENTO_PADRE que quedaron NULL
--         porque padre e hijo llegaron en la misma carga
-- ============================================================
UPDATE CONFORMED.DIM_DEPARTAMENTO t
SET    SK_DEPARTAMENTO_PADRE = p.SK_DEPARTAMENTO
FROM   CONFORMED.DIM_DEPARTAMENTO p
WHERE  t.ID_DEPARTAMENTO_PADRE = p.ID_DEPARTAMENTO
  AND  t.SK_DEPARTAMENTO_PADRE IS NULL
  AND  t.ID_DEPARTAMENTO_PADRE IS NOT NULL;


-- -- NOMBRE_RESPONSABLE AS RESPONSABLE en UPDATE e INSERT
-- -- NIVEL_JERARQUIA calculado con CTE recursiva en ambos pasos
--  — la CTE parte de los nodos raíz (sin padre) en nivel 1 y 
--  va sumando hacia abajo