-- dimension_medico.sql
-- Dimension SCD1/SCD2 de medicos
-- SCD1: Nombre, Apellidos, Numero_Colegiado, Telefono, Email
-- SCD2: Especialidad, Departamento
-- Fuente: CLEANSED.MEDICOS
--
-- Nota de nomenclatura:
-- APELLIDO1 || ' ' || APELLIDO2     → APELLIDOS
-- ESPECIALIDADES.NOMBRE_ESPECIALIDAD → ESPECIALIDAD  (JOIN por ID_ESPECIALIDAD)
-- DEPARTAMENTOS.NOMBRE_DEPARTAMENTO  → DEPARTAMENTO  (JOIN por CODIGO_DEPARTAMENTO)


CREATE SCHEMA IF NOT EXISTS CONFORMED;

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_MEDICO (
    SK_MEDICO          NUMBER        NOT NULL AUTOINCREMENT PRIMARY KEY,
    ID_MEDICO          NUMBER        NOT NULL,
    NOMBRE             VARCHAR(100)  NOT NULL,
    APELLIDOS          VARCHAR(200)  NOT NULL,
    NUMERO_COLEGIADO   VARCHAR(50)   NOT NULL,
    TELEFONO           VARCHAR(50),
    EMAIL              VARCHAR(100),
    ESPECIALIDAD       VARCHAR(200)  NOT NULL,  -- SCD2
    DEPARTAMENTO       VARCHAR(200),            -- SCD2
    FECHA_INICIO       DATE          NOT NULL,
    FECHA_FIN          DATE,
    ES_ACTUAL          BOOLEAN       NOT NULL   DEFAULT TRUE
);


CALL CONFORMED.SP_MERGE_SCD1_SCD2(
    'CONFORMED.DIM_MEDICO',
    'SELECT
        m.ID_MEDICO,
        m.NOMBRE,
        m.APELLIDO1 || '' '' || m.APELLIDO2  AS APELLIDOS,
        m.NUMERO_COLEGIADO,
        m.TELEFONO,
        m.EMAIL,
        esp.NOMBRE_ESPECIALIDAD              AS ESPECIALIDAD,
        dep.NOMBRE_DEPARTAMENTO              AS DEPARTAMENTO
     FROM CLEANSED.MEDICOS m
     LEFT JOIN CLEANSED.ESPECIALIDADES esp ON esp.ID_ESPECIALIDAD     = m.ID_ESPECIALIDAD
     LEFT JOIN CLEANSED.DEPARTAMENTOS  dep ON dep.CODIGO_DEPARTAMENTO = m.CODIGO_DEPARTAMENTO',
    'ID_MEDICO',
    'NOMBRE,APELLIDOS,NUMERO_COLEGIADO,TELEFONO,EMAIL',
    'ESPECIALIDAD,DEPARTAMENTO'
);
