-- dimension_fabricante.sql
-- Dimension SCD1 de fabricantes de equipos medicos
-- Fuente: CLEANSED_MEDICARE.FABRICANTES
--
-- Nota de nomenclatura: NOMBRE_FABRICANTE se mapea desde RAZON_SOCIAL en la fuente.
-- Se mantiene el nombre del spec en la dimension para mayor claridad en herramientas BI.


CREATE SCHEMA IF NOT EXISTS CONFORMED;

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_FABRICANTE (
    SK_FABRICANTE     NUMBER        NOT NULL AUTOINCREMENT PRIMARY KEY,
    ID_FABRICANTE     NUMBER        NOT NULL,
    NOMBRE_FABRICANTE VARCHAR(200)  NOT NULL,
    PAIS_ORIGEN       VARCHAR(100),
    TELEFONO_CONTACTO VARCHAR(50),
    EMAIL_CONTACTO    VARCHAR(100),
    SITIO_WEB         VARCHAR(200),
    CERTIFICACION_ISO VARCHAR(200)
);


-- ============================================================
-- PASO 1: SCD1 — actualizar en sitio sin guardar historial
-- ============================================================
UPDATE CONFORMED.DIM_FABRICANTE t
SET
    NOMBRE_FABRICANTE = s.NOMBRE_FABRICANTE,
    PAIS_ORIGEN       = s.PAIS_ORIGEN,
    TELEFONO_CONTACTO = s.TELEFONO_CONTACTO,
    EMAIL_CONTACTO    = s.EMAIL_CONTACTO,
    SITIO_WEB         = s.SITIO_WEB,
    CERTIFICACION_ISO = s.CERTIFICACION_ISO
FROM (
    SELECT
        ID_FABRICANTE,
        RAZON_SOCIAL      AS NOMBRE_FABRICANTE,
        PAIS_ORIGEN,
        TELEFONO_CONTACTO,
        EMAIL_CONTACTO,
        SITIO_WEB,
        CERTIFICACION_ISO
    FROM CLEANSED_MEDICARE.FABRICANTES
) s
WHERE t.ID_FABRICANTE = s.ID_FABRICANTE
  AND (
      t.NOMBRE_FABRICANTE IS DISTINCT FROM s.NOMBRE_FABRICANTE OR
      t.PAIS_ORIGEN       IS DISTINCT FROM s.PAIS_ORIGEN       OR
      t.TELEFONO_CONTACTO IS DISTINCT FROM s.TELEFONO_CONTACTO OR
      t.EMAIL_CONTACTO    IS DISTINCT FROM s.EMAIL_CONTACTO    OR
      t.SITIO_WEB         IS DISTINCT FROM s.SITIO_WEB         OR
      t.CERTIFICACION_ISO IS DISTINCT FROM s.CERTIFICACION_ISO
  );


-- ============================================================
-- PASO 2: INSERT — fabricantes nuevos que aun no existen
-- ============================================================
INSERT INTO CONFORMED.DIM_FABRICANTE (
    ID_FABRICANTE, NOMBRE_FABRICANTE, PAIS_ORIGEN,
    TELEFONO_CONTACTO, EMAIL_CONTACTO, SITIO_WEB, CERTIFICACION_ISO
)
SELECT
    ID_FABRICANTE,
    RAZON_SOCIAL      AS NOMBRE_FABRICANTE,
    PAIS_ORIGEN,
    TELEFONO_CONTACTO,
    EMAIL_CONTACTO,
    SITIO_WEB,
    CERTIFICACION_ISO
FROM CLEANSED_MEDICARE.FABRICANTES
WHERE NOT EXISTS (
    SELECT ID_FABRICANTE FROM CONFORMED.DIM_FABRICANTE
    WHERE ID_FABRICANTE = CLEANSED_MEDICARE.FABRICANTES.ID_FABRICANTE
);
