-- dimension_ubicacion.sql
-- Dimension SCD1 de ubicaciones fisicas del hospital
-- Fuente: CLEANSED_MEDICARE.UBICACIONES


CREATE SCHEMA IF NOT EXISTS CONFORMED;

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_UBICACION (
    SK_UBICACION NUMBER       NOT NULL AUTOINCREMENT PRIMARY KEY,
    ID_UBICACION NUMBER       NOT NULL,
    EDIFICIO     VARCHAR(200) NOT NULL,
    PLANTA       NUMBER,
    ALA          VARCHAR(50),
    SALA         VARCHAR(100) NOT NULL,
    TIPO_SALA    VARCHAR(100),
    CAPACIDAD    NUMBER
);


CALL CONFORMED.SP_MERGE_SCD1(
    'CONFORMED.DIM_UBICACION',
    'SELECT
        ID_UBICACION,
        EDIFICIO,
        PLANTA,
        ALA,
        SALA,
        TIPO_SALA,
        CAPACIDAD
     FROM CLEANSED_MEDICARE.UBICACIONES',
    'ID_UBICACION',
    'EDIFICIO,PLANTA,ALA,SALA,TIPO_SALA,CAPACIDAD'
);