-- dimension_ensayo.sql
-- Dimension SCD1 de ensayos clinicos
-- Fuente: CLEANSED_MEDICARE.ENSAYOS_CLINICOS
--
-- Nota de nomenclatura: tres columnas tienen nombres distintos entre la fuente y el spec.
-- Se mantienen los nombres del spec en la dimension y se resuelve con alias en el SELECT.
-- TITULO_ENSAYO → NOMBRE_ENSAYO | DESCRIPCION_ENSAYO → DESCRIPCION | FECHA_INICIO → FECHA_INICIO_ENSAYO


CREATE SCHEMA IF NOT EXISTS CONFORMED;

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_ENSAYO (
    SK_ENSAYO           NUMBER        NOT NULL AUTOINCREMENT PRIMARY KEY,
    ID_ENSAYO           NUMBER        NOT NULL,
    CODIGO_ENSAYO       VARCHAR(50)   NOT NULL,
    NOMBRE_ENSAYO       VARCHAR(300)  NOT NULL,
    DESCRIPCION         VARCHAR(500),
    PATROCINADOR        VARCHAR(200),
    FECHA_INICIO_ENSAYO DATE,
    FECHA_FIN_PREVISTA  DATE,
    ESTADO_ENSAYO       VARCHAR(50),
    OBJETIVO_PRINCIPAL  VARCHAR(500),
    MOLECULA_FARMACO    VARCHAR(200)
);


-- ============================================================
-- PASO 1: SCD1 — actualizar en sitio sin guardar historial
-- ============================================================
UPDATE CONFORMED.DIM_ENSAYO t
SET
    CODIGO_ENSAYO       = s.CODIGO_ENSAYO,
    NOMBRE_ENSAYO       = s.NOMBRE_ENSAYO,
    DESCRIPCION         = s.DESCRIPCION,
    PATROCINADOR        = s.PATROCINADOR,
    FECHA_INICIO_ENSAYO = s.FECHA_INICIO_ENSAYO,
    FECHA_FIN_PREVISTA  = s.FECHA_FIN_PREVISTA,
    ESTADO_ENSAYO       = s.ESTADO_ENSAYO,
    OBJETIVO_PRINCIPAL  = s.OBJETIVO_PRINCIPAL,
    MOLECULA_FARMACO    = s.MOLECULA_FARMACO
FROM (
    SELECT
        ID_ENSAYO,
        CODIGO_ENSAYO,
        TITULO_ENSAYO      AS NOMBRE_ENSAYO,
        DESCRIPCION_ENSAYO AS DESCRIPCION,
        PATROCINADOR,
        FECHA_INICIO       AS FECHA_INICIO_ENSAYO,
        FECHA_FIN_PREVISTA,
        ESTADO_ENSAYO,
        OBJETIVO_PRINCIPAL,
        MOLECULA_FARMACO
    FROM CLEANSED_MEDICARE.ENSAYOS_CLINICOS
) s
WHERE t.ID_ENSAYO = s.ID_ENSAYO
  AND (
      t.CODIGO_ENSAYO       IS DISTINCT FROM s.CODIGO_ENSAYO       OR
      t.NOMBRE_ENSAYO       IS DISTINCT FROM s.NOMBRE_ENSAYO       OR
      t.DESCRIPCION         IS DISTINCT FROM s.DESCRIPCION         OR
      t.PATROCINADOR        IS DISTINCT FROM s.PATROCINADOR        OR
      t.FECHA_INICIO_ENSAYO IS DISTINCT FROM s.FECHA_INICIO_ENSAYO OR
      t.FECHA_FIN_PREVISTA  IS DISTINCT FROM s.FECHA_FIN_PREVISTA  OR
      t.ESTADO_ENSAYO       IS DISTINCT FROM s.ESTADO_ENSAYO       OR
      t.OBJETIVO_PRINCIPAL  IS DISTINCT FROM s.OBJETIVO_PRINCIPAL  OR
      t.MOLECULA_FARMACO    IS DISTINCT FROM s.MOLECULA_FARMACO
  );


-- ============================================================
-- PASO 2: INSERT — ensayos nuevos que aun no existen
-- ============================================================
INSERT INTO CONFORMED.DIM_ENSAYO (
    ID_ENSAYO, CODIGO_ENSAYO, NOMBRE_ENSAYO, DESCRIPCION, PATROCINADOR,
    FECHA_INICIO_ENSAYO, FECHA_FIN_PREVISTA, ESTADO_ENSAYO,
    OBJETIVO_PRINCIPAL, MOLECULA_FARMACO
)
SELECT
    ID_ENSAYO,
    CODIGO_ENSAYO,
    TITULO_ENSAYO      AS NOMBRE_ENSAYO,
    DESCRIPCION_ENSAYO AS DESCRIPCION,
    PATROCINADOR,
    FECHA_INICIO       AS FECHA_INICIO_ENSAYO,
    FECHA_FIN_PREVISTA,
    ESTADO_ENSAYO,
    OBJETIVO_PRINCIPAL,
    MOLECULA_FARMACO
FROM CLEANSED_MEDICARE.ENSAYOS_CLINICOS
WHERE NOT EXISTS (
    SELECT ID_ENSAYO FROM CONFORMED.DIM_ENSAYO
    WHERE ID_ENSAYO = CLEANSED_MEDICARE.ENSAYOS_CLINICOS.ID_ENSAYO
);
