-- dimension_ensayo.sql
-- Dimension SCD1 de ensayos clinicos
-- Fuente: CLEANSED_MEDICARE.ENSAYOS_CLINICOS
--
-- Nota de nomenclatura: tres columnas tienen nombres distintos entre la fuente y el spec.
-- Se mantienen los nombres del spec en la dimension y se resuelve con alias en el SELECT.
-- TITULO_ENSAYO → NOMBRE_ENSAYO | DESCRIPCION_ENSAYO → DESCRIPCION | FECHA_INICIO → FECHA_INICIO_ENSAYO


CREATE SCHEMA IF NOT EXISTS CONFORMED;

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_ENSAYO (
    SK_ENSAYO           NUMBER        NOT NULL AUTOINCREMENT PRIMARY KEY,
    ID_ENSAYO           NUMBER        NOT NULL,
    CODIGO_ENSAYO       VARCHAR(50)   NOT NULL,
    NOMBRE_ENSAYO       VARCHAR(300)  NOT NULL,
    DESCRIPCION         VARCHAR(500),
    PATROCINADOR        VARCHAR(200),
    FECHA_INICIO_ENSAYO DATE,
    FECHA_FIN_PREVISTA  DATE,
    ESTADO_ENSAYO       VARCHAR(50),
    OBJETIVO_PRINCIPAL  VARCHAR(500),
    MOLECULA_FARMACO    VARCHAR(200)
);


CALL CONFORMED.SP_MERGE_SCD1(
    'CONFORMED.DIM_ENSAYO',
    'SELECT
        ID_ENSAYO,
        CODIGO_ENSAYO,
        TITULO_ENSAYO      AS NOMBRE_ENSAYO,
        DESCRIPCION_ENSAYO AS DESCRIPCION,
        PATROCINADOR,
        FECHA_INICIO       AS FECHA_INICIO_ENSAYO,
        FECHA_FIN_PREVISTA,
        ESTADO_ENSAYO,
        OBJETIVO_PRINCIPAL,
        MOLECULA_FARMACO
     FROM CLEANSED_MEDICARE.ENSAYOS_CLINICOS',
    'ID_ENSAYO',
    'CODIGO_ENSAYO,NOMBRE_ENSAYO,DESCRIPCION,PATROCINADOR,FECHA_INICIO_ENSAYO,FECHA_FIN_PREVISTA,ESTADO_ENSAYO,OBJETIVO_PRINCIPAL,MOLECULA_FARMACO'
);
