-- dimension_equipo.sql
-- Dimension SCD1/SCD2 de equipos medicos
-- SCD1: Nombre_Equipo, Descripcion, Numero_Serie, Modelo, Fecha_Adquisicion, Fecha_Fin_Garantia, Clase_Riesgo
-- SCD2: Estado_Equipo, Departamento_Actual, Ubicacion_Actual
-- Fuente: CLEANSED.EQUIPOS JOIN DEPARTAMENTOS JOIN UBICACIONES



CREATE SCHEMA IF NOT EXISTS CONFORMED;

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_EQUIPO (
    SK_EQUIPO           NUMBER          NOT NULL AUTOINCREMENT PRIMARY KEY,
    ID_EQUIPO           NUMBER          NOT NULL,
    NOMBRE_EQUIPO       VARCHAR(200)    NOT NULL,
    DESCRIPCION         VARCHAR(500),
    NUMERO_SERIE        VARCHAR(100)    NOT NULL,
    MODELO              VARCHAR(200),
    FECHA_ADQUISICION   DATE,
    FECHA_FIN_GARANTIA  DATE,
    ESTADO_EQUIPO       VARCHAR(50)     NOT NULL,   -- SCD2
    CLASE_RIESGO        VARCHAR(10)     NOT NULL,
    DEPARTAMENTO_ACTUAL VARCHAR(200),               -- SCD2
    UBICACION_ACTUAL    VARCHAR(200),               -- SCD2
    FECHA_INICIO        DATE            NOT NULL,
    FECHA_FIN           DATE,
    ES_ACTUAL           BOOLEAN         NOT NULL    DEFAULT TRUE
);


CALL CONFORMED.SP_MERGE_SCD1_SCD2(
    'CONFORMED.DIM_EQUIPO',
    'SELECT
        e.ID_EQUIPO,
        e.NOMBRE_EQUIPO,
        e.DESCRIPCION,
        e.NUMERO_SERIE,
        e.MODELO,
        e.FECHA_ADQUISICION,
        e.FECHA_FIN_GARANTIA,
        e.CLASE_RIESGO,
        CASE e.ESTADO_CODIGO
            WHEN 1 THEN ''Activo''
            WHEN 2 THEN ''En Reparacion''
            WHEN 3 THEN ''Fuera de Servicio''
            WHEN 4 THEN ''Baja''
        END                              AS ESTADO_EQUIPO,
        d.NOMBRE_DEPARTAMENTO            AS DEPARTAMENTO_ACTUAL,
        u.EDIFICIO || '' - '' || u.SALA  AS UBICACION_ACTUAL
     FROM CLEANSED.EQUIPOS e
     LEFT JOIN CLEANSED.DEPARTAMENTOS d ON e.ID_DEPARTAMENTO = d.ID_DEPARTAMENTO
     LEFT JOIN CLEANSED.UBICACIONES   u ON e.ID_UBICACION    = u.ID_UBICACION',
    'ID_EQUIPO',
    'NOMBRE_EQUIPO,DESCRIPCION,NUMERO_SERIE,MODELO,FECHA_ADQUISICION,FECHA_FIN_GARANTIA,CLASE_RIESGO',
    'ESTADO_EQUIPO,DEPARTAMENTO_ACTUAL,UBICACION_ACTUAL'
);

