-- dimension_fabricante.sql
-- Dimension SCD1 de fabricantes de equipos medicos
-- Fuente: CLEANSED.FABRICANTES
--
-- Nota de nomenclatura: NOMBRE_FABRICANTE se mapea desde RAZON_SOCIAL en la fuente.
-- Se mantiene el nombre del spec en la dimension para mayor claridad en herramientas BI.


CREATE SCHEMA IF NOT EXISTS CONFORMED;

CREATE TABLE IF NOT EXISTS CONFORMED.DIM_FABRICANTE (
    SK_FABRICANTE     NUMBER        NOT NULL AUTOINCREMENT PRIMARY KEY,
    ID_FABRICANTE     NUMBER        NOT NULL,
    NOMBRE_FABRICANTE VARCHAR(200)  NOT NULL,
    PAIS_ORIGEN       VARCHAR(100),
    TELEFONO_CONTACTO VARCHAR(50),
    EMAIL_CONTACTO    VARCHAR(100),
    SITIO_WEB         VARCHAR(200),
    CERTIFICACION_ISO VARCHAR(200)
);


CALL CONFORMED.SP_MERGE_SCD1(
    'CONFORMED.DIM_FABRICANTE',
    'SELECT
        ID_FABRICANTE,
        RAZON_SOCIAL      AS NOMBRE_FABRICANTE,
        PAIS_ORIGEN,
        TELEFONO_CONTACTO,
        EMAIL_CONTACTO,
        SITIO_WEB,
        CERTIFICACION_ISO
     FROM CLEANSED.FABRICANTES',
    'ID_FABRICANTE',
    'NOMBRE_FABRICANTE,PAIS_ORIGEN,TELEFONO_CONTACTO,EMAIL_CONTACTO,SITIO_WEB,CERTIFICACION_ISO'
);
